/** 365 daily quotes for Aries — one for every day of the year. */
export const ariesDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new fire. You were born to begin things — make today the first spark of something extraordinary.",
  "Jan 2": "Patience isn't your default setting, but today it's your superpower. Slow burns create lasting heat.",
  "Jan 3": "Your instincts are razor-sharp right now. Trust that gut feeling — it knows before your mind catches up.",
  "Jan 4": "Channel your competitive energy inward today. The only person worth outrunning is yesterday's version of you.",
  "Jan 5": "Someone needs your directness today. Say the thing everyone's thinking but nobody has the courage to voice.",
  "Jan 6": "Rest doesn't mean retreat. Even the fiercest warriors sharpen their swords between battles.",
  "Jan 7": "Your enthusiasm is contagious — use it to lift someone who's been running on empty.",
  "Jan 8": "A bold idea is forming. Don't overthink it. Aries energy rewards action over analysis.",
  "Jan 9": "Conflict may surface today. Remember: you can be right and still be kind. Choose both.",
  "Jan 10": "Your body is asking for movement. Honor that fire — run, dance, stretch, or just walk fast with purpose.",
  "Jan 11": "Something you started months ago is about to show results. Your persistence is paying off quietly.",
  "Jan 12": "Anger is information. Before you react, ask: what boundary was crossed? Then act from clarity, not heat.",
  "Jan 13": "Today favors the brave. Take that risk you've been circling. Fortune literally favors the bold — that's you.",
  "Jan 14": "Your independence is a gift, but today, let someone help. Receiving is its own kind of strength.",
  "Jan 15": "Creativity is surging. Whatever medium calls to you — words, images, movement — follow it without judgment.",
  "Jan 16": "You're more sensitive than you let on. Today, honor that softness. It doesn't diminish your fire; it deepens it.",
  "Jan 17": "A fresh start is available in some area of your life. You're the zodiac's expert at beginning again. Use that.",
  "Jan 18": "Your loyalty is being tested. Stay true to your principles — they're the foundation your courage stands on.",
  "Jan 19": "Impatience is just passion without a target. Find the target today and watch everything click.",
  "Jan 20": "The spotlight finds you naturally. Today, use it to illuminate someone else. Generosity amplifies your fire.",
  "Jan 21": "An old pattern is ready to break. You have the courage to do what others won't — start with yourself.",
  "Jan 22": "Your honesty cuts through illusions today. People may wince, but they'll thank you later.",
  "Jan 23": "Adventure is calling — even if it's just a new route to work or an unfamiliar restaurant. Feed the explorer in you.",
  "Jan 24": "You're processing something deeper than you realize. Give yourself space to feel before you act.",
  "Jan 25": "Leadership isn't about being first; it's about making others believe they can follow. Inspire today.",
  "Jan 26": "Your energy is magnetic right now. Whatever you focus on will multiply. Choose your focus wisely.",
  "Jan 27": "A conversation that's been avoided needs your signature directness. Clear the air with courage and compassion.",
  "Jan 28": "Burnout is not a badge of honor. If your flame feels dim, it's asking for fuel, not more wind.",
  "Jan 29": "Something unexpected may redirect your day. Roll with it — spontaneity is where you thrive.",
  "Jan 30": "Your protective instincts are activated. Stand up for someone who can't speak for themselves today.",
  "Jan 31": "The month ends on your terms. Reflect on what you initiated, and be proud of the energy you brought.",

  // ── February ──
  "Feb 1": "February asks for heart over hustle. Let warmth lead your actions today.",
  "Feb 2": "Your determination is unmatched, but today, flex your adaptability. Strength bends before it breaks.",
  "Feb 3": "A burst of creative energy hits. Channel it into something tangible before the spark fades.",
  "Feb 4": "You're being asked to lead with empathy today. Your fire can warm as well as burn.",
  "Feb 5": "Competition energizes you, but collaboration will take you further today. Find your allies.",
  "Feb 6": "Physical energy is high. Push your body — it wants to feel alive and powerful.",
  "Feb 7": "Someone underestimates you today. Let your results do the talking. Silence is its own kind of roar.",
  "Feb 8": "Your need for speed might clash with reality's pace. Use the tension as fuel, not frustration.",
  "Feb 9": "Romance or passion stirs. Whether with a person or a project — lean into what excites you.",
  "Feb 10": "The truth you've been avoiding is ready to be faced. You're brave enough. You always were.",
  "Feb 11": "Your inner child wants to play today. Let them. Joy is not frivolous — it's essential.",
  "Feb 12": "A financial or practical decision needs your attention. Apply your warrior focus to the mundane — it pays off.",
  "Feb 13": "Love is an act of courage for you. Today, be brave enough to show someone exactly how you feel.",
  "Feb 14": "Your heart burns hotter than most. Whether partnered or solo, celebrate the passion that makes you, you.",
  "Feb 15": "Frustration may simmer beneath the surface. Channel it into creation, not destruction.",
  "Feb 16": "You're planting seeds that won't bloom for months. Trust the process, even when you can't see progress.",
  "Feb 17": "Your natural authority shines today. People look to you for direction — give it clearly and kindly.",
  "Feb 18": "A new cycle begins. As the zodiac's initiator, you feel this shift more than most. Set your intention.",
  "Feb 19": "Vulnerability is your hidden strength. Today, crack the armor just enough to let someone see the real you.",
  "Feb 20": "Your restlessness has a message. Listen to what it's telling you about what needs to change.",
  "Feb 21": "Bold moves are rewarded now. That leap you've been considering? The net appears after you jump.",
  "Feb 22": "Forgiveness is a warrior's act. Release something you've been carrying — it's slowing your charge.",
  "Feb 23": "Your opinions are strong, but today, try listening twice as much as you speak. You'll be surprised.",
  "Feb 24": "Energy flows toward what matters most to you. Guard your attention like it's sacred — because it is.",
  "Feb 25": "A friend needs the fire only you can bring. Show up with your full, unfiltered warmth.",
  "Feb 26": "You're at your best when challenge meets passion. Seek out something that demands your A-game.",
  "Feb 27": "The past is trying to teach you something. Pause long enough to hear the lesson before charging ahead.",
  "Feb 28": "Endings are just beginnings wearing a different outfit. You know this better than anyone.",
  "Feb 29": "Rare day, rare energy. If this is your year, do something you've never done. If not, pretend it is anyway.",

  // ── March ──
  "Mar 1": "March opens with fire in the air. Your season approaches — feel the anticipation building in your veins.",
  "Mar 2": "Your intuition is louder than usual. Pay attention to the whispers — they're leading somewhere important.",
  "Mar 3": "A creative project needs your initiating force. Start messy. Start now. Perfection can come later.",
  "Mar 4": "You don't owe anyone a polished version of yourself. Show up raw and real today — it's more than enough.",
  "Mar 5": "Movement is medicine today. Your body has wisdom your mind hasn't caught up with yet.",
  "Mar 6": "A relationship dynamic is shifting. Lead with honesty, and let the chips fall. Authenticity over harmony.",
  "Mar 7": "Your ambition is beautiful, but today, check whose dream you're chasing. Make sure it's yours.",
  "Mar 8": "Courage takes many forms. Today, the bravest thing might be saying no.",
  "Mar 9": "You're a natural motivator. Someone in your circle is silently struggling — your words could reignite them.",
  "Mar 10": "The urge to rush is strong. But the thing worth having is worth building at the right pace.",
  "Mar 11": "Conflict doesn't scare you — but today, choose peace as an act of power, not weakness.",
  "Mar 12": "Your fire sign energy harmonizes with a grounded moment today. Slow down just enough to savor the details.",
  "Mar 13": "An opportunity lands that matches your skill set perfectly. Trust your reflexes and say yes.",
  "Mar 14": "Your inner warrior needs rest, not retirement. Recovery is part of the fight plan.",
  "Mar 15": "Something you've been fighting for is about to break through. Keep the pressure on — you're closer than you think.",
  "Mar 16": "Today, lead with your heart instead of your head. Your instincts are emotionally intelligent right now.",
  "Mar 17": "Luck favors action. Make your own fortune today with bold choices and decisive energy.",
  "Mar 18": "You're shedding an old story about who you had to be. The new chapter starts with who you choose to become.",
  "Mar 19": "On the eve of your season, reflect on what you've survived. You are stronger than every challenge that tried you.",
  "Mar 20": "Spring ignites and so do you. Your cosmic new year is here — set intentions that match your fire.",
  "Mar 21": "Happy Aries season. This is YOUR time. The universe conspires for those who move with purpose — and that's you.",
  "Mar 22": "Birthday energy surrounds you. What do you want this year to mean? Name it boldly and chase it.",
  "Mar 23": "Your charisma is at peak wattage. Use it for good — inspire, encourage, and push others toward their potential.",
  "Mar 24": "The stars amplify your natural courage today. Take on something that would terrify a lesser sign.",
  "Mar 25": "You radiate warmth and fire today. Everyone around you feels more alive in your presence.",
  "Mar 26": "A passion project deserves your full attention. Give it the same intensity you give everything you love.",
  "Mar 27": "Your pioneering spirit is needed somewhere new. Explore unfamiliar territory — literally or metaphorically.",
  "Mar 28": "Today, your directness is a healing force. Speak truthfully and watch walls come down.",
  "Mar 29": "Energy is abundant. Don't scatter it across a dozen things — aim it like an arrow at your biggest priority.",
  "Mar 30": "Your season is in full swing. Own every room you walk into. You belong there.",
  "Mar 31": "As March closes, feel the fire you've built this month. You're unstoppable when you choose to be.",

  // ── April ──
  "Apr 1": "Playfulness is power. Today, be the Aries who laughs loudest and loves hardest.",
  "Apr 2": "Your impatience is trying to tell you something meaningful. Listen to its message before silencing it.",
  "Apr 3": "A door that seemed closed is cracking open. Push. You have the strength.",
  "Apr 4": "Financial confidence grows when you trust your instincts. Make the money move you've been researching.",
  "Apr 5": "Your bluntness may need softening today — the message matters, but so does the delivery.",
  "Apr 6": "Physical vitality is high. Use it. Your body is your greatest instrument — play it well.",
  "Apr 7": "An old rivalry or grudge surfaces. You can choose to reignite it or release it. Freedom tastes better than revenge.",
  "Apr 8": "Your enthusiasm inspires a team or group today. When you believe, others can't help but follow.",
  "Apr 9": "Take a risk in love or creativity today. Half-hearted attempts are beneath you.",
  "Apr 10": "The universe rewards your courage today with a small but meaningful win. Celebrate it.",
  "Apr 11": "Slow down long enough to notice what's blooming around you. Spring reflects your own renewal.",
  "Apr 12": "A leadership role is being offered — officially or informally. Step up without hesitation.",
  "Apr 13": "Your protective instincts flare. Channel them wisely — defend what matters, release what doesn't.",
  "Apr 14": "Burnout looms if you don't pause. Your fire is sustainable only when fed, not forced.",
  "Apr 15": "Your competitive edge gives you an advantage today. Use it in service of a goal, not your ego.",
  "Apr 16": "Something creative wants to be born through you. Stop planning and start making.",
  "Apr 17": "Your honesty today clears a path that diplomacy never could. Sometimes blunt truth is the kindest option.",
  "Apr 18": "An unexpected encounter shifts your perspective. Stay open — the universe delivers teachers in strange packages.",
  "Apr 19": "Your Aries season closes soon. Make one more bold move before the spotlight shifts. Leave your mark.",
  "Apr 20": "Transition energy is here. You hand the baton gracefully — knowing you lit a fire others will carry forward.",
  "Apr 21": "Even outside your season, your fire doesn't dim. It just finds subtler ways to burn.",
  "Apr 22": "Earth energy grounds your fire today. Plant something — a seed, an idea, a commitment.",
  "Apr 23": "Your head and heart disagree. Trust the one that speaks with less fear.",
  "Apr 24": "A challenge at work or home demands your signature tenacity. You were built for this.",
  "Apr 25": "Play is not optional for you — it's how you recharge. Build something fun into your day.",
  "Apr 26": "Your capacity for fresh starts is unmatched. If something isn't working, pivot without guilt.",
  "Apr 27": "A friend or partner mirrors something back to you that stings. Sit with it before reacting.",
  "Apr 28": "Your ambition and your need for rest are not in conflict. They take turns, and today is rest's turn.",
  "Apr 29": "The fire within you today is calm and steady — like a hearth, not a wildfire. Enjoy the warmth.",
  "Apr 30": "April ends with quiet confidence. You've shown up, pushed through, and stayed true. That's always enough.",

  // ── May ──
  "May 1": "Taurus season slows the world down, but your fire adapts. Find power in patience today.",
  "May 2": "A sensory experience — great food, nature, music — feeds your spirit more than you expect.",
  "May 3": "Your directness cuts through Taurus stubbornness today. Speak up when things feel stuck.",
  "May 4": "Financial clarity comes when you combine Aries boldness with practical planning. Make it happen.",
  "May 5": "Your body craves something new — a different workout, a new trail, a spontaneous dance. Listen.",
  "May 6": "Loyalty is tested quietly today. Show up for someone even when it's not exciting to do so.",
  "May 7": "A creative block dissolves when you stop thinking and start doing. Action unlocks inspiration.",
  "May 8": "You may feel slowed by the current cosmic pace. Use the friction to build discipline, not frustration.",
  "May 9": "Romance speaks in actions, not words, today. Show love through what you do, not what you say.",
  "May 10": "Your inner fire is recalibrating. This quiet phase is building something powerful beneath the surface.",
  "May 11": "Someone challenges your ideas today. Rather than defending, get curious. Growth lives in the tension.",
  "May 12": "Your leadership style shifts toward mentoring today. Teach someone what you've learned the hard way.",
  "May 13": "Impulsive spending calls. Pause before you swipe — make sure it's passion, not boredom, driving the purchase.",
  "May 14": "A risk in your personal life pays off emotionally. Openness is brave, and bravery is your birthright.",
  "May 15": "Midway through the month, check your energy reserves. You give a lot — are you receiving enough?",
  "May 16": "Nature grounds your fire beautifully today. Spend time outside, even briefly. It resets everything.",
  "May 17": "Your competitive spirit finds a healthy outlet. Push yourself in a way that builds you up, not tears others down.",
  "May 18": "An unexpected kindness from a stranger reminds you that the world matches your energy. Burn bright.",
  "May 19": "Stubbornness and determination look similar but feel different. Check which one you're running on.",
  "May 20": "A chapter closes quietly today. You don't always need fireworks — sometimes grace is the bravest exit.",
  "May 21": "Gemini energy brings mental stimulation. Engage your curious side — read, debate, explore ideas.",
  "May 22": "Your communication sharpens today. The perfect words find you when you speak from conviction.",
  "May 23": "A partnership or collaboration opportunity arises. Your independence is an asset, not a barrier, within a team.",
  "May 24": "Restlessness signals growth, not discontent. Something bigger is calling — lean toward it.",
  "May 25": "Physical energy peaks. Challenge your body and it will remind you how powerful you are.",
  "May 26": "A confrontation you've been avoiding can be handled with grace and fire. You don't have to choose one.",
  "May 27": "Your instinct to protect your loved ones is beautiful. Just make sure they also feel your tenderness.",
  "May 28": "Joy arrives in an unexpected form today. Be open to delight from surprising sources.",
  "May 29": "Review your goals from the start of the year. Aries adjusts trajectory better than anyone — course-correct now.",
  "May 30": "Your energy inspires someone silently watching you. Never underestimate the power of simply being yourself.",
  "May 31": "May ends with a deep breath. You've earned the pause. Tomorrow, the fire builds again.",

  // ── June ──
  "Jun 1": "June brings lightness. Let your heavy intensity soften into playful confidence today.",
  "Jun 2": "Communication is your key to connection today. Say the brave thing — gently.",
  "Jun 3": "Dual energies pull you in two directions. Don't choose yet — explore both possibilities.",
  "Jun 4": "Your mental energy rivals your physical fire today. Use it for strategy and visioning.",
  "Jun 5": "A social gathering recharges you more than expected. Community fuels your flame.",
  "Jun 6": "Your signature impatience meets an invitation to wait. Something better is forming — give it time.",
  "Jun 7": "Curiosity leads you somewhere unexpected and wonderful today. Follow the thread.",
  "Jun 8": "A conversation changes your perspective on something you were certain about. Let it land.",
  "Jun 9": "Your courage inspires someone to take their own leap. You may never know the ripple you cause.",
  "Jun 10": "Creative energy demands expression. Draw, write, build, move — anything that externalizes the fire.",
  "Jun 11": "A small act of service brings unexpected fulfillment. Your power multiplies when given to others.",
  "Jun 12": "Romantic tension or excitement surfaces. Follow it without overthinking — your heart is smarter than you credit.",
  "Jun 13": "Your ability to cut through noise and get to the point is needed today. Be the voice of clarity.",
  "Jun 14": "Rest is not failure. It's preparation for the next triumph. Take it without guilt.",
  "Jun 15": "The halfway point of the year. Aries, you've already done more than most. But you're just warming up.",
  "Jun 16": "An old dream resurfaces. Examine it with fresh eyes — is it still yours, or has it evolved?",
  "Jun 17": "Your fierce loyalty is tested. Stay steady. The people who deserve your fire will earn it.",
  "Jun 18": "Your intuition about a situation is correct. Act on it before doubt creeps in.",
  "Jun 19": "A physical challenge beckons — a hike, a race, a dare. Your body says yes. Listen.",
  "Jun 20": "The longest day approaches. Let your fire match the sun's — burn bright and purposeful.",
  "Jun 21": "Summer solstice ignites your boldest self. Set the intention that scares you most — then chase it.",
  "Jun 22": "Emotional depth surprises you today. Let yourself feel fully — it doesn't weaken you; it completes you.",
  "Jun 23": "Your need for independence and your need for connection can coexist. Hold both today.",
  "Jun 24": "A creative breakthrough arrives when you stop forcing and start flowing. Ease is not laziness.",
  "Jun 25": "Someone calls you fearless today. You know the truth — you feel every fear, you just move anyway.",
  "Jun 26": "Financial energy favors bold but informed decisions. Research, then leap.",
  "Jun 27": "Your energy shifts inward briefly. Honor the introspection — even fire needs to curl before it leaps.",
  "Jun 28": "A playful, childlike joy wants your attention. Give in. Not everything needs to be intense.",
  "Jun 29": "Transformation happens quietly today. You won't notice it until you look back. Trust the process.",
  "Jun 30": "Half the year is behind you. Aries, you've been a force. The second half asks for fire with finesse.",

  // ── July ──
  "Jul 1": "Cancer season stirs your protective instincts. Guard the people and dreams that matter most.",
  "Jul 2": "Your emotions run deeper than your brash exterior lets on. Today, let someone see beneath the armor.",
  "Jul 3": "Home or family matters need your attention. Bring your warrior spirit to domestic life — gently.",
  "Jul 4": "Freedom is your core value. Celebrate it today in whatever form makes your spirit soar.",
  "Jul 5": "A nurturing gesture from you would surprise and delight someone. Show your softer side.",
  "Jul 6": "Your fire meets water energy today. The steam creates clarity you didn't expect.",
  "Jul 7": "Nostalgia visits. Look back with gratitude, then turn around and charge forward. The past is a teacher, not a home.",
  "Jul 8": "Your need for action may conflict with a call to rest. The bravest move today might be doing nothing.",
  "Jul 9": "An emotional truth surfaces that demands your famous honesty — directed inward this time.",
  "Jul 10": "Your physical energy fluctuates. Ride the waves instead of forcing consistency.",
  "Jul 11": "A family member or close friend needs your strength today. Show up fully — it's what you do best.",
  "Jul 12": "Creativity blooms when you feel safe. Build that safety today — then watch ideas pour out.",
  "Jul 13": "Frustration with slow progress is natural for you. But roots grow in the dark. Trust what you can't see.",
  "Jul 14": "Your competitive fire finds an unexpected outlet. Channel it into something that builds rather than battles.",
  "Jul 15": "Mid-month brings emotional clarity. The confusion was a cocoon — what's emerging is stronger.",
  "Jul 16": "Your instinct to lead is powerful today. Lead from the kitchen, the heart, or the boardroom — wherever you are.",
  "Jul 17": "Water energy asks you to flow rather than forge. Try flexibility over force today.",
  "Jul 18": "An old wound surfaces for healing. Your courage makes you uniquely capable of facing it.",
  "Jul 19": "Your passion for life is infectious today. Spread it generously — the world needs your fire.",
  "Jul 20": "Domesticity doesn't trap you; it grounds you. Find beauty in the everyday today.",
  "Jul 21": "A bold conversation at home clears tension that's been building. You're the one brave enough to start it.",
  "Jul 22": "Your emotional intelligence is sharper than people credit. Use it quietly and watch dynamics shift.",
  "Jul 23": "Leo season arrives, and your fire sign kinship ignites. Time to shine alongside the lion.",
  "Jul 24": "Collaboration with another fire sign or fiery personality creates magic. Seek out your energetic match.",
  "Jul 25": "Your generosity of spirit is your hidden superpower. Give freely today — it returns tenfold.",
  "Jul 26": "Adventure calls louder than routine today. Even a micro-adventure counts. Break the pattern.",
  "Jul 27": "Your body knows what it needs. Stop overriding its signals with willpower. Listen instead.",
  "Jul 28": "A risk taken in love or friendship leads somewhere beautiful. Vulnerability is your bravest act.",
  "Jul 29": "The fire in your belly is creative today, not combative. Build something instead of breaking through something.",
  "Jul 30": "Confidence is not arrogance when it's earned. You've earned yours. Wear it openly.",
  "Jul 31": "July closes with a sense of emotional grounding you rarely feel. Savor it. This is growth.",

  // ── August ──
  "Aug 1": "Leo season amplifies your natural fire. Today, be unapologetically bold.",
  "Aug 2": "Your creative and romantic fires burn equally bright. Feed whichever calls louder.",
  "Aug 3": "Recognition or praise comes your way. Accept it gracefully — you don't have to deflect to be humble.",
  "Aug 4": "Your leadership is magnetic today. People don't just follow you — they believe in you.",
  "Aug 5": "A playful competition or challenge brings out your best. Fun and fire go hand in hand.",
  "Aug 6": "Your heart opens wider than usual today. Let it. The world needs more fierce love.",
  "Aug 7": "Action over analysis. You've done enough planning — execute with Aries precision today.",
  "Aug 8": "Your loyalty is rewarded by someone who finally sees and matches it. Reciprocity feels like home.",
  "Aug 9": "Creative fire is at peak intensity. Make the art, start the project, write the thing. Now.",
  "Aug 10": "Your physical presence commands attention today. Walk tall, breathe deep, take up space.",
  "Aug 11": "An old ambition gets reignited by a new possibility. Your fire never truly goes out — it just smolders.",
  "Aug 12": "Your courage to be authentic gives others permission to do the same. That's leadership.",
  "Aug 13": "Romantic boldness pays off whether it's a first move or a renewal gesture. Love favors the fearless.",
  "Aug 14": "The sun fuels your vitality today. Spend time in light — literal or metaphorical.",
  "Aug 15": "Your drive is relentless and beautiful. But today, drive toward rest with equal intensity.",
  "Aug 16": "A moment of pure, unplanned joy reminds you why being alive is the greatest adventure.",
  "Aug 17": "Your fire inspires a younger person or someone just starting their journey. Be the torch that lights another.",
  "Aug 18": "Strategy combines with instinct today. Plan with your head, execute with your gut.",
  "Aug 19": "Your passions don't have to make sense to anyone else. Honor what lights you up, even if it surprises people.",
  "Aug 20": "The heat of August mirrors your inner intensity. Use this alignment to push toward a big goal.",
  "Aug 21": "A transition approaches. Aries handles change better than most — lean into the shift with confidence.",
  "Aug 22": "Your fire matures today. You're learning that strength can be quiet and power can be gentle.",
  "Aug 23": "Virgo season begins. Precision and attention to detail — not your comfort zone, but exactly what growth requires.",
  "Aug 24": "Slow down your natural pace just slightly. The details you usually skip contain treasures.",
  "Aug 25": "Your health and daily routines deserve the same passion you give your ambitions. Optimize the basics.",
  "Aug 26": "Someone's careful, methodical approach teaches you something today. Not every problem needs a battering ram.",
  "Aug 27": "Your body asks for cleaner fuel today. Honor it with nutrition that matches your athletic spirit.",
  "Aug 28": "A practical problem needs solving. Apply your warrior focus to logistics — you're better at it than you think.",
  "Aug 29": "Your impatience with inefficiency is valid, but today, be the solution instead of the critic.",
  "Aug 30": "A mentor or guide appears — possibly in the form of a book, a conversation, or a quiet realization.",
  "Aug 31": "August ends with a sense of quiet accomplishment. Your fire built something real this month.",

  // ── September ──
  "Sep 1": "September asks for refinement. You've charged ahead — now polish what you've built.",
  "Sep 2": "Your attention to detail improves when you channel your intensity into focus instead of speed.",
  "Sep 3": "A health routine or habit change sticks better when fueled by Aries determination. Start today.",
  "Sep 4": "Your mind is sharp as a blade today. Use it to analyze, plan, and strategize — then strike.",
  "Sep 5": "Service to others doesn't diminish your fire — it gives it purpose. Help someone today.",
  "Sep 6": "Perfectionism isn't your style, but precision is. Find the sweet spot between bold and meticulous.",
  "Sep 7": "An organizational task you've been dreading takes Aries willpower to tackle. Do it today and feel the relief.",
  "Sep 8": "Your body and mind crave alignment. A workout, a journaling session, or meditation brings both into sync.",
  "Sep 9": "A colleague or friend's quiet competence inspires a new approach. Flashy isn't always fierce.",
  "Sep 10": "Your work ethic peaks when it's challenged. Seek the task that pushes you beyond comfortable.",
  "Sep 11": "Compassion requires courage — and you have plenty of both. Extend grace to someone today.",
  "Sep 12": "Your instinct to pioneer applies to wellness too. Try a new practice that intrigues you.",
  "Sep 13": "The mundane holds magic when you approach it with full presence. Even chores become meditation today.",
  "Sep 14": "Communication clarity matters more than usual. Say exactly what you mean — no more, no less.",
  "Sep 15": "You're midway through a growth phase. The discomfort you feel is the stretch of becoming.",
  "Sep 16": "Your fiery optimism balances the critical energy around you. Be the voice of 'we can do this.'",
  "Sep 17": "A small act of discipline today creates a cascade of results this week. Start the domino.",
  "Sep 18": "Your fierceness softens into focused determination. This mature fire builds empires.",
  "Sep 19": "An intellectual debate sharpens your perspective. Engage with ideas that challenge your certainties.",
  "Sep 20": "Your relationship with your body is a partnership. Today, listen to what it needs before pushing harder.",
  "Sep 21": "Autumn approaches. Like the trees, you're letting go of what's no longer needed to make room for what's coming.",
  "Sep 22": "Libra season begins. Balance, partnership, and diplomacy — your growth edges, and exactly what makes you better.",
  "Sep 23": "Harmony doesn't mean surrender. Today, practice holding your ground while holding someone's hand.",
  "Sep 24": "Your opposite sign's energy teaches through contrast. What does balance look like when you stop fighting for it?",
  "Sep 25": "Partnership energy is high today. Whether romantic, creative, or professional — two fires burn brighter than one.",
  "Sep 26": "Beauty, art, and aesthetics catch your attention more than usual. Your fire has an eye for design — follow it.",
  "Sep 27": "A compromise doesn't mean you lost. It means you chose something bigger than being right.",
  "Sep 28": "Your charm is subtle and disarming today. Use it. People are drawn to warmth over heat.",
  "Sep 29": "Justice matters to you deeply. If something feels unfair, your warrior spirit is right to rise.",
  "Sep 30": "September ends with a surprising sense of peace. You're learning that stillness is not stagnation.",

  // ── October ──
  "Oct 1": "October brings depth. Your fire is ready to illuminate things hidden beneath the surface.",
  "Oct 2": "A relationship mirror reflects something you need to see about yourself. Be brave enough to look.",
  "Oct 3": "Your independence and your desire for partnership are not at war. They're dance partners.",
  "Oct 4": "Art, beauty, or music moves you profoundly today. Let it. Not everything needs to be conquered.",
  "Oct 5": "A negotiation or difficult conversation needs your courage and your tact. You have both.",
  "Oct 6": "Your fire warms the spaces you enter today. People gravitate toward you for reasons they can't explain.",
  "Oct 7": "Balance isn't a destination — it's a practice. Today, practice it in one small way.",
  "Oct 8": "Your natural bluntness benefits from a filter today. The message is right; season it with kindness.",
  "Oct 9": "A creative collaboration sparks something neither party could achieve alone. Synergy over solo today.",
  "Oct 10": "Your sense of justice burns hot. Use it constructively — advocate, don't attack.",
  "Oct 11": "Love or attraction energy surges. Whether new or long-standing, give it your undivided attention.",
  "Oct 12": "Your warrior archetype evolves today. The mature warrior knows when to fight and when to extend a hand.",
  "Oct 13": "An aesthetic choice — what you wear, how you arrange your space — lifts your energy today.",
  "Oct 14": "Partnership teaches you something solitude can't. Be a student of togetherness today.",
  "Oct 15": "Your fire meets the season's introspective energy. Look inward with the same courage you apply outward.",
  "Oct 16": "A decision needs making. Trust your first instinct — Aries' initial impulse is usually right.",
  "Oct 17": "Your protective nature combined with Libra season's grace makes you a gentle warrior today.",
  "Oct 18": "Creativity flows when you stop forcing and start playing. Lower the stakes and raise the fun.",
  "Oct 19": "As Libra season wanes, carry forward what it taught you about patience and partnership.",
  "Oct 20": "Your authenticity is a magnet. People trust your realness in a world full of performance.",
  "Oct 21": "Transformation energy intensifies. Something in your life is ready to shift — let it.",
  "Oct 22": "Scorpio season begins. Intensity meets intensity — you can handle depth like few others.",
  "Oct 23": "Your emotional courage is tested today. Go where others fear to look. You'll find gold there.",
  "Oct 24": "Passion and obsession are close cousins. Today, check which one is driving you.",
  "Oct 25": "Your fire illuminates shadowy corners today. Bring truth to places where it's been avoided.",
  "Oct 26": "Deep conversation feeds your soul today more than action does. Sit still and connect.",
  "Oct 27": "A financial or investment opportunity benefits from your bold instincts and research equally.",
  "Oct 28": "Jealousy or possessiveness may flare — in you or at you. Name it honestly and disarm it.",
  "Oct 29": "Your resilience is being quietly admired by someone going through their own battle. You're already helping.",
  "Oct 30": "The veil thins, and your intuition sharpens. Trust what you sense beyond the visible.",
  "Oct 31": "Your fearlessness shines on the darkest night. Step into mystery with the confidence of a warrior.",

  // ── November ──
  "Nov 1": "Depth over speed today. Something beneath the surface demands exploration — dive in.",
  "Nov 2": "Your fire meets transformative water energy. Emotional breakthroughs are possible if you stay present.",
  "Nov 3": "Power dynamics in a relationship become visible. Address them with your signature directness.",
  "Nov 4": "Your ability to be reborn after difficult experiences is your most underrated strength.",
  "Nov 5": "An investment — of time, money, or emotion — asks for commitment. Trust your gut and commit.",
  "Nov 6": "Vulnerability is the door to intimacy. Today, hands shaking, open it anyway.",
  "Nov 7": "Your fire-forged honesty cuts through Scorpio season's smokescreens. Be the truth-teller.",
  "Nov 8": "Physical intensity matches emotional intensity today. Work out the feelings through the body.",
  "Nov 9": "A secret or hidden truth comes to light. Your courage helps you handle it with grace.",
  "Nov 10": "Your willpower is unshakeable today. Whatever you commit to, you'll see through. Choose wisely.",
  "Nov 11": "Honor what has been. Your warrior spirit is equally brave in remembering and in charging forward.",
  "Nov 12": "Control and surrender are today's theme. Sometimes the strongest move is letting go.",
  "Nov 13": "Your instinct for self-preservation is important, but today, also preserve what you're building together.",
  "Nov 14": "Creative fire burns with unusual depth. What emerges from you now has emotional resonance others can feel.",
  "Nov 15": "Halfway through the month, your transformative journey this season becomes visible. Feel the growth.",
  "Nov 16": "Trust is earned slowly and lost quickly. Today, be someone worth trusting — in every small way.",
  "Nov 17": "Your fierce independence meets a call for interdependence. Both are strengths. Toggle between them wisely.",
  "Nov 18": "Healing is not linear. Some days you charge forward; some days you sit with what hurts. Both count.",
  "Nov 19": "Your raw energy gets refined today. Think diamond under pressure — you're becoming something precious.",
  "Nov 20": "An ending brings unexpected relief. Not everything that leaves is a loss.",
  "Nov 21": "Sagittarius season approaches. Your fire sign sibling brings expansion, optimism, and wide-open horizons.",
  "Nov 22": "Adventure calls with a megaphone. Your natural fire meets the archer's aim — focus your wanderlust.",
  "Nov 23": "Freedom, travel, and big ideas energize you. Think beyond your usual boundaries today.",
  "Nov 24": "Your optimism is genuine and hard-won. Share it — people need fire-sign hope right now.",
  "Nov 25": "Gratitude amplifies your fire. List what you're fiercely thankful for, and feel the energy surge.",
  "Nov 26": "A philosophical question captures your warrior mind. Not everything needs a physical solution — some battles are internal.",
  "Nov 27": "Your blunt humor makes people laugh and think today. Never underestimate your wit.",
  "Nov 28": "Physical adventure feeds your soul. A hike, a road trip, a new experience — seek it out.",
  "Nov 29": "Your vision for the future sharpens. Aim high — Aries doesn't settle, and neither should your dreams.",
  "Nov 30": "November ends with fire sign solidarity. You've gone deep and come back brighter.",

  // ── December ──
  "Dec 1": "December opens with expansive energy. Let your fire aim at the biggest vision you can imagine.",
  "Dec 2": "Travel or learning something new lights you up. Feed your restless mind today.",
  "Dec 3": "Your natural leadership gets a boost from Sagittarian optimism. Inspire with vision, not just action.",
  "Dec 4": "A philosophical conversation ignites a new passion. Your fire loves big, meaningful ideas.",
  "Dec 5": "Your body craves outdoor adventure. Honor it, even if it's just a long walk under winter sky.",
  "Dec 6": "Honesty and faith combine today. Say what you believe, believe what you say.",
  "Dec 7": "A project or goal enters its final stretch this year. Push with Aries intensity to cross the finish line.",
  "Dec 8": "Your fire-sign nature thrives in holiday energy. Be the one who brings warmth to every gathering.",
  "Dec 9": "A bold year-end decision solidifies something you've been building. Trust the momentum.",
  "Dec 10": "Your generosity peaks this season. Give from your fire — time, energy, presence, passion.",
  "Dec 11": "An old adventure calls your name again. Revisit it with wiser eyes and a just-as-bold heart.",
  "Dec 12": "Your competitive fire turns toward personal bests. What can you do better today than yesterday?",
  "Dec 13": "Joy is not a distraction from your mission — it IS the mission. Let yourself be ridiculously happy.",
  "Dec 14": "A friendship deepens through shared honesty. Your truthfulness is a rare and precious gift.",
  "Dec 15": "Your year-end review should celebrate how many times you got back up, not just the wins.",
  "Dec 16": "The fire within you today burns for others. Volunteer, help, give — it feeds your soul.",
  "Dec 17": "A party or celebration needs your spark. You're the one who makes gatherings unforgettable.",
  "Dec 18": "Your warrior energy finds peace in winter's stillness. Embrace the quiet fire burning inside.",
  "Dec 19": "Reflect on the battles you chose not to fight this year. That restraint is your greatest evolution.",
  "Dec 20": "Your fire sign heart beats stronger in community. Gather your people close.",
  "Dec 21": "Winter solstice. In the darkest moment, your fire is most needed. Be the light. You always have been.",
  "Dec 22": "Capricorn season grounds your fire into ambition. Dream big, plan practically.",
  "Dec 23": "Your year-end energy is intense and purposeful. Use it to set the stage for what's next.",
  "Dec 24": "Warmth is your gift tonight. Whether with many or few, your fire makes any gathering feel like home.",
  "Dec 25": "Today, let receiving be as brave as giving. Open your heart to the love being offered.",
  "Dec 26": "The quiet after the storm suits you more than you'd admit. Rest in the silence.",
  "Dec 27": "Your ambitions for the new year are already forming. Let them simmer — they'll ignite perfectly when ready.",
  "Dec 28": "Gratitude and fire combine: you're thankful for every battle that forged you. All of them.",
  "Dec 29": "Review your year with Aries honesty. What served you? What's done? Name it and release it.",
  "Dec 30": "Tomorrow the year ends. Today, acknowledge that your fire made the world warmer, brighter, and braver.",
  "Dec 31": "The year closes and you stand, as always, ready for what's next. Aries ends as they begin — on fire.",
};
