/** 365 daily quotes for Cancer — one for every day of the year. */
export const cancerDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, tender heart. Set intentions that honor both your ambition and your need for emotional safety.",
  "Jan 2": "Your intuition about what this year needs is already whispering. Trust the quiet voice, not the loud world.",
  "Jan 3": "A cozy morning ritual sets the tone for everything. Protect your morning — it protects you.",
  "Jan 4": "Your home is your power base. A small improvement there ripples into every area of your life.",
  "Jan 5": "Someone needs your nurturing today. But first — have you nurtured yourself?",
  "Jan 6": "The moon shifts and so do your moods. Don't judge the wave — ride it with compassion.",
  "Jan 7": "A family connection deepens through honest conversation. Lead with love, follow with truth.",
  "Jan 8": "Your protective shell isn't weakness — it's wisdom. Know when to open and when to retreat.",
  "Jan 9": "Financial security soothes your soul more than luxury does. Make one practical money move today.",
  "Jan 10": "Cooking is your meditation. Whatever you prepare today, stir in love — people can taste it.",
  "Jan 11": "The past holds lessons, not chains. Visit memories gently, then return to the present.",
  "Jan 12": "Your empathy is a superpower and a vulnerability. Today, use it with boundaries.",
  "Jan 13": "Home doesn't have to mean four walls. It can be a person, a feeling, a song. Find home today.",
  "Jan 14": "Your mood mirrors the moon you were born under. Track it — the patterns reveal your rhythm.",
  "Jan 15": "Midmonth calls for a check-in with your inner child. What do they need right now?",
  "Jan 16": "Water heals you — a bath, a swim, rain on your skin, or even a glass held mindfully. Hydrate your spirit.",
  "Jan 17": "Your fierce maternal energy applies to projects too. Protect what you're creating with gentle ferocity.",
  "Jan 18": "Emotional honesty with yourself precedes honesty with others. Journal today — let it pour out.",
  "Jan 19": "A nostalgic scent, song, or photo surfaces. Feel the tenderness, then set it down gently.",
  "Jan 20": "Your sensitivity to others' emotions is heightened. Shield yourself lovingly from energy that isn't yours.",
  "Jan 21": "Something growing quietly in your emotional world is about to bloom. Give it patience.",
  "Jan 22": "Your capacity for deep connection is rare and precious. Don't waste it on people who treat it casually.",
  "Jan 23": "Domestic peace is not a small thing — it's the foundation of everything. Protect it fiercely.",
  "Jan 24": "A memory from childhood holds a key to something you're navigating now. Look with soft eyes.",
  "Jan 25": "Your shell protects pearls of wisdom most never see. Today, show a trusted person one of those pearls.",
  "Jan 26": "Financial planning eases your anxiety better than any mantra. Build security brick by brick.",
  "Jan 27": "Seasonal foods, warm fabrics, and candlelight aren't indulgence — they're your emotional infrastructure.",
  "Jan 28": "Your lunar nature means some days glow and some are dark. Both are part of your cycle. Honor both.",
  "Jan 29": "An act of caretaking today fills you up rather than draining you. Give from overflow.",
  "Jan 30": "Home cooking tonight isn't optional — it's therapy. Make the comfort food your soul craves.",
  "Jan 31": "January ends with emotional clarity. You've honored your feelings, and they've honored you back.",

  // ── February ──
  "Feb 1": "February stirs your deepest longings for connection. Open your heart — but keep the key.",
  "Feb 2": "Your intuition about someone's feelings is correct today. Trust what you sense beneath their words.",
  "Feb 3": "A creative expression of emotion — painting, writing, cooking — helps you process what words can't.",
  "Feb 4": "Your home needs a love letter today. Clean a space, light a candle, arrange flowers. Tend your sanctuary.",
  "Feb 5": "Emotional boundaries aren't walls — they're filters. Let love in; keep toxicity out.",
  "Feb 6": "The moon's pull is especially strong today. Water-based activities soothe your restless tides.",
  "Feb 7": "A family member needs your understanding more than your advice. Just hold space today.",
  "Feb 8": "Your nurturing nature extends to yourself today. Be the parent your inner child needs right now.",
  "Feb 9": "A tender moment catches you off guard. Let the tears come if they want to. They're cleansing.",
  "Feb 10": "Your home is a healing center. Anyone who enters feels safer. That's your energy at work.",
  "Feb 11": "Sentimental keepsakes aren't clutter — they're your emotional museum. Curate, don't purge.",
  "Feb 12": "Your love language is caregiving. Today, lavish it on the person who receives it most gratefully — including yourself.",
  "Feb 13": "Pre-Valentine: your idea of romance is homemade, personal, and deeply felt. That's more valuable than any store-bought gesture.",
  "Feb 14": "Love flows from your core like a spring. Today, let it overflow. Give your full, unguarded heart.",
  "Feb 15": "Emotional hangover from deep feeling is real. Rest, hydrate, and be gentle with yourself today.",
  "Feb 16": "Your intuitive connection to the moon guides your energy today. Check the lunar phase and sync.",
  "Feb 17": "A recipe passed down through family carries more than flavor — it carries love across time. Cook it.",
  "Feb 18": "Your sensitivity is your art form. What you feel, others wish they could. That's a gift.",
  "Feb 19": "A protective instinct flares. Check if the threat is real or imagined. Sometimes your shell activates prematurely.",
  "Feb 20": "Emotional honesty in a relationship creates the safety you crave. Be brave enough to be real.",
  "Feb 21": "Your dream life is vivid tonight. Pay attention — your subconscious is sending messages.",
  "Feb 22": "Comfort isn't complacency. The safety you create is the launchpad for brave action.",
  "Feb 23": "A child, pet, or dependent reminds you what unconditional love looks like. Receive the lesson.",
  "Feb 24": "Your moods shift with invisible tides. Rather than fighting the current, learn to surf it.",
  "Feb 25": "Family dynamics that usually frustrate you reveal their deeper pattern today. Understanding brings peace.",
  "Feb 26": "A warm blanket, a good cry, and a cup of tea is sometimes the most radical act of self-care.",
  "Feb 27": "Your capacity to hold grief and joy simultaneously is uniquely Cancer. Both are present today. Hold them.",
  "Feb 28": "February taught you about the courage of vulnerability. Your soft heart is your strongest muscle.",
  "Feb 29": "Rare day, rare feeling. Name the emotion you've been circling around. Naming it gives you power.",

  // ── March ──
  "Mar 1": "Spring stirs your nesting instinct. Begin a home project that makes your space feel more alive.",
  "Mar 2": "Your emotional wisdom guides a decision that logic alone can't solve. Trust the feeling, not just the facts.",
  "Mar 3": "Water your own roots before watering everyone else's. You can't pour from an empty well.",
  "Mar 4": "Your sensitivity today picks up emotional frequencies others miss. Use this awareness compassionately.",
  "Mar 5": "A creative outlet saves you from emotional buildup. Write, draw, cook, or dance the feelings out.",
  "Mar 6": "Family-of-choice matters as much as family-of-origin. Today, honor the people you chose to be yours.",
  "Mar 7": "The moon wakes something restless in you tonight. Don't analyze it — just feel it.",
  "Mar 8": "Your maternal strength shows. Protecting others comes naturally, but today, protect your own time and energy too.",
  "Mar 9": "A sentimental gesture — writing a letter, framing a photo, revisiting a place — fills your heart.",
  "Mar 10": "Your home reflects your inner state. If it feels cluttered or chaotic, tend it — and watch your mood shift.",
  "Mar 11": "Emotional vulnerability in a safe relationship builds the intimacy you crave. Risk being seen.",
  "Mar 12": "Your crab nature knows: sometimes lateral movement gets you where head-on cannot. Approach sideways today.",
  "Mar 13": "A long bath or shower washes away more than dirt. Let water carry what no longer serves you.",
  "Mar 14": "Your love of tradition doesn't mean you're stuck in the past. It means you honor what endures.",
  "Mar 15": "Nourishing others is your joy, but today, be fiercely selfish about your own nourishment.",
  "Mar 16": "An emotional breakthrough whispers rather than shouts. Listen in the quiet moments today.",
  "Mar 17": "Your lucky streak comes through emotional authenticity, not strategy. Be real and watch doors open.",
  "Mar 18": "Your dream home isn't about square footage — it's about safety, warmth, and belonging. Define that today.",
  "Mar 19": "Spring is almost here and your interior world starts to thaw. Feelings frozen all winter begin to flow.",
  "Mar 20": "Spring equinox. Rebirth energy meets your nurturing nature. Plant emotional seeds and tend them daily.",
  "Mar 21": "Aries season lights a fire under your career and public life. Be brave in how the world sees you.",
  "Mar 22": "Your ambition stirs, and it surprises people who only see your soft side. You're as driven as anyone.",
  "Mar 23": "A career move fueled by emotional intelligence puts you ahead. Your empathy IS your professional edge.",
  "Mar 24": "Public recognition feels uncomfortable but earned. Accept the spotlight gracefully today.",
  "Mar 25": "Your private self and public self are both authentic. Today, let them meet in the middle.",
  "Mar 26": "Authority comes naturally when people feel safe around you. Lead through care today.",
  "Mar 27": "Your fear of rejection is real, but courage isn't the absence of fear — it's action despite it.",
  "Mar 28": "A professional relationship benefits from your emotional attunement. Read the room and respond.",
  "Mar 29": "Ambition and nurturing aren't opposites. Build your empire from a place of love.",
  "Mar 30": "Your public face today should match your private truth. Authenticity is your authority.",
  "Mar 31": "March ends with growth in how the world sees you. Your shell protects, but it doesn't hide.",

  // ── April ──
  "Apr 1": "Playfulness is allowed, even for the serious crab. Laugh at yourself today — it's healing.",
  "Apr 2": "Your emotional radar picks up shifts in your community today. You feel the collective mood.",
  "Apr 3": "A friendship deepens when you share something from your inner world. Trust arrives through openness.",
  "Apr 4": "Group dynamics reveal roles you naturally fill: nurturer, protector, quiet leader. Own it.",
  "Apr 5": "Your wish for the future is rooted in emotional values, not just material goals. Dream with your heart.",
  "Apr 6": "Social energy is higher than usual. Your warmth draws people toward you effortlessly.",
  "Apr 7": "A cause or community effort that aligns with your values deserves your energy today.",
  "Apr 8": "Your friends are your chosen family. Today, show them the same devotion you give blood relatives.",
  "Apr 9": "An innovative idea about home, family, or emotional wellness surfaces. Trust it — it's ahead of its time.",
  "Apr 10": "Your protective instincts extend to your community today. Advocate for what's right.",
  "Apr 11": "Spring blooms mirror your inner softening. What was closed begins to open safely.",
  "Apr 12": "Group settings don't drain you when you're with the right people. Curate your tribe carefully.",
  "Apr 13": "A dream or vision for the future crystallizes through emotional clarity, not analysis.",
  "Apr 14": "Your humanitarian side shows beautifully. Caring for one person at a time IS changing the world.",
  "Apr 15": "Financial planning for your family or household unit comes naturally today. Secure the foundation.",
  "Apr 16": "Your intuition about a group dynamic prevents unnecessary conflict. Trust your read on people.",
  "Apr 17": "The moon tonight carries a message just for you. Sit with it before sleep.",
  "Apr 18": "Your need for solitude battles your need for connection today. Honor both — alternate throughout the day.",
  "Apr 19": "Taurus season approaches. Earth energy grounds your water nature beautifully.",
  "Apr 20": "Your emotional sensitivity meets grounded, sensual energy. A perfect day for comfort and beauty.",
  "Apr 21": "Home nesting hits peak satisfaction. Cook something extraordinary and enjoy every bite.",
  "Apr 22": "Earth Day resonates with your primal connection to nature. Get your hands in soil today.",
  "Apr 23": "Your love of comfort extends to creating comfort for others. Be the host, the cook, the safe harbor.",
  "Apr 24": "Financial security continues to soothe your deepest anxieties. Make another practical move.",
  "Apr 25": "Sensory pleasure heals your emotional body. Music, fragrance, taste — indulge mindfully.",
  "Apr 26": "Your patience with someone's growth process is itself a form of love. Keep waiting kindly.",
  "Apr 27": "A material possession triggers an emotional memory. Objects carry energy for you — honor that.",
  "Apr 28": "Your garden — real or metaphorical — shows signs of new growth. Something you nurtured is thriving.",
  "Apr 29": "Evening cooking with good music is not a small thing. It's your version of spiritual practice.",
  "Apr 30": "April ends with emotional richness. You've given generously and received more than you expected.",

  // ── May ──
  "May 1": "May brings sensory abundance that feeds your water soul. Beauty, food, and love are your medicine.",
  "May 2": "Your body holds emotional truth. A tight chest means unexpressed feeling. A warm belly means safety. Listen.",
  "May 3": "A nurturing gesture from you transforms someone's difficult day. Never underestimate your kindness.",
  "May 4": "Financial grounding continues. You're building the material safety that lets your heart be free.",
  "May 5": "Your home needs something alive — a plant, a pet, a blooming bouquet. Life energy heals your space.",
  "May 6": "Nostalgia visits with a gentle hand today. Let it remind you how far you've come.",
  "May 7": "An evening spent cooking a cherished recipe connects you to love across generations.",
  "May 8": "Your emotional reserves are deep today. Draw from them for a friend who's running dry.",
  "May 9": "Your body craves grounding foods — root vegetables, warm soups, nourishing staples. Feed it well.",
  "May 10": "Mothering energy (regardless of gender) flows through you naturally. A nurturing act fulfills you deeply.",
  "May 11": "Family traditions aren't chains — they're bridges between past love and future joy. Honor one today.",
  "May 12": "Your protective nature creates sanctuary wherever you go. People feel safe in your energy.",
  "May 13": "A home improvement brings unexpected emotional relief. Your outer space mirrors your inner state.",
  "May 14": "Love expressed through acts of service speaks louder than words. Fold someone's laundry with devotion.",
  "May 15": "Your emotional intelligence helps navigate a complex family dynamic. You see what others can't.",
  "May 16": "Water energy intensifies. Swim, bathe, walk by a river — your element restores you.",
  "May 17": "A sentimental object holds more value than its price tag. Keep what feels sacred.",
  "May 18": "Your fear of abandonment surfaces. Sit with it. It's old, it's familiar, and it doesn't control you anymore.",
  "May 19": "Evening candlelight and quiet music aren't luxury — they're your emotional oxygen. Breathe deeply.",
  "May 20": "A homemade gift from you carries more love than anything money could buy.",
  "May 21": "Gemini season begins. Mental agility helps you articulate what you usually only feel.",
  "May 22": "Your emotional depth meets communicative energy. Express what's in your heart with new clarity.",
  "May 23": "A conversation about feelings goes better than expected. Words capture what sighs couldn't.",
  "May 24": "Your nurturing nature finds verbal expression. A compliment, a poem, a love note — write it.",
  "May 25": "Social energy pulls you gently outward. Short visits or calls with close friends recharge you.",
  "May 26": "Your empathetic listening skills make you the friend everyone confides in. Protect your energy while giving.",
  "May 27": "Learning about emotional intelligence, attachment styles, or psychology feeds your soul today.",
  "May 28": "A sibling or neighborhood connection brings unexpected comfort. Community is family too.",
  "May 29": "Your dream journal has been trying to tell you something. Read back through recent entries.",
  "May 30": "Movement with purpose — walking to a destination, dancing in the kitchen — lifts your water spirits.",
  "May 31": "May ends with emotional articulation you didn't have before. You're learning to river into words.",

  // ── June ──
  "Jun 1": "June lightens your emotional intensity. Let the breeze carry some weight off your shoulders.",
  "Jun 2": "Your verbal expression of love deepens. Saying how you feel becomes less scary and more natural.",
  "Jun 3": "An idea about home, family, or emotional wellness forms clearly in your mind. Write it down.",
  "Jun 4": "Your curiosity about human nature is rewarded with an insight that changes how you see someone.",
  "Jun 5": "Short trips or local explorations break your routine and refresh your emotional palate.",
  "Jun 6": "A conversation with a sibling or close friend reveals a shared emotional pattern. Healing together is powerful.",
  "Jun 7": "Your hands create nourishment today — food, art, or simply arranging your space with love.",
  "Jun 8": "Pre-season energy builds. Your sign's season is approaching, and you can feel it in your tides.",
  "Jun 9": "Gentle communication repairs a rift you've been carrying silently. Some things need to be said.",
  "Jun 10": "Your heart and mind align today. Emotion and logic point in the same direction. Move.",
  "Jun 11": "A book or article about emotional health gives you vocabulary for what you've always felt.",
  "Jun 12": "Your evening routine is sacred. Bath, tea, gratitude — the ritual holds you together.",
  "Jun 13": "Anticipation builds as your season draws near. The world is about to feel you at full power.",
  "Jun 14": "Your sensitivity to lunar shifts is heightened. Check tonight's moon — it mirrors your mood.",
  "Jun 15": "Halfway through the year, your emotional growth is remarkable. You've felt deeply and survived it all.",
  "Jun 16": "A home-cooked feast shared with loved ones is your temple, your offering, your art. Create one.",
  "Jun 17": "Your fierce protectiveness isn't a flaw — it's love in warrior clothing. Direct it wisely.",
  "Jun 18": "The pull toward water grows. Ocean, river, rain, or bathtub — immerse yourself and reset.",
  "Jun 19": "Your season is almost here. Feel the moon calling your name. You're about to shine.",
  "Jun 20": "Summer solstice eve. The longest light prepares to cradle your season. You are ready.",
  "Jun 21": "Summer solstice. The light peaks and then begins to turn toward your domain. Everything shifts for you now.",
  "Jun 22": "Happy Cancer season! Your cosmic birthday month begins. The universe aligns to support your deepest needs.",
  "Jun 23": "Your energy radiates during your season. People feel drawn to your warmth without knowing why.",
  "Jun 24": "Emotional truth-telling comes easier now. Your season gives you permission to be fully, unapologetically you.",
  "Jun 25": "Home transformations during your season carry extra magic. Rearrange, cleanse, beautify your space.",
  "Jun 26": "Your nurturing instincts peak. But remember: the best caretakers also accept care. Let someone tend you.",
  "Jun 27": "A family gathering during your season feels more meaningful. These are your people. Love them loudly.",
  "Jun 28": "Your intuition is laser-focused during your season. Trust every hunch, every gut feeling.",
  "Jun 29": "The moon tonight is your personal ally. Speak your wishes to it and trust them to the tides.",
  "Jun 30": "June ends with Cancer season in full flow. You are the ocean — deep, powerful, and endlessly nurturing.",

  // ── July ──
  "Jul 1": "July is your month fully. Own every emotional peak and valley — they're all part of your power.",
  "Jul 2": "Your birthday season amplifies everything: love, creativity, intuition, and emotional depth. Receive it.",
  "Jul 3": "Home celebrations during your season mean more than lavish parties. Intimate gatherings fill your cup.",
  "Jul 4": "Freedom for you means emotional safety — the liberty to feel without judgment. Claim it today.",
  "Jul 5": "Your season makes you magnetic. Opportunities that align with your emotional truth arrive now.",
  "Jul 6": "Cooking during your birthday month is alchemy. Whatever you create in the kitchen carries extra love.",
  "Jul 7": "Your emotional memory is a treasure chest. Pick one golden memory and relive it today.",
  "Jul 8": "The moon guides your decisions more accurately than any spreadsheet. Consult your feelings first.",
  "Jul 9": "Your vulnerability during your season is your greatest strength. Let people see the real you.",
  "Jul 10": "A birthday wish made with genuine heart carries unusual power this week. Dream specifically.",
  "Jul 11": "Nurture your own dreams as devotedly as you nurture others. Your wishes matter too.",
  "Jul 12": "Family photos, heirlooms, or stories passed down carry healing power. Engage with your lineage today.",
  "Jul 13": "Your emotional radar operates at full capacity. You feel everything — and that's exactly the point.",
  "Jul 14": "A water-based activity — swimming, surfing, soaking — recharges your zodiac battery completely.",
  "Jul 15": "Mid-July is peak Cancer energy. You are running on cosmic support. Use it fully.",
  "Jul 16": "A creative project birthed during your season has extra emotional resonance. Share it.",
  "Jul 17": "Your home during Cancer season should feel like a sanctuary. Add something that deepens the comfort.",
  "Jul 18": "Financial moves made during your season tend to reflect your truest values. Invest in what matters.",
  "Jul 19": "Your season's final days concentrate your energy. What emotional intention do you want to set?",
  "Jul 20": "Evening rituals carry extra potency now. Bath, journal, moon gazing — your trifecta of renewal.",
  "Jul 21": "The protective shell that sometimes isolates you also shields your most sacred gifts. Honor it.",
  "Jul 22": "Your season closes with the fullness of a high tide. Let it peak, then prepare for the ebb with grace.",
  "Jul 23": "Leo season starts. Fire meets your water. Let the warmth draw you out of your shell.",
  "Jul 24": "Creative self-expression calls. Your emotional depth gives art unusual authenticity — create today.",
  "Jul 25": "Your inner child wants to play in the spotlight. Let them — safely and joyfully.",
  "Jul 26": "Romance or creative passion surges. Express love boldly — it doesn't have to be quiet to be real.",
  "Jul 27": "Your nurturer role shifts toward playfulness. Parent your inner child with fun today.",
  "Jul 28": "A heart-centered project or hobby gets Leo fire behind it. Create with courage.",
  "Jul 29": "Your emotional generosity is your gift to the world. Give from the heart today.",
  "Jul 30": "Dramatic self-expression isn't your usual style, but today, let feelings be big and bold.",
  "Jul 31": "July ends. Your season may be over, but your emotional power lasts all year. Never forget that.",

  // ── August ──
  "Aug 1": "August's boldness activates your hidden ambition. What would you dare if you felt completely safe?",
  "Aug 2": "Creative fire meets emotional depth. Your art, cooking, or projects carry unusual heart today.",
  "Aug 3": "Your nurturing shows up as creative mentoring today. Encourage someone's fledgling courage.",
  "Aug 4": "A playful approach to a usually serious topic lightens the emotional weight you carry.",
  "Aug 5": "Joy and vulnerability are cousins. Today, let delight crack your shell — it's meant to.",
  "Aug 6": "Your emotional intelligence makes you a brilliant creative collaborator. Share an idea enthusiastically.",
  "Aug 7": "Romance during Leo season asks for grander gestures than your usual subtle love notes. Be bold.",
  "Aug 8": "A child, pet, or playful friend reminds you that love doesn't always need to be serious to be deep.",
  "Aug 9": "Your home becomes a creative studio today. Make art in whatever medium feels right. Mess is welcome.",
  "Aug 10": "Your heart is bigger than your fear today. Lead with the big one. The fear will shrink.",
  "Aug 11": "A creative risk pays off emotionally. The thing you almost didn't share? It resonated deeply.",
  "Aug 12": "Sunlight and laughter are genuinely medicinal for you. Get both today.",
  "Aug 13": "Your devotion is your art form. How you love, cook, create, and care — it's all masterwork.",
  "Aug 14": "Summer's peak energy fills your shell with light. Let it illuminate even the hidden corners.",
  "Aug 15": "Mid-August invites you to rest within abundance. You've given so much — now sit in the harvest.",
  "Aug 16": "A family member surprises you with insight into your emotional patterns. Listen without defending.",
  "Aug 17": "Your protective instincts serve you well today. A situation needed exactly your careful attention.",
  "Aug 18": "Evening comfort — a loved one, a great meal, a clear night — is the sum of a life well-lived.",
  "Aug 19": "Your emotional reserves prepare for the season's transition. Rest and replenish now.",
  "Aug 20": "The shift toward fall whispers to your water nature. Change is coming — and you'll navigate it beautifully.",
  "Aug 21": "Summer memories crystallize into emotional treasures. Which ones will you carry forward?",
  "Aug 22": "The transition to earth energy steadies your tides. Practical self-care anchors you.",
  "Aug 23": "Virgo season begins. Practical health and daily routines serve your emotional stability. Embrace structure.",
  "Aug 24": "Your meal prep, cleaning rituals, and health habits aren't boring — they're your emotional scaffolding.",
  "Aug 25": "A health-focused adjustment improves your emotional weather. Body and heart are deeply linked for you.",
  "Aug 26": "Your attention to domestic detail creates the background of safety others take for granted.",
  "Aug 27": "Organizing your home or workspace eases an anxiety you didn't realize was environmental.",
  "Aug 28": "A daily wellness practice — gratitude journaling, a morning walk, herbal tea — becomes non-negotiable.",
  "Aug 29": "Your service to others is genuine but should never drain you completely. Check the balance.",
  "Aug 30": "Practical love — making the appointment, buying the groceries, cleaning the kitchen — is love nonetheless.",
  "Aug 31": "August ends with practical and emotional growth woven together. You've been both soft and strong.",

  // ── September ──
  "Sep 1": "September's organized energy harnesses your emotional power into productive channels.",
  "Sep 2": "Your health and wellness routine is the container that holds your emotional well-being. Tend it.",
  "Sep 3": "A home cleanse — physical, emotional, or energetic — clears space for what's coming next.",
  "Sep 4": "Your nurturing nature applies to daily acts: packing lunches, watering plants, checking in on people.",
  "Sep 5": "A detail-oriented task feels surprisingly satisfying today. Your care shows in every line.",
  "Sep 6": "Your gut — both intuitive and physical — tells you what your body needs. Feed it accordingly.",
  "Sep 7": "Service to family or household is not drudgery; it's your love language made tangible. Own it.",
  "Sep 8": "A health concern eases when you address it practically and compassionately. Take care of yourself.",
  "Sep 9": "Your daily rituals create emotional rhythm. The predictability isn't boring — it's stabilizing.",
  "Sep 10": "Meal planning and cooking with intention is your form of spell-casting. Put love in the recipe.",
  "Sep 11": "Your sensitivity holds collective grief with unusual grace today. Honor what you feel.",
  "Sep 12": "A pet or animal brings unexpected emotional healing. Their unconditional presence mirrors what you offer others.",
  "Sep 13": "Organization brings you peace when it serves beauty. A well-organized kitchen or closet is your meditation.",
  "Sep 14": "Your emotional health check-in: are you giving more than you're receiving? Balance the scales.",
  "Sep 15": "Practical self-care — clean sheets, a healthy meal, an early night — says 'I love myself' louder than fancy rituals.",
  "Sep 16": "Your attention to someone's needs makes them feel truly seen. That gift is invaluable.",
  "Sep 17": "A routine change — a new walking route, a different breakfast — refreshes your emotional landscape.",
  "Sep 18": "Your home should nourish all five senses. Today, improve one sensory experience in your space.",
  "Sep 19": "Virgo season has refined your caregiving. You're more effective and sustainable in how you love.",
  "Sep 20": "A practical accomplishment brings emotional satisfaction that ambition alone never could.",
  "Sep 21": "Autumn arrives, and your water nature responds to the cooling. Wrap yourself in warmth and routine.",
  "Sep 22": "Libra season begins. Partnership and harmony activate your relationship-oriented heart.",
  "Sep 23": "Emotional balance in relationships requires honest communication. Say what you need today.",
  "Sep 24": "Your home becomes a place of partnership harmony. Create beauty together with someone you love.",
  "Sep 25": "Fairness in emotional exchange matters. Are your relationships equal in care? Assess gently.",
  "Sep 26": "Beauty soothes your soul today. Art, music, nature, or a beautifully set table — surround yourself with it.",
  "Sep 27": "Your diplomatic side emerges. Smoothing conflict feels natural when you lead with empathy.",
  "Sep 28": "A loved one's appreciation for your consistency touches you deeply today. You ARE appreciated.",
  "Sep 29": "Balance between giving and receiving is this season's lesson. Learn it — it transforms everything.",
  "Sep 30": "September taught you that practical care IS emotional depth. They were never separate.",

  // ── October ──
  "Oct 1": "October deepens your emotional currents. The surface calms while the depths stir with transformation.",
  "Oct 2": "Your relationships enter a more honest phase. Truth, spoken gently, heals what pretense couldn't.",
  "Oct 3": "A beautiful domestic scene — candlelit dinner, fresh flowers, curated music — restores your entire being.",
  "Oct 4": "Your aesthetic of comfort and warmth becomes your signature. People associate peace with your presence.",
  "Oct 5": "A partnership grows stronger through shared vulnerability. You go first — your courage invites theirs.",
  "Oct 6": "Your ability to create harmony at home is a genuine superpower. Exercise it today.",
  "Oct 7": "Balance in caretaking: nurture others, then nurture yourself with equal devotion. Both matter.",
  "Oct 8": "Your empathy helps mend a broken connection. Your compassionate approach works miracles.",
  "Oct 9": "A cozy evening — fire, blankets, tea, and someone you love — heals more than any therapy session.",
  "Oct 10": "Your sensitivity to seasons means autumn genuinely shifts your emotional landscape. Go with the change.",
  "Oct 11": "A home preservation or family heritage project fills you with purposeful joy.",
  "Oct 12": "Your love of tradition weaves past and present beautifully. Honor an ancestor today.",
  "Oct 13": "Comfort food season is YOUR season within a season. Cook with love and share with devotion.",
  "Oct 14": "A long-held emotional pattern is ready to release. Let it go like a leaf releasing from its branch.",
  "Oct 15": "Your emotional courage builds. What once felt too big to face now feels navigable. Growth.",
  "Oct 16": "A sentimental gesture from you — a photo, a handwritten note, a recipe card — becomes a treasured gift.",
  "Oct 17": "Your home during autumn is a masterpiece of warmth. Pumpkins, candles, blankets — curate it lovingly.",
  "Oct 18": "Your partnership skills strengthen through practice and patience. Love is a craft, and you're a master.",
  "Oct 19": "Evening gratitude practice deepens your emotional well-being. Name three things you're grateful for right now.",
  "Oct 20": "Your water nature flows toward depth as Scorpio season approaches. Prepare for emotional intensity.",
  "Oct 21": "A family recipe cooked on a cool evening connects you to love that spans generations.",
  "Oct 22": "Scorpio season begins. Deep emotional waters are your natural habitat. Dive in fearlessly.",
  "Oct 23": "Transformation energy feels familiar to you. Your emotional world has always been deep — now it gets powerful.",
  "Oct 24": "An emotional truth surfaces that you've been avoiding. Face it, fellow water sign. You can handle this.",
  "Oct 25": "Your intuition operates at profound depth now. Trust every feeling, every hunch, every dream.",
  "Oct 26": "Intimacy deepens when you share the parts of yourself you usually hide. Someone sees you fully today.",
  "Oct 27": "Financial or shared resource discussions benefit from your emotional intelligence. Feel the right decision.",
  "Oct 28": "Your capacity to sit with difficult emotions without fleeing is rare and powerful. Use it today.",
  "Oct 29": "The thin veil between worlds doesn't frighten you — you've always felt it. Tonight, honor the unseen.",
  "Oct 30": "Emotional transformation is not one big moment — it's many small courageous choices. You're making them.",
  "Oct 31": "Your water nature senses the spirit world with unusual clarity tonight. Light a candle for someone you miss.",

  // ── November ──
  "Nov 1": "November speaks your emotional language fluently. Allow depth without drowning. You know how.",
  "Nov 2": "Honor the departed through memory, food, and love. Your connection to ancestry is powerful.",
  "Nov 3": "An emotional purge — tears, writing, releasing — creates space for new growth. Let it out.",
  "Nov 4": "Shared resources, joint finances, or emotional investments ask for your attention and wisdom.",
  "Nov 5": "Your trust, once given, runs as deep as the ocean. Give it today to someone who's earned it.",
  "Nov 6": "Vulnerability with a trusted person creates intimacy that surface-level relating never could.",
  "Nov 7": "Your emotional resilience surprises even you. After everything, you're still here, still loving. That's power.",
  "Nov 8": "A family or domestic matter requires your brave emotional honesty. Speak from your heart.",
  "Nov 9": "Your dreams carry messages from your deepest self. Write them down before they dissolve.",
  "Nov 10": "A transformation in how you see yourself ripples into every relationship. Love yourself differently today.",
  "Nov 11": "Remember with tenderness. Your ability to hold grief and gratitude simultaneously is uniquely Cancer.",
  "Nov 12": "Financial security built through emotional wisdom — knowing when to hold and when to release.",
  "Nov 13": "Your home during Scorpio season becomes a cocoon. What emerges from it will have wings.",
  "Nov 14": "Emotional boundaries you set now protect future peace. Be firm where tenderness has been exploited.",
  "Nov 15": "Halfway through November, your transformation is visible. You've shed something heavy. Feel the lightness.",
  "Nov 16": "Your capacity for emotional held space is legendary. Hold space for yourself today too.",
  "Nov 17": "A secret shared with you is sacred. Your trustworthiness is one of your greatest gifts.",
  "Nov 18": "Your water nature meets fire season soon. Prepare for expansion by making sure your foundation is solid.",
  "Nov 19": "An emotional conversation reaches resolution because of your willingness to sit with discomfort.",
  "Nov 20": "Release the old to make room for the new. Your shell can be outgrown — and that's beautiful.",
  "Nov 21": "Sagittarius season begins. Expansion, adventure, and philosophy broaden your emotional world.",
  "Nov 22": "Travel or new experiences challenge your comfort zone — but growth lives just beyond it.",
  "Nov 23": "Gratitude for your home, your family, and the love you've built flows naturally today.",
  "Nov 24": "Your kitchen during the holidays is the heart of every gathering. You orchestrate love through flavor.",
  "Nov 25": "Traditional recipes carry ancestral love. Cook them with reverence and share them with joy.",
  "Nov 26": "Your nurturing nature gets philosophical today. Why do you care so deeply? Because that's what love is.",
  "Nov 27": "Adventure doesn't require leaving home. A new recipe, a foreign film, a different perspective — explore.",
  "Nov 28": "Your emotional wisdom meets Sagittarius optimism. Hope is not naive when it's rooted in experience.",
  "Nov 29": "A bigger vision for your life includes emotional freedom alongside material security. Dream expandedly.",
  "Nov 30": "November ends transformed and tender. You've gone deep and come back renewed.",

  // ── December ──
  "Dec 1": "December's holiday energy meets your nesting instincts perfectly. Decorate, bake, and gather.",
  "Dec 2": "Your holiday traditions carry the weight of love. Begin them early — the anticipation is part of the magic.",
  "Dec 3": "A philosophical conversation about the meaning of home deepens your understanding of what matters.",
  "Dec 4": "Your gifts are always personal, always thoughtful. You remember what people mentioned months ago.",
  "Dec 5": "Winter's darkness doesn't depress you — it cocoons you. The quiet suits your reflective nature.",
  "Dec 6": "Your kitchen fills with holiday aromas that heal everyone who enters. Cook today as an act of love.",
  "Dec 7": "Family dynamics during holidays are complex. Your emotional intelligence navigates them with grace.",
  "Dec 8": "A handmade or sentimental gift from you carries more love than the most expensive alternative.",
  "Dec 9": "Your year-end reflection goes deep. What did you feel this year? What grew? What healed?",
  "Dec 10": "Holiday decorating is your art form. Every ornament has a memory, every light has a wish.",
  "Dec 11": "Your home during December is the destination everyone wants to visit. That's your magic.",
  "Dec 12": "Rest and reflection pair perfectly today. Curl up, look back, and feel proud of your journey.",
  "Dec 13": "A carol, a hymn, or a seasonal song moves you to tears today. Let it. Music speaks to your soul.",
  "Dec 14": "Your emotional generosity during the holidays is boundless. Just remember to fill your own cup too.",
  "Dec 15": "The year's emotional highlight reel includes more courage than you realized. You felt everything and grew.",
  "Dec 16": "A quiet evening at home during the holiday rush is your sanctuary. Protect it.",
  "Dec 17": "Your memory for traditions — who sat where, what was served, the special ornament — keeps love alive.",
  "Dec 18": "The deepening winter matches your inward season. Hibernate a little. The world can wait.",
  "Dec 19": "Family love isn't always easy, but it's always worth protecting. Choose compassion tonight.",
  "Dec 20": "Your year of emotional growth has been remarkable. Gentler, braver, and more authentically you.",
  "Dec 21": "Winter solstice. The darkest night cradles your water nature gently. Light a candle and feel held.",
  "Dec 22": "Capricorn season begins. Ambition meets emotion — you're ready to build on everything you've felt this year.",
  "Dec 23": "Your pre-holiday preparations are love in action. Every detail you tend is a prayer for belonging.",
  "Dec 24": "Tonight, your home glows with the accumulated love of every person you've ever nurtured. Feel it.",
  "Dec 25": "Today, receive. You give so much all year. Let love flow IN today. Open your heart, your arms, your shell.",
  "Dec 26": "Post-holiday quiet is your favorite. Leftovers, pajamas, and the people who feel like home.",
  "Dec 27": "Your emotional year-end is rich with feeling. Journal it — next year's you will want to remember.",
  "Dec 28": "A New Year intention forms around emotional freedom: less people-pleasing, more authentic expression.",
  "Dec 29": "Your home, your family, and your heart are the three things you built this year. All three are thriving.",
  "Dec 30": "Tomorrow the year ends. Tonight, hold what you love and whisper your gratitude to the moon.",
  "Dec 31": "The year closes with you standing in the fullness of your feelings. Tender, brave, and deeply alive. Happy new year, Cancer.",
};
