/** 365 daily quotes for Capricorn — one for every day of the year. */
export const capricornDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "YOUR season is in full force. Set intentional, strategic goals that honor your ambition and your wisdom.",
  "Jan 2": "Saturn's discipline fuels your new year. No one builds like you, Capricorn. Blueprint the year.",
  "Jan 3": "A morning routine built on structure and purpose sets you up for long-term dominance.",
  "Jan 4": "Your living space should reflect your achievements, your aspirations, and your impeccable taste.",
  "Jan 5": "Someone respects your steadfast nature today. Your reliability is a rare and precious gift.",
  "Jan 6": "Saturn rewards patience. The compound interest of your daily effort is about to pay dividends.",
  "Jan 7": "A quiet ambition burns within you, hotter than anyone suspects beneath your composed exterior.",
  "Jan 8": "Your reserved nature isn't coldness — it's selective investment. You spend energy wisely.",
  "Jan 9": "Financial mastery is your birthright. One disciplined decision today builds long-term wealth.",
  "Jan 10": "Your leadership instinct shows through results, not speeches. Let your work speak today.",
  "Jan 11": "Long-term thinking is your superpower. While others rush, you build foundations that endure.",
  "Jan 12": "Your strategic mind already sees several moves ahead. Trust your long game today.",
  "Jan 13": "Home is your fortress. Make it a place of dignity, comfort, and quiet achievement.",
  "Jan 14": "Your cardinal earth nature means you initiate lasting structures. Start building something permanent.",
  "Jan 15": "Midmonth check-in: are your goals ambitious enough? You're capable of more than you think.",
  "Jan 16": "Winter is your power season. The cold doesn't slow you — it sharpens your focus.",
  "Jan 17": "A project benefits from your meticulous planning. Excellence is your minimum standard.",
  "Jan 18": "Self-improvement through discipline, mastery, and incremental progress is your lifelong path.",
  "Jan 19": "Your dry humor surfaces at the perfect moment. Wit is intelligence enjoying itself.",
  "Jan 20": "The final days of your season concentrate your power. Achieve something meaningful before Aquarius arrives.",
  "Jan 21": "Aquarius season approaches. Innovation meets your structure — evolution, not revolution.",
  "Jan 22": "Your birthday season concludes with a legacy: foundations laid that will support you all year.",
  "Jan 23": "The meaningful work of your life combines mastery with purpose. Both are non-negotiable.",
  "Jan 24": "A childhood lesson about perseverance still drives you. That early discipline shaped a mountain.",
  "Jan 25": "Your quiet determination inspires someone who watches how you work without complaining.",
  "Jan 26": "Financial planning for the year ahead comes naturally. You think in decades, not impulses.",
  "Jan 27": "Classic literature, enduring art, and timeless music feed your old-soul appreciation.",
  "Jan 28": "Your cardinal earth nature means you don't just endure — you build empires on solid ground.",
  "Jan 29": "An act of quiet generosity — helping without fanfare, supporting without spotlight — fulfills you.",
  "Jan 30": "An evening of quality solitude with a worthy book or project recharges your ambitious spirit.",
  "Jan 31": "January ends in your powerful wake. The foundations you've laid this month will hold all year.",

  // ── February ──
  "Feb 1": "February asks your structured nature to make room for innovation alongside tradition.",
  "Feb 2": "Your strategic insight today solves a problem that impulsive thinking couldn't reach. Trust your patience.",
  "Feb 3": "A creative expression of your ambition — plans, designs, strategies — impresses someone in authority.",
  "Feb 4": "Your space needs an element of timeless quality: leather, wood, stone, or something built to last.",
  "Feb 5": "Emotional expression doesn't come as naturally as professional achievement. Practice vulnerability.",
  "Feb 6": "Your earth sign nature craves tangible progress. Check one major item off the list today.",
  "Feb 7": "Someone needs your grounded perspective. Your stability is genuinely calming in chaos.",
  "Feb 8": "Your inner leader sometimes overshadows your collaborator. Today, support from behind the scenes.",
  "Feb 9": "Ambition fueled by genuine purpose creates work that outlasts any individual career move.",
  "Feb 10": "Your social selectivity means your friendships are few but deep. Honor them intentionally.",
  "Feb 11": "Quality possessions maintained over time aren't materialism — they're your autobiography in objects.",
  "Feb 12": "Your love language is reliability — showing up consistently, supporting steadfastly, building together.",
  "Feb 13": "Pre-Valentine: your idea of romance involves commitment, ambition shared, and trust built over time.",
  "Feb 14": "Love for Capricorn is a long-term investment. Today, show your partner the returns.",
  "Feb 15": "After Valentine's intensity, your practical spirit needs productive solitude. Work on something meaningful.",
  "Feb 16": "Your connection to Saturn teaches discipline as devotion. Structure IS your love language.",
  "Feb 17": "A quality home-cooked meal, perfectly executed, satisfies your need for mastery in every domain.",
  "Feb 18": "Your strategic perspective is your gift. What you see from the summit guides everyone below.",
  "Feb 19": "Emotional walls you built for protection may now block the intimacy you deserve. Lower one brick.",
  "Feb 20": "Your disciplined exterior hides a deeply sensitive interior. Acknowledge both sides today.",
  "Feb 21": "Your ambitions carry you to places you've planned for years. Some success is right on schedule.",
  "Feb 22": "Confidence rooted in competence — in proven ability and earned authority — is unshakable.",
  "Feb 23": "A trusted colleague or mentor reminds you that shared ambition multiplied by loyalty is unstoppable.",
  "Feb 24": "Your moods are steady and deep — a slow tide, not a crashing wave. Honor the rhythm.",
  "Feb 25": "Your cardinal nature initiates even when others hesitate. Lead with quiet authority today.",
  "Feb 26": "Professional attire that reflects your authority and taste communicates who you are before you speak.",
  "Feb 27": "Your ability to find purpose in difficulty AND success is uniquely Capricornian. Both teach you.",
  "Feb 28": "February taught you that the most enduring structures are built with both ambition and heart.",
  "Feb 29": "Rare day, rare opportunity. Do something that breaks your own rules. Prove your flexibility.",

  // ── March ──
  "Mar 1": "Spring stirs something beneath your disciplined surface. Even mountains feel the thaw.",
  "Mar 2": "Your strategic wisdom guides a decision that impulsive thinking couldn't solve. Trust your patience.",
  "Mar 3": "Rest before the next major push. Even the most determined climber camps before the summit.",
  "Mar 4": "Your practical awareness today reveals an overlooked efficiency. Optimization is your art.",
  "Mar 5": "A professional milestone showcases your consistent effort. Others see your years of work now.",
  "Mar 6": "Your mentors, role models, and worthy rivals deserve acknowledgment today.",
  "Mar 7": "Saturn steadies your evening contemplation. Reflect on the plan before executing the next phase.",
  "Mar 8": "True leadership means building others up, not standing on them. Elevate your team.",
  "Mar 9": "A handwritten note to a professional connection or mentor carries weight that emails can't match.",
  "Mar 10": "Your home should feel like a reward: comfortable, elegant, and worthy of all you've earned.",
  "Mar 11": "Emotional vulnerability in relationships is the one discipline you sometimes skip. Practice it.",
  "Mar 12": "Your cardinal nature finds new strategies when old approaches plateau. Adapt and climb differently.",
  "Mar 13": "Quality time — meaningful, undistracted, fully present — is the luxury your relationships crave.",
  "Mar 14": "Your restraint is powerful. Not every thought needs to be spoken, not every reaction expressed.",
  "Mar 15": "Fueling your body for sustained performance is practical investment. Eat for endurance.",
  "Mar 16": "A strategic detour today positions you better for the long game. Think several moves ahead.",
  "Mar 17": "Your good fortune is earned, not random. Luck is preparation meeting opportunity.",
  "Mar 18": "Your ideal home includes a study, quality furnishings, and an atmosphere of quiet achievement.",
  "Mar 19": "Spring equinox approaches. Balance your relentless ambition with deliberate rest.",
  "Mar 20": "Spring equinox. Renewal of purpose reinvigorates your climb. The mountain was waiting for you.",
  "Mar 21": "Aries season activates your professional sector. Bold career moves and ambitious initiatives surge.",
  "Mar 22": "Your calculated risk-taking today differs from impulsiveness. You've done the homework.",
  "Mar 23": "A professional project benefits from fresh, bold energy applied to your solid foundation.",
  "Mar 24": "New career or business initiatives launched now have Aries fire behind your Capricorn strategy.",
  "Mar 25": "Your authentic ambition requires no apology today. Be the mountain: solid, reaching, undeniable.",
  "Mar 26": "Bold professional moves honoring your earth nature. Expand the territory you've earned.",
  "Mar 27": "Your tendency toward overwork sometimes prevents enjoying achievements. Today, celebrate a win.",
  "Mar 28": "A professional alliance benefits from your reliable competence. You bring gravity to any team.",
  "Mar 29": "Success and meaning aren't separate pursuits. The most meaningful work is often the most rewarding.",
  "Mar 30": "Your strategic narrative shows how far you've climbed. Look back and acknowledge the altitude gained.",
  "Mar 31": "March ends with spring energy fueling your ambition and your foundation holding firm.",

  // ── April ──
  "Apr 1": "April asks your serious nature to lighten up. Humor is strategy disguised as play.",
  "Apr 2": "Your grounded presence brings credibility to any plan or project you endorse.",
  "Apr 3": "A friendship deepens through shared work ethic — collaborating on a project reveals character.",
  "Apr 4": "Group dynamics benefit from your steady leadership. You're the one who keeps things on track.",
  "Apr 5": "Your vision for the future is strategic, practical, and secretly grander than anyone suspects.",
  "Apr 6": "Networking events reward your quality-over-quantity approach. One meaningful connection beats twenty superficial ones.",
  "Apr 7": "A cause that promotes structure, education, or traditional values deserves your support today.",
  "Apr 8": "Your professional contacts span industries and hierarchies. That network IS your infrastructure.",
  "Apr 9": "A long-term strategic idea crystallizes. It's been forming for months beneath your planning.",
  "Apr 10": "Your protective instincts activate for those under your care. Shield them with your authority.",
  "Apr 11": "Spring growth mirrors your ascending ambition. Build consistently, like rings in a mighty tree.",
  "Apr 12": "Professional gatherings energize you when strategies are discussed. Seek the planning session.",
  "Apr 13": "A grand professional vision materializes through patient, strategic implementation and persistence.",
  "Apr 14": "Your instinct says: proper structure changes everything. Apply it to one system today.",
  "Apr 15": "Financial decisions demonstrate your legendary discipline. Others admire your fiscal clarity.",
  "Apr 16": "Your dry wit at a gathering lightens the atmosphere with precisely timed humor.",
  "Apr 17": "Saturn structures your evening thoughts. Plan tomorrow before sleep — let your subconscious optimize.",
  "Apr 18": "Your need for achievement balances with growing appreciation for presence. Both have value.",
  "Apr 19": "Taurus season approaches. Fellow earth energy reinforces your material-world mastery.",
  "Apr 20": "Your strategic drive meets sensory satisfaction. Enjoy the rewards of your labor.",
  "Apr 21": "Quality food, excellently prepared, is an achievement for the senses. Master something delicious.",
  "Apr 22": "Earth Day connects your practical nature with environmental stewardship. Build sustainably.",
  "Apr 23": "Hosting with Capricorn precision means everything runs smoothly, looks elegant, and impresses.",
  "Apr 24": "Material wealth isn't vanity. It's the evidence of applied discipline. Build without guilt.",
  "Apr 25": "Sensory pleasure earned through hard work tastes twice as good. Savor what you've built.",
  "Apr 26": "Your patience during slow seasons of growth proves its worth when results finally appear.",
  "Apr 27": "A treasured possession that represents achievement — a watch, a pen, a key — carries your energy.",
  "Apr 28": "Your professional projects show growth when you maintain high standards through every season.",
  "Apr 29": "Evening reflection on your career trajectory reveals steady, impressive ascent. You climb well.",
  "Apr 30": "April ends with your ambition grounded and your strategy refined. The summit gets closer.",

  // ── May ──
  "May 1": "May's stable energy supports your building nature. Earth on earth — your foundation deepens.",
  "May 2": "Your body responds to discipline. A consistent exercise routine rewards Capricorn more than any sign.",
  "May 3": "A carefully considered recommendation enhances someone's career or investment portfolio.",
  "May 4": "Financial mastery creates the security that allows calculated risk-taking later. Save first.",
  "May 5": "Your space benefits from quality investment: pieces that last decades and improve with age.",
  "May 6": "Past achievements remind you of your capacity for excellence. Review a proud moment today.",
  "May 7": "A perfectly executed meal demonstrates that mastery in small things predicts mastery in large ones.",
  "May 8": "Your expertise reserves are deep. Deploy specialized knowledge where it creates maximum impact.",
  "May 9": "Your body needs quality fuel: nutritious, well-prepared, and worthy of the vehicle that carries your ambition.",
  "May 10": "Your mentoring nature combines high expectations with patient teaching. Your students excel.",
  "May 11": "Professional traditions and institutional knowledge define your career culture. Preserve what works.",
  "May 12": "Your presence at any professional gathering commands respect. Walk in with your earned authority.",
  "May 13": "A home upgrade that adds quality and lasting value enriches your daily experience of success.",
  "May 14": "Love expressed through acts of service, long-term commitment, and strategic support speaks your heart.",
  "May 15": "Your long-view perspective navigates short-term turbulence with characteristic calm.",
  "May 16": "Mountain hiking — literally ascending — is your meditation practice. Elevation soothes you.",
  "May 17": "A bookshelf curated for depth and quality tells the story of a mind that values mastery.",
  "May 18": "Your ambitious drive surfaces. Ensure it's pulling toward a worthy summit, not just any peak.",
  "May 19": "An evening of strategic planning — finances, career, or life architecture — satisfies deeply.",
  "May 20": "A gift chosen with care that reflects lasting quality carries the spirit of your mountain-like reliability.",
  "May 21": "Gemini season begins. Flexible communication enriches your structured thinking.",
  "May 22": "Your strategic vision meets versatile expression. Complex plans find clear, accessible words.",
  "May 23": "Lighter conversation and quick exchanges balance your usual depth. Enjoy the surface sometimes.",
  "May 24": "Your communication skills improve when you add agility to your authoritative delivery.",
  "May 25": "Social energy balances your solitary work ethic. People need your grounded presence.",
  "May 26": "Professional networking during Gemini season expands your contact base efficiently.",
  "May 27": "Learning something adjacent to your expertise creates unexpected professional advantages.",
  "May 28": "Local professional events during communicative season reveal opportunities you'd otherwise miss.",
  "May 29": "Your mind strategizes with precision tonight. Document the plan — your future self will thank you.",
  "May 30": "Movement that serves a purpose — a working walk, a commute by bike — aligns efficiency with health.",
  "May 31": "May ends with your foundation reinforced and your communication skills polished for the climb ahead.",

  // ── June ──
  "Jun 1": "June's light energy asks your serious nature to lighten without losing depth.",
  "Jun 2": "Your verbal precision is powerful. Every word chosen deliberately communicates authority and care.",
  "Jun 3": "A strategic plan finds its communicable form. Present it — clarity is your professional weapon.",
  "Jun 4": "Your curiosity about excellence in any domain leads to unexpected professional advantages.",
  "Jun 5": "A quick professional connection or networking exchange pays dividends beyond its brevity.",
  "Jun 6": "A trusted advisor matches your strategic depth. The conversation produces actionable wisdom.",
  "Jun 7": "Your hands create something of lasting quality. Craftsmanship is your creative language.",
  "Jun 8": "Partnership deep-dives become valuable as summer approaches. Invest in key alliances.",
  "Jun 9": "Direct, competent communication earns respect faster than elaborate persuasion. State, don't sell.",
  "Jun 10": "Your strategic mind and your practical instincts form an unbeatable combination today.",
  "Jun 11": "A business text, professional development course, or leadership lecture feeds your mastery drive.",
  "Jun 12": "Your evening schedule should balance work with genuine rest. Even mountains need settled nights.",
  "Jun 13": "Summer approaches, and even your driven nature feels the pull toward some ease.",
  "Jun 14": "Your connection to Saturn strengthens as you approach the year's midpoint. Recommit to your structures.",
  "Jun 15": "Midyear review: are you on track for your goals? Have you rested enough? Adjust the plan.",
  "Jun 16": "A quality dinner at a respected establishment satisfies your taste for excellence and reward.",
  "Jun 17": "Your measured speech sometimes needs warmth added. Today, authority plus kindness equals influence.",
  "Jun 18": "Evening spent in a beautiful, structured environment recharges your earth-sign soul.",
  "Jun 19": "Summer planning that includes strategic rest AND ambitious projects balances your nature.",
  "Jun 20": "Summer solstice eve. The longest light illuminates the path you've climbed and the summit ahead.",
  "Jun 21": "Summer solstice. Maximum daylight, maximum visibility. Survey your kingdom from the altitude you've earned.",
  "Jun 22": "Cancer season begins. Home, family, and emotional foundations deserve your building skills.",
  "Jun 23": "Your home is your legacy in miniature. Build it with the same care as your career.",
  "Jun 24": "Emotional investment in family creates the bedrock that supports your professional structures.",
  "Jun 25": "Your nurturing side expresses through providing, protecting, and building lasting security.",
  "Jun 26": "A family milestone reveals the legacy you're already creating through steady dedication.",
  "Jun 27": "Quality home cooking demonstrates that even domestic tasks can reach Capricorn excellence.",
  "Jun 28": "Your emotional wisdom, usually expressed through action, finds words today. Speak what you feel.",
  "Jun 29": "A quiet evening of deep emotional connection recharges you more than any professional success.",
  "Jun 30": "June ends with emotional foundations strengthened beneath your professional ambitions.",

  // ── July ──
  "Jul 1": "July asks for emotional connection alongside professional ambition. Build both empires.",
  "Jul 2": "Your emotional restraint is challenged gently. Can you stay with a feeling without solving it?",
  "Jul 3": "Home as achievement: beautiful, functional, and built to last generations.",
  "Jul 4": "Freedom within structure is your Capricorn paradox. Today, find the liberty in your discipline.",
  "Jul 5": "Emotional conversations you usually defer deserve your full attention. Don't postpone feeling.",
  "Jul 6": "Kitchen mastery turns even simple meals into quiet demonstrations of excellence.",
  "Jul 7": "Family traditions built over years carry the weight of your dedication. They ARE your legacy.",
  "Jul 8": "Trust your emotional gut today. Your instincts for people are sharper than you usually credit.",
  "Jul 9": "Vulnerability isn't weakness. It's the foundation material for the deepest structures.",
  "Jul 10": "An emotional investment made now carries your mountain-like stability behind it.",
  "Jul 11": "Your protective nature extends fiercely to those you love. Guardian energy at full strength.",
  "Jul 12": "Generational wisdom carries strategic gold. Ask an elder about their life decisions.",
  "Jul 13": "Physical activity under summer sun loosens your usually tight-held control. Release through movement.",
  "Jul 14": "Summer relaxation tests your ability to enjoy without achieving. Can you simply be?",
  "Jul 15": "Mid-July: your emotional world is richer than usual. Feelings add warmth to your cool competence.",
  "Jul 16": "A creative project with emotional depth produces something unexpectedly powerful. Feel while you build.",
  "Jul 17": "Your home evolution this month should honor both legacy and comfort. Heritage luxury.",
  "Jul 18": "Financial strategies that include family security bring your protective instinct into the material world.",
  "Jul 19": "Leo's fire approaches. Creative expression asks your structured nature to play without a plan.",
  "Jul 20": "Evening in your carefully crafted home space reminds you what all the building was for.",
  "Jul 21": "Emotional processing through practical action helps you understand what you feel and need.",
  "Jul 22": "Leo season begins. Creative fire warms your strategic bones. Build something beautiful.",
  "Jul 23": "Your structured approach gains Leo's bold confidence. Present with authority AND warmth.",
  "Jul 24": "Playful expression of your ambitions makes strategy accessible and inspiring. Lead through joy.",
  "Jul 25": "Your inner child wants to build sandcastles — elaborate, ambitious, grand designs in the sand.",
  "Jul 26": "Romantic gestures during Leo season: quality experiences, lasting gifts, and genuine admiration.",
  "Jul 27": "A creative collaboration where your structure supports another's vision produces excellence.",
  "Jul 28": "Heart-centered leadership gives your authority emotional power. People follow warmth AND competence.",
  "Jul 29": "Enjoyment as strategy: people who love their work outperform everyone. Find the joy in your craft.",
  "Jul 30": "Public recognition of your achievements validates years of quiet, dedicated effort.",
  "Jul 31": "July ends with emotional depth and creative warmth enriching your strategic worldview.",

  // ── August ──
  "Aug 1": "August's creative peak asks your structured nature to build something with artistic soul.",
  "Aug 2": "Creative-strategic projects shine: presentations, architectural thinking, and elegant problem-solving.",
  "Aug 3": "Your teaching combines high standards with genuine investment. You make excellence achievable.",
  "Aug 4": "A strategic challenge that requires creative thinking activates your best problem-solving abilities.",
  "Aug 5": "Pride in craftsmanship: every detail executed perfectly, every standard met or exceeded.",
  "Aug 6": "Your deep expertise serves a creative project today. Mastery creates art.",
  "Aug 7": "Romance built on mutual respect, shared ambition, and earned trust speaks your heart's language.",
  "Aug 8": "A professional partnership with creative vision produces something that lasts.",
  "Aug 9": "Your space showcases your achievements: framed milestones, quality pieces, and tasteful success.",
  "Aug 10": "Your courage to maintain standards when others lower theirs is your defining professional trait.",
  "Aug 11": "A bold professional move — proposing, launching, or demanding — puts your authority on display.",
  "Aug 12": "Summer activity in structured form — scheduled hikes, organized sports, planned retreats — suits you.",
  "Aug 13": "Your dedicated approach to everything you value is itself a form of art and devotion.",
  "Aug 14": "Summer's peak invites peak performance. Execute the most ambitious project of the season.",
  "Aug 15": "Mid-August: your creative-strategic engine is refined. Apply it to your most important work.",
  "Aug 16": "Recognition from an authority figure validates your consistent standards and dedicated effort.",
  "Aug 17": "Your strategic mastery serves legacy thinking brilliantly. You plan in generations, not quarters.",
  "Aug 18": "Evening at a quality establishment — a fine restaurant, a respected venue — satisfies your refined taste.",
  "Aug 19": "Late summer transitions feel like preparation for the productive season you thrive in.",
  "Aug 20": "The shift toward more analytical energy aligns with your natural strategic precision.",
  "Aug 21": "Summer achievements crystallize into professional milestones. Document the progress.",
  "Aug 22": "Virgo energy approaches. Fellow earth sign detail reinforces your already meticulous standards.",
  "Aug 23": "Virgo season begins. Practical refinement polishes your already high-quality output.",
  "Aug 24": "Your strategic plans receive detailed optimization. Already excellent work becomes impeccable.",
  "Aug 25": "Health routines support your demanding ambitions. Peak performance requires peak maintenance.",
  "Aug 26": "Attention to detail improves your already strong execution. Precision elevates mastery.",
  "Aug 27": "Organizing your systems — files, contacts, processes — creates infrastructure for the next summit attempt.",
  "Aug 28": "Daily excellence in small matters predicts excellence in large ones. Maintain your standards everywhere.",
  "Aug 29": "Service through competence and reliability fulfills your Saturn-guided purpose.",
  "Aug 30": "Practical goal refinement turns ambitious dreams into achievable project plans.",
  "Aug 31": "August ends with your standards upheld and your strategic plans polished to brilliance.",

  // ── September ──
  "Sep 1": "September channels your ambitious earth energy into focused, productive excellence.",
  "Sep 2": "Health routines optimized for sustained performance support your marathon of achievement.",
  "Sep 3": "A professional audit: where are you exceeding standards? Where is improvement needed? Balance both.",
  "Sep 4": "Your dedication to mastery makes you an invaluable resource in daily professional interactions.",
  "Sep 5": "A detailed review of your strategic plan produces refinements that broad thinking missed.",
  "Sep 6": "Your body needs quality fuel for sustained ambition: nutritious, well-prepared, and dignified.",
  "Sep 7": "Mentoring through example teaches more effectively than instruction. Be the standard.",
  "Sep 8": "A health investment that supports your demanding lifestyle pays compound interest over years.",
  "Sep 9": "Daily contact with excellence — in work, in environment, in relationships — is essential.",
  "Sep 10": "A quality meal, mindfully prepared and consumed, demonstrates mastery in the daily domain.",
  "Sep 11": "Your grounded perspective helps others find structure during difficulty. Be the pillar.",
  "Sep 12": "A strategic partner or professional mentor reminds you that shared ambition builds faster.",
  "Sep 13": "Organization of your professional systems creates infrastructure for your next major achievement.",
  "Sep 14": "Your achievement health check: are you progressing enough? Resting enough? Building wisely?",
  "Sep 15": "Physical strength and endurance directly support professional performance. Exercise is strategy.",
  "Sep 16": "Your reliable guidance helps someone navigate a challenge they couldn't solve alone.",
  "Sep 17": "A routine optimization that increases efficiency without sacrificing quality is your kind of magic.",
  "Sep 18": "Strategic planning during this organized season produces plans that will execute flawlessly.",
  "Sep 19": "Virgo season has refined your standards to a razor edge. Quality never compromised.",
  "Sep 20": "A practical achievement demonstrates that consistent effort compounded over time produces greatness.",
  "Sep 21": "Autumn equinox. Balance ambition with appreciation for what you've already built.",
  "Sep 22": "Libra season begins. Partnership and refinement add grace to your powerful ambitions.",
  "Sep 23": "Professional relationships benefit from your reliable, competent presence. Trust builds empires.",
  "Sep 24": "A partnership deepens when you share strategic insights with genuine care for shared success.",
  "Sep 25": "Balanced relationships give your ambitious nature a beautiful legacy to build for.",
  "Sep 26": "Aesthetics and quality intersect. Your professional image, space, and work should all reflect excellence.",
  "Sep 27": "Your diplomatic skills emerge when authoritative communication adds warmth and grace.",
  "Sep 28": "A partner's respect for your achievements and work ethic touches your deeply private heart.",
  "Sep 29": "Balance between career and relationship IS possible. It looks like mutual investment in each other's success.",
  "Sep 30": "September polished your strategic approach to a fine edge. Ready for the final quarter's push.",

  // ── October ──
  "Oct 1": "October's deepening energy fuels your most serious, strategic thinking. The final quarter begins.",
  "Oct 2": "Relationships reveal professional implications when you see partnership as strategic alliance.",
  "Oct 3": "An aesthetically excellent environment inspires better strategic thinking. Invest in your workspace.",
  "Oct 4": "Your reputation for reliability and excellence is your most valuable professional asset.",
  "Oct 5": "A strategic partnership with mutual benefit advances both careers. True alliance, not transaction.",
  "Oct 6": "Your ability to maintain composure in any professional situation is genuinely admirable.",
  "Oct 7": "Balance between professional ambition and personal relationship deepens with intentional effort.",
  "Oct 8": "Your honest, competent assessment heals a professional wound that flattery couldn't. Truth builds trust.",
  "Oct 9": "An autumn evening of strategic reflection, quality whiskey, and long-term planning is your paradise.",
  "Oct 10": "Seasonal transition activates legacy thinking. What are you building that will outlast this season?",
  "Oct 11": "A long-term project — a business, an investment, a legacy initiative — deserves renewed dedication.",
  "Oct 12": "Your appreciation for tradition and excellence honors the builders who came before you.",
  "Oct 13": "Autumn cuisine prepared with precision and quality ingredients is achievement on a plate.",
  "Oct 14": "A strategic breakthrough simplifies what complexity had obscured. The best plans are elegant.",
  "Oct 15": "Your ambition grows with October's seriousness. Bigger goals deserve bolder strategies.",
  "Oct 16": "A gift of enduring quality — leather goods, fine tools, lasting craftsmanship — is perfectly Capricorn.",
  "Oct 17": "Your autumn workspace should feel commanding: warm, organized, efficient, and inspiring.",
  "Oct 18": "Professional truth in partnerships deepens when competence is matched by emotional honesty.",
  "Oct 19": "Evening review of your long-term strategy reveals it's working. You climb at exactly the right pace.",
  "Oct 20": "Depth approaches as Scorpio season nears. Your strategy is about to go beneath the surface.",
  "Oct 21": "A professional or educational event delivers strategic insight that reshapes your approach.",
  "Oct 22": "Scorpio season begins. Deep transformation adds power to your already potent ambition.",
  "Oct 23": "Strategic depth meets emotional intensity. Your plans gain psychological awareness.",
  "Oct 24": "An uncomfortable truth about your control patterns surfaces. Examine it with Capricorn honesty.",
  "Oct 25": "Your intuition, usually focused on strategy, turns inward with unusual emotional precision.",
  "Oct 26": "Intimacy challenges your guard. The deepest partnerships are forged through mutual vulnerability.",
  "Oct 27": "Investment or shared financial decisions benefit from deep, thorough analysis. Miss nothing.",
  "Oct 28": "Your capacity for strategic transformation: can you dismantle an old plan to build a better one?",
  "Oct 29": "The deeper you dig, the stronger your foundations become. Some building is underground.",
  "Oct 30": "Internal strategic transformation is as significant as an external career achievement.",
  "Oct 31": "Your costume should project authority with a twist: the executive, the architect, the king.",

  // ── November ──
  "Nov 1": "November deepens everything, including your strategic convictions. Look beneath outcomes.",
  "Nov 2": "Honor those who built before you. Mentors, ancestors, and professional founders across history.",
  "Nov 3": "A strategic breakthrough through emotional understanding integrates head, heart, and ambition.",
  "Nov 4": "Shared investments and deep partnerships benefit from your thorough, disciplined analysis.",
  "Nov 5": "Trust built through consistent reliability runs deeper than trust built through charisma.",
  "Nov 6": "Emotional investment — the kind you sometimes withhold — builds the partnerships that build empires.",
  "Nov 7": "Your resilience is structural: you stand because your foundations are deep and well-constructed.",
  "Nov 8": "A profound truth about ambition and integrity surfaces. Real success includes right action.",
  "Nov 9": "Strategic dreams carry blueprints for your next major build. Journal the architecture.",
  "Nov 10": "A transformation in strategic thinking ripples into every area of professional life.",
  "Nov 11": "Remember the builders, mentors, and leaders who shaped your ambition. Their standards live in you.",
  "Nov 12": "Financial mastery during analytical season produces investment decisions of lasting value.",
  "Nov 13": "Your strategic depth during Scorpio season produces plans that will take years to fully execute.",
  "Nov 14": "Professional boundaries based on clear standards protect your excellence and your energy.",
  "Nov 15": "Halfway through November, your strategy has deepened. Some assumptions have been productively challenged.",
  "Nov 16": "Holding strategic complexity without rushing to resolution shows advanced mastery. Sit with the puzzle.",
  "Nov 17": "A private strategic project generates plans that will eventually manifest as a major achievement.",
  "Nov 18": "A major professional challenge resolves through your characteristically disciplined approach.",
  "Nov 19": "Release outdated strategies that no longer produce results. Make room for evolved approaches.",
  "Nov 20": "Sagittarius season approaches. Philosophical fire warms your strategic bones. Dream bigger.",
  "Nov 21": "Sagittarius optimism loosens your usually tight plans. Some expansion is uncomfortable but necessary.",
  "Nov 22": "Adventure and philosophy challenge your structure — and that's exactly what makes it stronger.",
  "Nov 23": "Holiday season begins. Your organizational talent makes celebrations elegant and memorable.",
  "Nov 24": "Traditional celebrations managed with Capricorn precision and care become family legend.",
  "Nov 25": "Your generous nature, expressed through quality and thoughtfulness, outshines flashier giving.",
  "Nov 26": "Philosophical generosity during the holidays: share your strategic wisdom with those who need guidance.",
  "Nov 27": "Your steadying presence during holiday chaos makes everything around you work better.",
  "Nov 28": "Gratitude for the structure, discipline, and patience that built your achievements fills your evening.",
  "Nov 29": "A grand professional vision set before your season begins has strategic momentum behind it.",
  "Nov 30": "November ends with deeper strategy and growing anticipation. Your season approaches.",

  // ── December ──
  "Dec 1": "December builds toward YOUR powerful season. Ambition, achievement, and cosmic authority approach.",
  "Dec 2": "Holiday preparation meets your organizational excellence. Everything runs on your master plan.",
  "Dec 3": "A quality gift — something built to last, chosen with care — carries more weight than any impulse purchase.",
  "Dec 4": "Holiday entertaining with Capricorn standards means flawless execution and memorable quality.",
  "Dec 5": "Winter's arrival signals your power season approaching. The cold concentrates your authority.",
  "Dec 6": "Holiday baking or cooking with meticulous attention produces results that command respect.",
  "Dec 7": "Family gatherings you organize run like clockwork. Beautiful, warm, and impeccably managed.",
  "Dec 8": "A holiday gift that represents enduring quality is the perfect Capricorn gesture.",
  "Dec 9": "Year-end review: strategy executed, standards maintained, foundations reinforced. How'd you do?",
  "Dec 10": "Holiday decorating with Capricorn taste: elegant, classic, and quietly commanding.",
  "Dec 11": "Your home during December reflects your refined standards: beautiful, warm, and perfectly arranged.",
  "Dec 12": "Strategic rest before your season is intelligent preparation, not laziness. Recharge deliberately.",
  "Dec 13": "Pre-birthday season energy builds. Saturn gathers your concentrated power for the year's climax.",
  "Dec 14": "Your seasonal generosity expresses through quality, service, and strategic gift-giving.",
  "Dec 15": "Year-end highlights show more achievement, more mastery, and more building than any previous year.",
  "Dec 16": "A quiet evening of strategic planning during the busy season keeps you grounded and productive.",
  "Dec 17": "Your composed presence at holiday gatherings commands respectful attention. Lead quietly.",
  "Dec 18": "Capricorn season approaches fast. Can you feel the mountain calling your name?",
  "Dec 19": "Your structures have held all year. Your discipline has paid off. Your season is the reward.",
  "Dec 20": "Year-end accomplishments demonstrate that steady discipline outperforms sporadic brilliance.",
  "Dec 21": "Winter solstice. CAPRICORN SEASON BEGINS. The most powerful time in your cosmic calendar.",
  "Dec 22": "Your season opens with the authority of winter itself. Cold, clear, and commanding.",
  "Dec 23": "Holiday eve preparations run perfectly under your masterful coordination. The mountain manages.",
  "Dec 24": "Tonight, your quiet authority gathers people around warmth and tradition. You made this happen.",
  "Dec 25": "Today, receive what you've earned: love, respect, and the satisfaction of a year well-built.",
  "Dec 26": "Post-holiday strategic thinking begins. What will you build in the coming year?",
  "Dec 27": "Your year-end journal should read like an achievement ledger balanced with wisdom. Document the climb.",
  "Dec 28": "A New Year strategy forms: higher standards, bigger goals, and even more disciplined execution.",
  "Dec 29": "Your achievements, your standards, and your resilience are the three pillars of this year.",
  "Dec 30": "Tomorrow the year ends. Tonight, acknowledge every foundation laid and every summit reached.",
  "Dec 31": "The year closes with you standing at the peak you climbed to with quiet, relentless determination. You are the mountain. Happy new year, Capricorn.",
};
