/** 365 daily quotes for Gemini — one for every day of the year. */
export const geminiDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new conversations. Your quick mind is already three steps ahead — write those ideas down before they fly away.",
  "Jan 2": "Curiosity is your compass today. Follow every interesting thread — one of them leads somewhere brilliant.",
  "Jan 3": "Words carry extra power for you today. Choose them carefully and watch them shape reality.",
  "Jan 4": "Your dual nature is a feature, not a bug. Let both sides of yourself show up today — the world needs both.",
  "Jan 5": "A short trip or unexpected conversation sparks a chain reaction of ideas. Stay flexible.",
  "Jan 6": "Your nervous system needs soothing today. Breathe deeply — your brilliant mind works better when calm.",
  "Jan 7": "Learning something new makes you feel alive. Pick up a book, watch a documentary, or start a language app.",
  "Jan 8": "Your wit disarms tension today. Use humor to bridge gaps where logic can't reach.",
  "Jan 9": "Multiple interests don't make you scattered — they make you dimensional. Honor your multiplicity.",
  "Jan 10": "A sibling, neighbor, or local connection holds a surprising opportunity today. Stay socially tuned in.",
  "Jan 11": "Your mind races at night. Journal before bed — capture the chaos on paper so your body can rest.",
  "Jan 12": "Adaptability is your secret weapon. A sudden change today hands you an advantage everyone else misses.",
  "Jan 13": "Your communication style opens a door that was previously locked. Say the right thing at the right time.",
  "Jan 14": "Social energy is high. Connect with three people today — each conversation plants a seed.",
  "Jan 15": "Focus is your January challenge. Choose one thing and give it your full Gemini brilliance for just one hour.",
  "Jan 16": "Your playfulness lifts the mood everywhere you go. Don't underestimate the power of levity.",
  "Jan 17": "An intellectual debate sharpens your perspective. Argue for both sides — it's what you're built for.",
  "Jan 18": "Your hands want to be busy. Write, type, sketch, text — let your fingers process what your mind generates.",
  "Jan 19": "A clever shortcut saves hours today. Your brain naturally optimizes — trust the hack.",
  "Jan 20": "Your social circle is your net worth today. The right introduction changes everything.",
  "Jan 21": "Two paths present themselves. This is your specialty — gather info on both, then choose with confidence.",
  "Jan 22": "Your capacity for small talk is actually deep connection in disguise. Never dismiss casual conversation.",
  "Jan 23": "Technology or gadgets solve a problem beautifully today. You speak the language of innovation.",
  "Jan 24": "Restlessness signals growth. Your mind is outgrowing something — let it expand.",
  "Jan 25": "A book, podcast, or article changes your thinking today. Consume the idea, then share it.",
  "Jan 26": "Your verbal agility persuades where facts alone couldn't. Make your case today — you'll win.",
  "Jan 27": "Multitasking works for you when it's intentional. Juggle, but don't let anything drop.",
  "Jan 28": "Your twin nature finds balance today. Action and reflection, speech and listening, motion and rest.",
  "Jan 29": "A message you send today ripples further than you expect. Write it with care and released intention.",
  "Jan 30": "Your nervous energy is creative fuel. Channel the buzz into art, writing, or problem-solving.",
  "Jan 31": "January ends with your mind buzzing productively. You've connected, created, and communicated brilliantly.",

  // ── February ──
  "Feb 1": "February's love energy meets your air-sign intellect. For you, the most romantic thing is a great conversation.",
  "Feb 2": "Your mind is a butterfly garden today — let every thought land briefly, then release it beautifully.",
  "Feb 3": "A writing project has been calling. Today, answer the call — even just 500 words. Start.",
  "Feb 4": "Your adaptability makes you the person everyone wants on their team. Collaborate today.",
  "Feb 5": "Two things that seemed unrelated suddenly connect in your mind. That's Gemini genius — trust the synthesis.",
  "Feb 6": "Social media or digital communication serves you well today. Your online presence has real impact.",
  "Feb 7": "Your wit and charm peak today. Use them for good — make someone laugh who hasn't in a while.",
  "Feb 8": "Learning and teaching are two sides of your coin. Today, do both — you grow either way.",
  "Feb 9": "Air sign lightness doesn't mean shallowness. Your breezy approach today covers profound depth.",
  "Feb 10": "A phone call or text reconnects you with someone important. Communication is your love language.",
  "Feb 11": "Your curiosity about human nature helps you understand someone better today. Ask the interesting question.",
  "Feb 12": "Multiple projects don't overwhelm you — they energize you. Let the variety flow.",
  "Feb 13": "Pre-Valentine energy: your gift is words. A handwritten note from Gemini is worth diamonds.",
  "Feb 14": "Love speaks through conversation for you. The date that matters most is the one where you talked until 3am.",
  "Feb 15": "Your mind needs variety like your lungs need air. Change up your routine, even slightly.",
  "Feb 16": "A neighborhood connection or local community involvement enriches your day. Your world starts close to home.",
  "Feb 17": "Your quicksilver mind makes a decision that's been pending. Sometimes speed is wisdom.",
  "Feb 18": "Information is your currency. Today, you're rich — share the knowledge generously.",
  "Feb 19": "Your dual perspective on a tricky situation reveals the solution others can't see. Speak up.",
  "Feb 20": "Movement — walking, biking, dancing — gets your thoughts flowing better than sitting still.",
  "Feb 21": "A sibling or close friend mirrors something back to you. Listen to what the mirror shows.",
  "Feb 22": "Your storytelling ability captivates today. Whether at a meeting or dinner table, you have the floor. Own it.",
  "Feb 23": "Mental health maintenance: your busy brain needs intentional downtime. Schedule nothing for an hour.",
  "Feb 24": "Communication clarity matters more than usual. Review that email before sending.",
  "Feb 25": "Your flexibility in the face of change inspires someone who's struggling to adapt. Model grace under pressure.",
  "Feb 26": "A new gadget, app, or tool perfectly serves a need. You find what's useful before everyone else.",
  "Feb 27": "Your nervous system thanks you for any calming practice today. Meditation, float, breathwork — choose one.",
  "Feb 28": "February ends with your mind vibrant and connected. You've been the bridge between ideas and people all month.",
  "Feb 29": "Bonus day for your boundless curiosity. Learn something completely outside your usual interests.",

  // ── March ──
  "Mar 1": "March blows in with wind and ideas. Your air sign element is activated — think big, communicate bigger.",
  "Mar 2": "Your pen, keyboard, or voice is your most powerful tool today. Create with language.",
  "Mar 3": "Two perspectives on the same issue both feel valid. That's not confusion — that's nuance. Hold both.",
  "Mar 4": "A podcast, lecture, or conversation downloads exactly the insight you needed. Information finds you.",
  "Mar 5": "Your social battery charges through connection. Seek out the people who make you think.",
  "Mar 6": "Flexibility in communication saves a situation today. Adjust your tone and watch walls dissolve.",
  "Mar 7": "Your mercurial energy shifts rapidly. Ride the waves instead of fighting the current.",
  "Mar 8": "Writing — in any form — is therapeutic for you. Journal, blog, or just text a friend your thoughts.",
  "Mar 9": "A neighbor, sibling, or local acquaintance delivers unexpected news that opens a door.",
  "Mar 10": "Your mental energy peaks. Tackle the challenging cognitive tasks now while your mind is razor-sharp.",
  "Mar 11": "Gossip tempts, but meaningful conversation satisfies. Choose depth over drama today.",
  "Mar 12": "Your hands are expressive today. Gesture wildly, build something tangible, or let your fingers tell stories.",
  "Mar 13": "A humorous take on a serious subject breaks through resistance. Laughter is your skeleton key.",
  "Mar 14": "Pi Day energy: your mathematical, pattern-seeking mind sees connections everywhere. Beautiful.",
  "Mar 15": "Your dual nature helps you see both opportunity and risk simultaneously. That's wisdom, not indecision.",
  "Mar 16": "Travel — even just driving a new route — refreshes your mental landscape. Get moving.",
  "Mar 17": "Luck finds the prepared mind, and your mind is always prepared. Stay alert for the lucky break.",
  "Mar 18": "Your communication style evolves today. A more authentic voice emerges when you stop performing.",
  "Mar 19": "Spring approaches, and your air sign nature feels the shift in the wind. Something exciting is coming.",
  "Mar 20": "Spring equinox stimulates mental renewal. Clear old thought patterns to make room for fresh perspectives.",
  "Mar 21": "Aries season fires up your sector of friendship and community. Social adventures beckon.",
  "Mar 22": "A group discussion or brainstorm session needs your rapid-fire mind. Contribute freely.",
  "Mar 23": "Your ability to code-switch between social groups is a genuine gift. Move between worlds fluidly today.",
  "Mar 24": "A notification or message contains an opportunity disguised as ordinary information. Read closely.",
  "Mar 25": "Your attention span is short today — and that's okay. Give yourself permission to flit.",
  "Mar 26": "A short course, workshop, or tutorial satisfies your craving for mental stimulation.",
  "Mar 27": "Your silver tongue negotiates something that seemed impossible. Language is your magic.",
  "Mar 28": "Sibling or twin energy is highlighted. If applicable, reach out. If not, honor your inner duality.",
  "Mar 29": "The weather of your mind changes hourly. Track it with curiosity, not judgment.",
  "Mar 30": "A community gathering or social event sparks ideas that could shape your next several months.",
  "Mar 31": "March ends with your mind full and your connections strong. You've been the messenger of possibility.",

  // ── April ──
  "Apr 1": "Your Trickster archetype dances today. Playful pranks, clever wordplay, and delightful surprise — bring it.",
  "Apr 2": "Restless energy needs an outlet. A walk-and-talk or moving meditation channels it perfectly.",
  "Apr 3": "Your pen is mightier today. Write that letter, letter, email, story, or post you've been composing mentally.",
  "Apr 4": "A debate or discussion sharpens your already keen mind. Engage with ideas that challenge you.",
  "Apr 5": "Your social network holds hidden value. A friend of a friend connects you to something important.",
  "Apr 6": "Air sign clarity cuts through emotional fog today. You see what others feel but can't articulate.",
  "Apr 7": "Technology serves you exceptionally well today. Automate, optimize, or create digitally.",
  "Apr 8": "Your duality blesses you with empathy for all sides. In any conflict, you see everyone's truth.",
  "Apr 9": "A local adventure — a new café, a bookshop, an unexplored street — feeds your curiosity.",
  "Apr 10": "Your verbal spontaneity produces something genuinely brilliant today. Don't edit — let it flow.",
  "Apr 11": "Spring energy matches your mental agility. Your thoughts bloom like wildflowers — abundant and unpredictable.",
  "Apr 12": "A communication breakthrough in a relationship happens when you listen as masterfully as you speak.",
  "Apr 13": "Your nervous system wants fresh air. Open windows, walk outside, let the breeze move through you.",
  "Apr 14": "You collect facts like others collect shells — with delight and wonder. Share a fascinating one today.",
  "Apr 15": "A practical task benefits from your creative problem-solving. You see angles others miss.",
  "Apr 16": "Your need for variety is intense today. Don't fight it — schedule different activities back to back.",
  "Apr 17": "A message you receive today changes a belief you've held. Evolution of thought is your specialty.",
  "Apr 18": "Your wit is protection and connection simultaneously. Use it to bridge awkward moments.",
  "Apr 19": "Taurus season approaches, and grounding energy helps your scattered tendencies. Welcome the slowdown.",
  "Apr 20": "Your mind might resist the slower pace, but your body welcomes it. Listen to the body today.",
  "Apr 21": "A financial or material matter benefits from your clever analysis. Apply your brainpower to practical wealth.",
  "Apr 22": "Earth Day grounds your airy nature. Touch dirt, walk barefoot, or tend a plant. Anchor your thoughts.",
  "Apr 23": "World Book Day — your personal holiday. Lose yourself in words. Reading is oxygen for Gemini.",
  "Apr 24": "Your capacity to find humor in difficulty is a genuine coping strength. Laugh through the hard part.",
  "Apr 25": "A new interest catches fire in your mind. Let it burn — even if it's the fifth one this month.",
  "Apr 26": "Your voice mail, texts, and emails create real-world results today. Your words have material power.",
  "Apr 27": "Mental fatigue hits harder than physical fatigue for you. Rest your brain with something completely mindless.",
  "Apr 28": "A conversation you've been avoiding actually goes better than expected. Your communication skills save the day.",
  "Apr 29": "Your need for mental stimulation intensifies. Feed it with quality input — content matters.",
  "Apr 30": "April ends with ideas swirling like spring pollen. Capture the best ones. The rest will blow away.",

  // ── May ──
  "May 1": "May arrives with blossoming ideas. You're the pollinator — cross-fertilize concepts between different fields.",
  "May 2": "A quiet day isn't empty for Gemini — it's when the inner dialogue gets loudest. Direct it productively.",
  "May 3": "Your social charm opens doors that qualifications alone couldn't. Show up authentically and let connection do the work.",
  "May 4": "Two projects compete for your attention. Good news: you can juggle both. Start with whichever excites more.",
  "May 5": "A conversation with a stranger teaches you something no friend could. Stay open to unfamiliar voices.",
  "May 6": "Your writing is soulful today. Whatever you put on paper has unusual emotional depth.",
  "May 7": "Your mental energy needs physical grounding. Take your thinking outdoors — walk while you plan.",
  "May 8": "A sibling or childhood friend holds a key today. Reconnect with your roots through relationship.",
  "May 9": "Your ability to explain complicated things simply is needed. Be the translator between worlds.",
  "May 10": "Information overload threatens. Curate your input today — quality over quantity of ideas.",
  "May 11": "A short, spontaneous trip or outing resets your perspective brilliantly. Just go.",
  "May 12": "Your nervous energy channels into something creative when you give it direction. Point and shoot.",
  "May 13": "Your season is approaching. Feel the electrical buzz in the air. That's your cosmic battery charging.",
  "May 14": "A language — spoken, coded, artistic, or musical — calls to you. Engage with it today.",
  "May 15": "Your anticipation for Gemini season surges. Pre-game your birthday intentions now.",
  "May 16": "Words of affirmation from someone meaningful hit differently today. Sometimes you need to hear it.",
  "May 17": "Your ability to see patterns in chaos is peak today. Connect the dots others can't see.",
  "May 18": "Movement and thought are inseparable for you. Pace while you talk, walk while you brainstorm.",
  "May 19": "A deep breath between activities protects your nervous system. Transition consciously.",
  "May 20": "Tomorrow your season begins. Tonight, honor the version of you that weathered the past year. You've evolved.",
  "May 21": "Happy Gemini season! Your cosmic batteries are fully charged. Communicate, connect, and create unapologetically.",
  "May 22": "Birthday energy fills you with electric curiosity. What will this year bring? The answer: whatever you ask it for.",
  "May 23": "Your mental agility is at its apex. Learn something today that challenges your smartest self.",
  "May 24": "Socializing during your season feels like breathing pure oxygen. Surround yourself with stimulating people.",
  "May 25": "Your dual nature harmonizes today. Both sides of you are pulling in the same direction. Rare and powerful.",
  "May 26": "A writing, speaking, or media opportunity presents itself during your season. Take it.",
  "May 27": "Your season supercharges your already electric communication. Conversations sparkle with insight and humor.",
  "May 28": "A decision you've been ping-ponging lands clearly. When both minds agree, the answer is certain.",
  "May 29": "Your youthful energy radiates during your season. People describe you as ageless — and they're right.",
  "May 30": "Short trips, local exploration, and spontaneous outings bring peak joy. Say yes to the invitation.",
  "May 31": "May closes with Gemini energy fully blazing. Your season is just getting started.",

  // ── June ──
  "Jun 1": "June doubles down on your season's magic. Mental clarity and social grace combine beautifully.",
  "Jun 2": "Your storytelling power captivates every audience today. Share the story only you can tell.",
  "Jun 3": "The Twins energy means you contain multitudes. Today, let all of them breathe.",
  "Jun 4": "A brilliant idea doesn't need your usual second-guessing. This one is solid — execute it.",
  "Jun 5": "Your natural networking creates a connection today that will bear fruit for years. Plant generously.",
  "Jun 6": "Air sign clarity slices through confusion. You see the truth others are too emotional to notice.",
  "Jun 7": "A book, article, or film profoundly shifts your perspective. Your mind is a sponge — let it absorb.",
  "Jun 8": "Your season peaks with communication at its most potent. Words spoken today carry unusual weight.",
  "Jun 9": "The social butterfly in you is magnetic. Every room you enter gets brighter. That's not ego — it's energy.",
  "Jun 10": "Two truths seem to contradict each other. Only a Gemini can hold both and find they're actually complementary.",
  "Jun 11": "Mental restlessness needs an ambitious target. Aim high — your agile mind deserves a worthy challenge.",
  "Jun 12": "Your hands create beauty today — write, cook, build, or gesture with expressive purpose.",
  "Jun 13": "A friendship deepens through intellectual honesty. Share what you really think, not what's polite.",
  "Jun 14": "Your season begins to wane, but your powers don't. You've been magnificent — and you're not done.",
  "Jun 15": "Half the year, fully lit. You've connected, created, and communicated more than most. And there's more to come.",
  "Jun 16": "Music matches your mercury energy today. Sing along, drum your fingers, let rhythm carry your ideas.",
  "Jun 17": "Your lighter side isn't superficial — it's strategic. Keeping things breezy creates space for depth later.",
  "Jun 18": "A communication channel you've neglected holds an important message. Check your inbox, voicemail, or DMs.",
  "Jun 19": "Your wit meets wisdom today. The joke that lands also illuminates. That's art.",
  "Jun 20": "Your season closes with gratitude for your mind, your words, and everyone who listened.",
  "Jun 21": "Summer solstice. The light matches your brilliance. Absorb the longest day with Gemini joy.",
  "Jun 22": "Cancer season begins. Emotional depth beckons your usually cerebral self. Let feelings in.",
  "Jun 23": "Your home and inner world deserve the same curiosity you give the outer world. Explore inward.",
  "Jun 24": "Emotional language doesn't come as naturally, but today, try to speak from the heart, not just the mind.",
  "Jun 25": "Your versatility means you can nurture while still being curious. Blend warmth with intellect.",
  "Jun 26": "A family conversation needs your diplomatic, multi-perspectived skill set. Be the translator.",
  "Jun 27": "Your restlessness settles when you create a cozy, stimulating space at home. Books, music, thoughtful décor.",
  "Jun 28": "Nostalgia and novelty meet. You can honor the past and crave the future simultaneously.",
  "Jun 29": "Your inner child wants to play today. Puzzles, games, clever challenges — give your mind fun.",
  "Jun 30": "June ends with emotional depth adding a new color to your already rainbow personality. Growth.",

  // ── July ──
  "Jul 1": "Cancer season continues to deepen you. The emotional education is uncomfortable but valuable.",
  "Jul 2": "Your curiosity turns inward today. What are the stories you tell yourself? Are they still true?",
  "Jul 3": "A domestic project benefits from your clever mind. You approach home improvement like a puzzle.",
  "Jul 4": "Freedom of thought is your most cherished liberty. Celebrate it by thinking something no one else would.",
  "Jul 5": "Your emotional intelligence grows today. Feeling isn't a foreign language — it's one you're learning to speak.",
  "Jul 6": "A deep conversation about family or origins reveals patterns you'd never seen before.",
  "Jul 7": "Your mind craves stimulation even at home. Rearrange, redecorate, or start a home-based project.",
  "Jul 8": "Communication with family members flows better when you lead with curiosity instead of correction.",
  "Jul 9": "Your dual nature allows you to be both caretaker and free spirit. Balance them gracefully.",
  "Jul 10": "An emotional truth hits your intellect like lightning. Let it illuminate rather than shock.",
  "Jul 11": "Your ability to lighten heavy situations is needed at home or within your inner circle today.",
  "Jul 12": "Reading a great novel or memoir gives you both escape and insight. Feed your Gemini mind.",
  "Jul 13": "Your restlessness is tempered by emotional awareness. You're growing into a more complete version of yourself.",
  "Jul 14": "A childhood memory holds a clue to an adult pattern. Your analytical mind can decode it.",
  "Jul 15": "Halfway through July, emotional and intellectual streams merge. The result is unusually wise perspective.",
  "Jul 16": "Your nervous system benefits from water — a bath, swimming, or just listening to rain. Soothe the buzz.",
  "Jul 17": "Communication about feelings gets easier with practice. You're practicing right now. Keep going.",
  "Jul 18": "Your adaptability helps family dynamics more than anyone realizes. You adjust so others don't have to.",
  "Jul 19": "A piece of writing or a conversation captures exactly what you've been feeling. Language catches up to emotion.",
  "Jul 20": "Home doesn't have to be boring for Gemini. Make your space a haven for curiosity and comfort.",
  "Jul 21": "Your mind is a bridge between what people think and what they feel. Walk that bridge today.",
  "Jul 22": "Cancer season taught you emotional fluency. Carry that skill into the next season with pride.",
  "Jul 23": "Leo season ignites your creative confidence. Your ideas deserve an audience — find one.",
  "Jul 24": "Your playful side gets a solar boost. Create, perform, and express with unfiltered enthusiasm.",
  "Jul 25": "A creative collaboration sparks because two minds are always better — especially when one is yours.",
  "Jul 26": "Your words have dramatic flair today. Storytelling, presentations, or even casual chats become performances.",
  "Jul 27": "Romance lives in conversation for you. The person who captivates your mind captures your heart.",
  "Jul 28": "Your mental agility in creative problem-solving impresses someone important today.",
  "Jul 29": "Children, play, and youthful energy recharge you. Embrace your eternal youthfulness.",
  "Jul 30": "Your ideas deserve the spotlight today. Pitch, present, or just share boldly. No dimming allowed.",
  "Jul 31": "July ends with creative and emotional growth intertwined. You're more whole than you were 31 days ago.",

  // ── August ──
  "Aug 1": "August fires up your communication with creative boldness. Say it louder and with more color.",
  "Aug 2": "A creative writing or speaking opportunity lands perfectly in your lap. You were made for this.",
  "Aug 3": "Your quick wit and Leo season's warmth combine into dazzling charisma. Light up every room.",
  "Aug 4": "Play is not procrastination — it's where genius lives. Give yourself permission to play today.",
  "Aug 5": "A child or young person has wisdom that your adult mind hasn't considered. Listen with wonder.",
  "Aug 6": "Romance and mental stimulation merge. The most attractive thing anyone can do for you is think out loud.",
  "Aug 7": "Your creative output today has unusual heart behind it. When Gemini adds feeling to thought, magic happens.",
  "Aug 8": "Dramatic self-expression isn't usually your style, but today, let the inner performer out.",
  "Aug 9": "A hobby or creative pursuit deserves professional-level attention today. You're better at it than you think.",
  "Aug 10": "Your ability to make complex ideas entertaining is peak today. Teach something through story.",
  "Aug 11": "Social energy is abundant. Every conversation is a potential collaboration or creative spark.",
  "Aug 12": "Your inner twins agree on something today. When that happens, nothing can stop you.",
  "Aug 13": "Laughter is your medicine and your method. Prescribe it generously today.",
  "Aug 14": "A bold communication move — publishing, posting, presenting — gets the response you hoped for.",
  "Aug 15": "Mid-August finds your mind refreshed and your creativity flowing. Harvest the ideas while they're ripe.",
  "Aug 16": "Your nervous energy transforms into excitement today. The buzz is productive — ride it.",
  "Aug 17": "A brief encounter with a stranger becomes surprisingly meaningful. You attract interesting people.",
  "Aug 18": "Your signature adaptability helps navigate an unexpected change that rattles everyone else.",
  "Aug 19": "Technology and creativity intersect today. A digital tool helps you express something perfectly.",
  "Aug 20": "The transition from fire to earth energy asks your air nature to ground. Find stability in routine.",
  "Aug 21": "Your summer of creative expression yields something tangible today. See the results of your ideas.",
  "Aug 22": "Capture the remaining Leo season energy in a creative project before things shift to practical Virgo.",
  "Aug 23": "Virgo season begins. Your ruler Mercury is active — communication gets more precise and purposeful.",
  "Aug 24": "Detail orientation sharpens. Your usually broad strokes gain fine lines. Precision suits you today.",
  "Aug 25": "Health communication — with your body, your doctor, or your wellness routine — is favored.",
  "Aug 26": "Your mind craves order today. Organize your thoughts, your desk, your digital life.",
  "Aug 27": "A practical skill set upgrades when you apply your learner's mind to improvement.",
  "Aug 28": "Your nervous system responds to healthy routines. Structure supports freedom — paradoxically.",
  "Aug 29": "Analytical Mercury energy helps you see through confusion with crystal clarity. Trust your analysis.",
  "Aug 30": "A helpful communication — instructions, advice, or information — genuinely improves someone's day.",
  "Aug 31": "August ends with mental sharpness and creative momentum in perfect harmony. Well played, Gemini.",

  // ── September ──
  "Sep 1": "September focuses your fleet mind. Let precision guide your communication today.",
  "Sep 2": "Your Mercury ruler shines in Virgo. Your thinking is both fast and accurate. A rare combination.",
  "Sep 3": "Health habits stick when your curious mind understands the why behind them. Research today, commit tomorrow.",
  "Sep 4": "Your work benefits from your ability to process and relay information quickly. Be the team's brain.",
  "Sep 5": "A daily routine adjustment — small but smart — creates ripple effects you'll feel for weeks.",
  "Sep 6": "Your communication becomes more refined. Fewer words, more impact. Quality over quantity.",
  "Sep 7": "An organizational system finally works because you designed it for your unique brain. Custom solutions win.",
  "Sep 8": "Mercury sharpens your critical eye. Edit, revise, and polish — your first draft was good; your second is great.",
  "Sep 9": "Your body is giving you data. Listen to it with the same attention you give interesting articles.",
  "Sep 10": "Helping others articulate their thoughts is a Gemini superpower. Use it generously today.",
  "Sep 11": "Your words create bridges between grief and hope. Speak with care and intention.",
  "Sep 12": "A skill-building exercise engages your happiest self. Learning in service of mastery is pure Gemini joy.",
  "Sep 13": "Your mind finds patterns where others see chaos. That pattern-recognition is valuable today.",
  "Sep 14": "The difference between gossip and information is intention. Keep yours positive.",
  "Sep 15": "Your cognitive flexibility is an asset in problem-solving. Approach the challenge from three angles.",
  "Sep 16": "A written piece — journal, blog, report — comes together beautifully with today's precise energy.",
  "Sep 17": "Your service-oriented side emerges. Help through communication: teach, explain, clarify.",
  "Sep 18": "Brain food matters: omega-3s, berries, sleep. Your extraordinary mind deserves top-tier fuel.",
  "Sep 19": "A neighbor, coworker, or acquaintance says something that sticks. Pay attention to passing wisdom.",
  "Sep 20": "Your daily communications — texts, emails, casual chats — carry more weight than you realize. Be intentional.",
  "Sep 21": "Autumn whispers of change, and your air nature catches every breeze. Something new is coming.",
  "Sep 22": "Libra season activates your fellow air sign energy. Socializing, aesthetics, and balance align.",
  "Sep 23": "Your charm and wit create harmony in tense situations. Be the peacemaker with a punchline.",
  "Sep 24": "Partnerships — romantic and creative — thrive on Gemini communication now. Talk it through together.",
  "Sep 25": "Beauty and intellect merge today. Appreciate art, design, or architecture with your analytical eye.",
  "Sep 26": "A diplomatic conversation you've been dreading goes surprisingly well. Your words were perfectly chosen.",
  "Sep 27": "Social energy harmonizes with your natural gregariousness. This is your element — enjoy it.",
  "Sep 28": "Two people need connecting, and you're the natural bridge. Make the introduction.",
  "Sep 29": "Your mental flexibility helps you see both sides of a debate. In Libra season, that's gold.",
  "Sep 30": "September's lessons land: precision, health, and service give your brilliance a meaningful direction.",

  // ── October ──
  "Oct 1": "October sharpens your perception. Your air sign mind picks up on what's unspoken today.",
  "Oct 2": "A creative partnership flourishes through honest, balanced communication. Say your truth.",
  "Oct 3": "Your social calendar fills up. Choose wisely — energy spent on boring conversations is energy lost.",
  "Oct 4": "Aesthetic decisions come naturally when your intellect and taste collaborate. Trust your eye.",
  "Oct 5": "An important conversation about fairness or justice needs your articulate perspective.",
  "Oct 6": "Your words create beauty today — a well-turned phrase, a perfectly timed joke, an elegant email.",
  "Oct 7": "Balance in communication: listen exactly as much as you speak. The ratio matters today.",
  "Oct 8": "A negotiation or discussion benefits from your ability to hold multiple viewpoints simultaneously.",
  "Oct 9": "Your curiosity about people makes you an excellent interviewer. Ask the question no one else thinks to ask.",
  "Oct 10": "Romance lives in your mind first. Today, intellectual intimacy matters more than physical.",
  "Oct 11": "A short trip or local experience brings unexpected magic. Stay open to detours.",
  "Oct 12": "Your adaptability smooths a group dynamic that was getting tense. You're the social lubricant.",
  "Oct 13": "A great conversation today — the kind that lasts hours and makes you forget time. Savor it.",
  "Oct 14": "Your twin nature helps you understand coupled energy during Libra season. Partnership teaches you about yourself.",
  "Oct 15": "Your mind races with ideas for partnerships, collaborations, and creative unions. Follow the most exciting one.",
  "Oct 16": "Words heal today. Say something kind to someone who looks like they need it. Your timing will be perfect.",
  "Oct 17": "Air sign solidarity: Gemini, Libra, and Aquarius energy creates a triangle of brilliance. Connect with fellow air signs.",
  "Oct 18": "Your capacity for light in dark times is genuine strength. The world needs your levity right now.",
  "Oct 19": "A book or conversation about psychology, philosophy, or mystery captivates you after hours.",
  "Oct 20": "Your mental energy shifts toward depth as the season transitions. Let your thoughts go underground.",
  "Oct 21": "Transformation energy approaches. Your flexible nature adapts to intensity better than you'd expect.",
  "Oct 22": "Scorpio season begins. Deep waters for an air sign — but depth adds dimension to your brilliance.",
  "Oct 23": "A secret or hidden truth surfaces in conversation. Your role: listen without judgment.",
  "Oct 24": "Your usually light touch encounters heavy topics. Let them land. Depth won't drown you — it'll grow you.",
  "Oct 25": "Research and investigation engage your detective brain. Dig into something mysterious.",
  "Oct 26": "Communication about shared resources, intimacy, or vulnerability requires care. Measure twice, speak once.",
  "Oct 27": "Your mind processes intensity through writing. Journal the thoughts that are too heavy for conversation.",
  "Oct 28": "A financial conversation benefits from your analytical clarity and ability to see all options.",
  "Oct 29": "Your adaptability shines in emotionally charged environments. You adjust without losing yourself.",
  "Oct 30": "Mystery and intellect intersect. Your restless mind loves a good puzzle — lean into the unknown.",
  "Oct 31": "Your trickster spirit thrives on this liminal night. Play in the space between worlds.",

  // ── November ──
  "Nov 1": "November asks for fewer words and deeper meaning. Quality communication over quantity.",
  "Nov 2": "A conversation about loss, memory, or legacy reveals unexpected wisdom. Let it speak through you.",
  "Nov 3": "Your mental agility navigates emotional depth today. Think while feeling; feel while thinking.",
  "Nov 4": "Shared resources or investments benefit from your analytical eye. Crunch the numbers with someone.",
  "Nov 5": "Your curiosity about human nature goes deeper today. What motivates people? What frightens them? Explore.",
  "Nov 6": "Your words carry transformative power today. Choose them like a surgeon chooses instruments.",
  "Nov 7": "A piece of information you stumble on changes your understanding of something important.",
  "Nov 8": "Your usually breezy communication style gains weight and gravitas. People hear you differently today.",
  "Nov 9": "Emotional honesty feels foreign but necessary. Say the vulnerable thing. It won't break you.",
  "Nov 10": "Research into psychology, mystery, or the occult fascinates your inexhaustible mind.",
  "Nov 11": "Your words honor those who've sacrificed. Communication can be a memorial, a prayer, a tribute.",
  "Nov 12": "A trusted person shares something that deepens your bond permanently. Depth creates loyalty.",
  "Nov 13": "Your air sign nature learns to breathe underwater this Scorpio season. The skill stays with you forever.",
  "Nov 14": "Financial clarity arrives through careful analysis — your forte when combined with emotional intelligence.",
  "Nov 15": "Midmonth transformation: your communication has changed this season. More honest, more brave, more real.",
  "Nov 16": "Your twin selves integrate the light and shadow of human experience. Wholeness is the goal.",
  "Nov 17": "A written piece — journal, letter, or post — achieves unusual emotional truthfulness. Let it breathe.",
  "Nov 18": "Intimacy through conversation. Words, whispered or typed, create bridges to another soul.",
  "Nov 19": "Your intellectual courage matches your emotional growth this month. You're becoming multidimensional.",
  "Nov 20": "Release a belief that no longer serves you. Your flexible mind excels at this — let it go.",
  "Nov 21": "Sagittarius season arrives. Your opposite sign's energy teaches through contrast. Embrace big-picture thinking.",
  "Nov 22": "Adventure and philosophy expand your already boundless mind. Think wider, not just faster.",
  "Nov 23": "Travel — physical or mental — to distant places or ideas enriches you enormously.",
  "Nov 24": "Gratitude expressed in your own clever, heartfelt way means more than generic sentiments.",
  "Nov 25": "A philosophical or spiritual conversation opens a door in your mind that stays open.",
  "Nov 26": "Your natural gift for language helps bridge cultural or generational gaps today.",
  "Nov 27": "Learning about a foreign culture, belief system, or discipline delights your curious mind.",
  "Nov 28": "Your opposite sign's fire warms your air. When Gemini and Sagittarius energy combines, wisdom is born.",
  "Nov 29": "A publication, broadcast, or educational opportunity aligns with your communicative gifts.",
  "Nov 30": "November ends with your mind expanded and deepened. You've grown in ways you can't yet see.",

  // ── December ──
  "Dec 1": "December's expansive energy gives your ideas a philosophical frame. Think not just cleverly, but wisely.",
  "Dec 2": "Your words carry holiday warmth. A card, message, or toast from Gemini lights up the season.",
  "Dec 3": "Learning about traditions different from your own enriches your understanding of humanity. Stay curious.",
  "Dec 4": "A conversation about meaning, purpose, or belief stretches your mind in the best direction.",
  "Dec 5": "Your social gifts make you the connector at holiday gatherings. Introduce strangers; create sparks.",
  "Dec 6": "Travel energy is high. Your restless spirit finds peace in movement — plan or embark.",
  "Dec 7": "A year-end reflection reveals how much your thinking has evolved. You're not the same mind you were in January.",
  "Dec 8": "Your gift-giving superpower: you remember the random thing someone mentioned months ago. That's love.",
  "Dec 9": "A distant friend or far-flung connection reaches out. Your social web spans wider than you realize.",
  "Dec 10": "Your mind craves meaning alongside information this December. Wisdom over data today.",
  "Dec 11": "Holiday parties are your stage. Your wit, charm, and storytelling make you unforgettable tonight.",
  "Dec 12": "A foreign language, cuisine, or art form sparks new neural pathways. Feed the learning addiction.",
  "Dec 13": "Your duality is your holiday secret: you can be both the life of the party and the one who craves quiet.",
  "Dec 14": "A meaningful book makes the perfect gift and the perfect escape. Give one, read one.",
  "Dec 15": "Year in review for your mind: what did you learn, read, write, say, and think that mattered most?",
  "Dec 16": "Your adaptability makes you the easiest houseguest, travel companion, and holiday partner. That's rare.",
  "Dec 17": "A heartfelt conversation at a holiday gathering surprises you with its depth. You went there. Good.",
  "Dec 18": "Write a letter to your future self. Your January Gemini will love hearing from December's wiser twin.",
  "Dec 19": "The year's communication highlight reel is impressive. You connected, explained, and enchanted through words.",
  "Dec 20": "Your holiday wish is simple: interesting people, fascinating conversations, and a stack of new books.",
  "Dec 21": "Winter solstice. In the darkness, let your quicksilver mind rest. Even mercury needs to settle sometimes.",
  "Dec 22": "Capricorn season grounds your flighty nature. Structure and ambition give your ideas an engine.",
  "Dec 23": "Year-end planning energizes. Your lists, goals, and ideas for next year fill notebooks and notes apps.",
  "Dec 24": "Tonight, presence over presents. Your full, undistracted attention is the greatest gift you can offer.",
  "Dec 25": "Words of love spoken today carry extra magic. Say them — out loud, in writing, through the air.",
  "Dec 26": "Post-holiday quiet is golden for your overstimulated brain. Read, rest, recharge.",
  "Dec 27": "Your new year plans are already taking shape. Multiple ideas compete — hold them all loosely for now.",
  "Dec 28": "A phone call or message to someone you haven't spoken to in too long reconnects you beautifully.",
  "Dec 29": "Your year-end words matter. Acknowledge, appreciate, and articulate your gratitude.",
  "Dec 30": "Tomorrow the year ends. Today, let your twin selves agree: it was a hell of a ride.",
  "Dec 31": "The year closes and your mind is already racing toward what's next. That's not just Gemini nature — it's genius.",
};
