/** 365 daily quotes for Leo — one for every day of the year. */
export const leoDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new stage. Set intentions that honor your need for recognition AND authentic self-expression.",
  "Jan 2": "Your inner fire knows what this year requires: courage, creativity, and unshakable confidence. Light the first spark.",
  "Jan 3": "Morning rituals should feel regal. Start the day in a way that reminds you of your worth.",
  "Jan 4": "Your personal space should reflect your grandeur. Add something bold and beautiful to your environment today.",
  "Jan 5": "Someone needs your warmth today. Your natural generosity can transform a cold moment into a golden one.",
  "Jan 6": "The sun never apologizes for shining. Neither should you. Let your full radiance show today.",
  "Jan 7": "Leadership begins with self-mastery. Before directing others, direct your own energy with intention.",
  "Jan 8": "Your pride can be armor or a cage. Today, let it be a crown — worn lightly and with grace.",
  "Jan 9": "Financial boldness balanced with wisdom creates the kingdom you're building. One strategic move today.",
  "Jan 10": "Your creative fire simmers even in winter. Feed it, even if it's just a sketch, a song, or a bold idea.",
  "Jan 11": "The spotlight isn't a destination — it's your natural habitat. Step into it without guilt.",
  "Jan 12": "Your loyalty is legendary and deserves to be reciprocated. Assess who truly honors your devotion.",
  "Jan 13": "Warmth radiates from your core. Even on the coldest day, you are the sun in someone's sky.",
  "Jan 14": "Your dramatic flair isn't excessive — it's expressive. The world needs more color, more passion, more YOU.",
  "Jan 15": "Midmonth calls for bold self-assessment. Where are you playing small? The lion doesn't tiptoe.",
  "Jan 16": "Your heart is gold — literally and metaphorically. Guard it from those who take without giving.",
  "Jan 17": "A creative project deserves your signature courage. Make it unmistakably yours.",
  "Jan 18": "Self-expression through fashion, art, or words makes you feel alive. Dress your truth today.",
  "Jan 19": "Your roar can comfort as much as it commands. Use your powerful voice to reassure someone today.",
  "Jan 20": "A fixed sign's determination shines today. Once you set your mind, nothing moves you. Set it wisely.",
  "Jan 21": "Something brewing in your creative spirit will demand full expression soon. Let it build.",
  "Jan 22": "Your generous nature is a gift to the world, but the most important generosity is toward yourself.",
  "Jan 23": "The stage of your life — personal or professional — deserves a performance worthy of your talent.",
  "Jan 24": "A childhood dream still pulses in your heart. Don't dismiss it as nostalgia — it's direction.",
  "Jan 25": "Your warmth melts resistance. Today, use your sunny disposition to open a door that's been closed.",
  "Jan 26": "Financial confidence comes from knowing your worth AND managing your resources. Attend to both.",
  "Jan 27": "Luxury isn't vanity for you — it's self-respect. Treat yourself to something that makes you feel regal.",
  "Jan 28": "Your fixed nature means some days you burn bright and some you burn steady. Both are powerful.",
  "Jan 29": "An act of extraordinary generosity today fills your heart more than it costs your wallet.",
  "Jan 30": "Entertainment, joy, and laughter aren't frivolous — they're essential Leo fuel. Play tonight.",
  "Jan 31": "January ends with your fire burning steady. You've remembered who you are: the one who shines.",

  // ── February ──
  "Feb 1": "February stirs your romantic heart. Love should be grand, passionate, and worthy of your devotion.",
  "Feb 2": "Your intuition about who truly admires you versus who merely flatters you sharpens today.",
  "Feb 3": "A creative explosion wants out. Give it a canvas, a stage, a page — anything. Just let it roar.",
  "Feb 4": "Your personal throne — wherever you sit most — should feel magnificent. Elevate your daily seat of power.",
  "Feb 5": "Confidence without arrogance is your superpower when you're aligned. Find that sweet spot today.",
  "Feb 6": "Your fire sign nature craves movement and warmth. Dance, exercise, or simply bask in sunlight.",
  "Feb 7": "Someone looks to you for strength today. Your presence alone reassures them. Show up fully.",
  "Feb 8": "Your creative inner child demands attention. Finger-paint, sing badly, dance wildly — give them joy.",
  "Feb 9": "Drama is your art form when conscious, your downfall when unconscious. Choose the art today.",
  "Feb 10": "Your radiance attracts people. Today, be intentional about which connections you invest in.",
  "Feb 11": "Mementos of triumphs — awards, photos, memories — aren't vanity. They're your victory gallery.",
  "Feb 12": "Your love language is adoration — giving and receiving. Today, be generous with genuine compliments.",
  "Feb 13": "Pre-Valentine: your idea of romance involves grand gestures, passionate declarations, and theatrical love. That's beautiful.",
  "Feb 14": "Love is your kingdom's greatest treasure. Today, rule with an open heart and fearless devotion.",
  "Feb 15": "After the intensity of love's spotlight, rest your heart with quiet pride in how deeply you feel.",
  "Feb 16": "Your connection to the sun guides your vitality. Seek genuine warmth — physical and emotional.",
  "Feb 17": "A creative tradition or ritual you've established carries your unique signature. Honor it.",
  "Feb 18": "Your passion is your compass. What sets you on fire points you toward your purpose.",
  "Feb 19": "Pride can either elevate or isolate. Check: is yours building bridges or burning them?",
  "Feb 20": "Emotional honesty in love requires the courage of a lion. Be brave enough to be tender.",
  "Feb 21": "Your dream life reflects your waking desires: recognition, love, and creative fulfillment.",
  "Feb 22": "Confidence built on authenticity, not performance, is the kind that never fades.",
  "Feb 23": "A child or creative project reminds you why joy matters more than perfection.",
  "Feb 24": "Your moods run hot, not heavy. When frustration flares, channel it into creative combustion.",
  "Feb 25": "Your fixed loyalty means you hold on sometimes longer than you should. Know when to release with dignity.",
  "Feb 26": "A bold outfit, a vivid color, or a statement piece lifts your entire spirit today.",
  "Feb 27": "Your ability to hold both vulnerability and strength is uniquely Leo. The bravest thing is being real.",
  "Feb 28": "February taught you about the courage of loving fully. Your generous heart is your crown.",
  "Feb 29": "Rare day, rare fire. Let the extra day be for something daring you'd never usually try.",

  // ── March ──
  "Mar 1": "Spring stirs your creative restlessness. Start a project that lets your talents roar.",
  "Mar 2": "Your creative instincts guide a decision today. Trust the fire in your belly over the calculator on your desk.",
  "Mar 3": "Pour into your own cup before filling everyone else's with sunshine. Even the sun rests each night.",
  "Mar 4": "Your magnetic energy today draws opportunities toward you. Stand tall and receive them.",
  "Mar 5": "Dramatic self-expression saves you from burnout. Perform, create, or simply narrate your life with flair.",
  "Mar 6": "Your chosen audience — the people who see you fully — deserve a standing ovation of gratitude.",
  "Mar 7": "The performing arts, live music, or theatre feeds your soul tonight. Experience someone else's spotlight.",
  "Mar 8": "Your leadership shows in how you lift others, not just how you shine yourself. Elevate someone today.",
  "Mar 9": "A grand gesture — writing a love letter, planning a surprise — fills your heart with purpose.",
  "Mar 10": "Your environment reflects your inner state. If it looks dull, add something that makes your heart race.",
  "Mar 11": "Vulnerability in a safe relationship builds the worship you secretly crave. Be real, not perfect.",
  "Mar 12": "Your lion nature knows: sometimes a direct charge gets you further than strategy. Be bold today.",
  "Mar 13": "Sunlight is your elixir. Even 15 minutes of warm rays recalibrates your entire being.",
  "Mar 14": "Your love of celebration isn't superficial. It's how you honor life's preciousness.",
  "Mar 15": "Feeding your creative fire is as important as eating. Starve neither your body nor your art.",
  "Mar 16": "An audience — even an audience of one — energizes your performance. Find your witness today.",
  "Mar 17": "Your luck comes through boldness, not caution. Fortune favors the courageous lion.",
  "Mar 18": "Your dream life includes stages, crowns, and standing ovations. Those aren't fantasies — they're blueprints.",
  "Mar 19": "Spring awakening meets your fire nature. The world is about to see you bloom in full color.",
  "Mar 20": "Spring equinox. Rebirth energy ignites your creative flame. Plant seeds of artistic intention.",
  "Mar 21": "Aries season fuels your fellow fire nature. Energy, courage, and initiative multiply. Charge forward.",
  "Mar 22": "Your ambition doesn't need permission. It's as natural as your mane blowing in the wind.",
  "Mar 23": "A bold career move fueled by creative confidence puts you ahead. Your uniqueness IS your edge.",
  "Mar 24": "Public attention feels like oxygen. Breathe it in today — you've earned the spotlight.",
  "Mar 25": "Your authentic self and your stage self are the same person at different volumes. Turn it up.",
  "Mar 26": "Authority comes naturally when people admire your courage. Lead through inspiration today.",
  "Mar 27": "Your fear of being ignored is real, but your light is impossible to miss. Keep shining.",
  "Mar 28": "A professional opportunity benefits from your charismatic warmth. Be your brilliant self.",
  "Mar 29": "Ambition and generosity aren't opposites. Build your empire while lifting others along.",
  "Mar 30": "Your public presence today should radiate confidence and warmth. The world is watching.",
  "Mar 31": "March ends with your creative fire burning brighter. Spring was made for lions.",

  // ── April ──
  "Apr 1": "Playfulness is your birthright. Jokes, theatrics, and wholehearted silliness are Leo-approved today.",
  "Apr 2": "Your social charisma attracts a crowd today. Enjoy every admiring glance and conversation.",
  "Apr 3": "A friendship deepens when you let them see the real you — not just the performance.",
  "Apr 4": "Group dynamics reveal your natural role: center stage, the one everyone orbits. Shine responsibly.",
  "Apr 5": "Your wish for the future includes creative recognition and passionate love. Dream theatrically.",
  "Apr 6": "Social energy surges. Your warmth creates the atmosphere others want to be part of.",
  "Apr 7": "A cause or community effort that lets you lead and inspire deserves your energy today.",
  "Apr 8": "Your friends are your audience AND your family. Today, make them feel like stars too.",
  "Apr 9": "An innovative creative idea surfaces. Trust it — your vision is often ahead of its time.",
  "Apr 10": "Your protective instincts for those you love rival a lion's ferocity. Defend what matters.",
  "Apr 11": "Spring blooms mirror your outward expansion. You're becoming more visible, more magnetic.",
  "Apr 12": "Group settings energize you when you're valued. Curate your circle for mutual admiration.",
  "Apr 13": "A dream or vision for the future crystallizes through creative confidence, not timid planning.",
  "Apr 14": "Your humanitarian side shows when you use your spotlight to illuminate others' causes.",
  "Apr 15": "Financial planning should include creative investments. Fund your art, your joy, your passion.",
  "Apr 16": "Your read on group dynamics prevents unnecessary drama. Your leadership prevents conflict before it starts.",
  "Apr 17": "The sun set tonight is a love letter from your ruling star. Watch it and feel claimed.",
  "Apr 18": "Your need for attention battles your need for authenticity today. Choose authenticity — it attracts more.",
  "Apr 19": "Taurus season approaches. Earth energy grounds your fire beautifully, adding substance to your sparkle.",
  "Apr 20": "Your fiery passion meets grounded sensuality. A perfect day for luxury and pleasure.",
  "Apr 21": "Indulge in something that makes all five senses feel regal. You deserve the finest.",
  "Apr 22": "Earth Day connects your fire to the ground that feeds it. Nature recharges your solar battery.",
  "Apr 23": "Your generous hosting nature turns any meal into a banquet and any room into a palace.",
  "Apr 24": "Material beauty isn't superficial for a Leo — it's self-expression. Invest in quality you love.",
  "Apr 25": "Sensory pleasure feeds your creative spirit. Music, fragrance, silk — surround yourself with the exquisite.",
  "Apr 26": "Your patience with a creative process pays off. The masterpiece takes time — even for a prodigy.",
  "Apr 27": "A treasured possession tells the story of a triumph. Display it proudly.",
  "Apr 28": "Your garden — real or metaphorical — flourishes under your magnificent attention. What's growing?",
  "Apr 29": "Evening entertainment is non-negotiable. Watch something, perform something, or create something joyful.",
  "Apr 30": "April ends with your creative confidence soaring. You've given generously and sparkled brilliantly.",

  // ── May ──
  "May 1": "May brings sensory richness that feeds your fire. Beauty, pleasure, and romance are your fuel.",
  "May 2": "Your body expresses joy through movement. Dance, stretch, or stride with the confidence of royalty.",
  "May 3": "Your warmth transforms an ordinary day into a celebration. Never underestimate your golden touch.",
  "May 4": "Financial confidence grows through bold but wise investments. Build your treasury, your majesty.",
  "May 5": "Your space needs something that sparkles, gleams, or glows. Your environment should match your energy.",
  "May 6": "Past victories remind you who you are. Revisit a proud moment and carry that energy forward.",
  "May 7": "A celebratory meal — lavish, colorful, and shared — is your idea of heaven. Create one tonight.",
  "May 8": "Your creative reserves are overflowing. Channel the excess into a passion project before it combusts.",
  "May 9": "Your body craves vitality-boosting foods: vibrant colors, bold flavors, and energizing ingredients.",
  "May 10": "Your nurturing style is empowering, not coddling. You raise people up by believing in them fiercely.",
  "May 11": "Traditions of celebration — birthdays, victories, milestones — matter deeply to you. Start one today.",
  "May 12": "Your presence commands attention not through volume but through authentic charisma. Walk in boldly.",
  "May 13": "A space improvement that adds drama — a statement wall, bold art, gold accents — lifts your spirits.",
  "May 14": "Love expressed through play, passion, and celebration speaks louder than solemn devotion.",
  "May 15": "Your emotional intelligence helps you lead with heart, not just authority. The crown fits because you care.",
  "May 16": "Sunlight recharges your solar batteries. Get outside and soak in your ruling star's energy.",
  "May 17": "A treasured award, photo, or symbol of achievement isn't vanity — it's motivation. Display it.",
  "May 18": "Your fear of mediocrity pushes you to excellence. Let it drive you, not paralyze you.",
  "May 19": "Evening glamour — dressing up for dinner, lighting candles, setting a beautiful table — feeds your soul.",
  "May 20": "Your handmade or personally chosen gifts carry the warmth of your generous heart.",
  "May 21": "Gemini season begins. Mental agility helps you articulate your vision with charm and wit.",
  "May 22": "Your creative vision meets communicative clarity. Pitch your ideas with confidence today.",
  "May 23": "A conversation about your dreams goes brilliantly. Words capture your passion perfectly.",
  "May 24": "Your generous nature finds verbal expression. Praise, encourage, and uplift with words today.",
  "May 25": "Social energy pulls you magnificently into the spotlight. Short but dazzling appearances recharge you.",
  "May 26": "Your storytelling skills make you the center of every gathering. Tell a tale that moves hearts.",
  "May 27": "Learning about creative expression, leadership, or performance arts feeds your soul today.",
  "May 28": "Networking with fellow creatives sparks new collaborations. Your fire ignites others.",
  "May 29": "Your dreams lately have been showing you a stage you haven't stepped onto yet. Prepare.",
  "May 30": "Movement with flair — dance, performance, or simply walking with presence — elevates your fire spirit.",
  "May 31": "May ends with your creative voice stronger and clearer. The world is ready for your next act.",

  // ── June ──
  "Jun 1": "June brightens your already-golden energy. Summer is your element's natural season.",
  "Jun 2": "Your verbal charisma deepens. Every word carries warmth that makes people lean closer.",
  "Jun 3": "An idea about creative expression, entertainment, or leadership crystallizes. Write it in gold.",
  "Jun 4": "Your curiosity about what makes people admire and follow reveals the psychology of charisma.",
  "Jun 5": "Short adventures or local explorations let your playful side roam. Explore like a cub.",
  "Jun 6": "A conversation with a creative ally reveals shared ambitions. Collaborate with mutual admiration.",
  "Jun 7": "Your hands create beauty today — visual art, styled outfits, or a gorgeously plated meal.",
  "Jun 8": "Pre-season fire builds. Your sign's season is approaching, and your glow already intensifies.",
  "Jun 9": "Gracious communication heals a rift. Your warmth can thaw any cold shoulder.",
  "Jun 10": "Your heart and head align today. Passion and strategy point in the same direction. Charge.",
  "Jun 11": "A book or film about a legendary figure inspires your own sense of destiny.",
  "Jun 12": "Your evening routine should feel ceremonial. You're royalty preparing for rest, not just going to bed.",
  "Jun 13": "Anticipation builds as your season draws near. The world is about to feel your full brilliance.",
  "Jun 14": "Your connection to the sun intensifies as days lengthen. You're literally powered by longer light.",
  "Jun 15": "Halfway through the year, assess: are you living as boldly as you deserve? Adjust accordingly.",
  "Jun 16": "A feast you prepare or attend feeds more than bodies — it feeds community, connection, and joy.",
  "Jun 17": "Your fierce protectiveness of your creative vision isn't stubbornness — it's artistic integrity.",
  "Jun 18": "Golden hour sunlight was made for Leo selfies and self-celebration. You look magnificent.",
  "Jun 19": "Your season approaches. Can you feel the throne being dusted? The crown being polished?",
  "Jun 20": "Summer solstice eve. The longest light is your personal prelude. Tomorrow, the sun peaks — and so do you.",
  "Jun 21": "Summer solstice. Maximum sunlight. Maximum Leo power. You are the living embodiment of solar energy.",
  "Jun 22": "Cancer season begins. Water energy asks you to tend your emotional depths beneath the golden surface.",
  "Jun 23": "Home and heart matters demand attention. Your domestic space deserves royal treatment.",
  "Jun 24": "Emotional honesty with yourself, even when it's not glamorous, builds authentic confidence.",
  "Jun 25": "Nurture your inner child today. They don't need a stage — they need your love and acceptance.",
  "Jun 26": "Your protective instincts for loved ones emerge powerfully. Guard them with gentle ferocity.",
  "Jun 27": "Family appreciation during this season strengthens your roots so your branches can reach higher.",
  "Jun 28": "Your intuition about home and family matters is strong. Trust those quiet inner knowings.",
  "Jun 29": "A cozy evening restores the energy you pour out so generously. Rest is regal too.",
  "Jun 30": "June ends with emotional depth you didn't expect. Feeling deeply makes your future shine brighter.",

  // ── July ──
  "Jul 1": "July begins with your pre-season glow. The warmth inside you is about to become visible to all.",
  "Jul 2": "Emotional matters from Cancer season resolve beautifully, clearing the stage for your entrance.",
  "Jul 3": "Home celebrations prepare for the grand event: your season. Set the stage for your arrival.",
  "Jul 4": "Independence and self-expression blaze together. You are free, fierce, and unapologetically brilliant.",
  "Jul 5": "The countdown to Leo season accelerates. Your inner fire intensifies like a rising curtain.",
  "Jul 6": "Creative projects birthed now carry unusual golden light. Start something magnificent.",
  "Jul 7": "Your heart center activates memories of every time you were brave. You've always been the hero.",
  "Jul 8": "Trust your gut today. It has the instincts of a lion and the wisdom of a king.",
  "Jul 9": "Vulnerability before your season isn't weakness — it's the soft moment before the roar.",
  "Jul 10": "A bold creative intention set this week will bloom magnificently during your season.",
  "Jul 11": "Nurture your own dreams with the same fierce protection you give to those you love.",
  "Jul 12": "Your legacy — what you create and how you love — is forming right now. Shape it consciously.",
  "Jul 13": "Your emotional radar operates at high sensitivity. You feel everything — and it fuels your art.",
  "Jul 14": "Sunbathing, sunrises, or sunsets: your ruling star heals you with every golden ray. Soak it in.",
  "Jul 15": "Mid-July: your season is one week away. Can you feel the crown descending?",
  "Jul 16": "A creative project near completion carries your personal magic. Finish it with flourish.",
  "Jul 17": "Your space should feel like a palace as your season approaches. Add beauty and grandeur.",
  "Jul 18": "Financial investments in yourself — courses, tools, wardrobe — pay off during your season.",
  "Jul 19": "The approaching Leo energy concentrates your focus. What do you want your season to manifest?",
  "Jul 20": "Evening rituals should feel like preparations for coronation. You're about to reign.",
  "Jul 21": "Last day before your season. The quiet before the magnificent storm. Breathe and prepare.",
  "Jul 22": "LEO SEASON BEGINS! The sun enters your sign, and the cosmos crowns you. This is YOUR time.",
  "Jul 23": "Happy Leo season! Your cosmic birthday month activates maximum magnetism. The world orbits you.",
  "Jul 24": "Creative confidence peaks during your season. Make, perform, build, shine — everything turns to gold.",
  "Jul 25": "Your inner child dances in the spotlight. Let them — this is their birthday party too.",
  "Jul 26": "Romance blazes during your season. Love should be grand, passionate, and utterly unforgettable.",
  "Jul 27": "Your generosity during your season creates ripples of joy that extend far beyond your circle.",
  "Jul 28": "A heart-centered creative project during your season carries destiny energy. Give it everything.",
  "Jul 29": "The spotlight during your season isn't a privilege — it's your natural position. Own it completely.",
  "Jul 30": "Dramatic celebration of life, love, and creative fire defines your season. Celebrate EVERYTHING.",
  "Jul 31": "July ends with Leo season in full glory. You are the sun — warm, life-giving, and eternally bright.",

  // ── August ──
  "Aug 1": "August is Leo's peak month. Your power, confidence, and creative force reach maximum brilliance.",
  "Aug 2": "Birthday season energy amplifies everything: love, art, leadership, and your magnificent heart.",
  "Aug 3": "Your warmth is the climate everyone wants to live in. Radiate it without reservation.",
  "Aug 4": "Playful energy during your season transforms every activity into a celebration. Even errands become fun.",
  "Aug 5": "Joy and courage are siblings in your fiery heart. Today, let delight make you fearless.",
  "Aug 6": "Your creative brilliance makes you an irresistible collaborator. Share an idea with theatrical confidence.",
  "Aug 7": "Romance during your season demands grand gestures, passionate declarations, and legendary love.",
  "Aug 8": "8/8 — the Lion's Gate portal. Set the most magnificent intention you can imagine. The cosmos listens.",
  "Aug 9": "Your space becomes a gallery during your season. Display your art, your trophies, your joy.",
  "Aug 10": "Your heart is bolder than your fear every single day. That's why you're the sign of courage.",
  "Aug 11": "A creative risk during your season pays off spectacularly. Applause is headed your way.",
  "Aug 12": "Sunlight and celebration are your prescription for everything. Get both in abundance today.",
  "Aug 13": "Your devotion is your masterpiece. How you love is the most creative thing you'll ever do.",
  "Aug 14": "Summer's peak IS Leo's peak. You and the season are one golden, blazing force.",
  "Aug 15": "Mid-August is the climax of your power. Stand in it. Own it. The kingdom is yours.",
  "Aug 16": "A fellow creative or admirer gives you feedback that makes your heart roar with pride.",
  "Aug 17": "Your protective loyalty serves your kingdom well today. Defend what you've built with dignity.",
  "Aug 18": "Evening celebration — dinner, entertainment, and beloved company — is the perfect Leo night.",
  "Aug 19": "Your season's final days concentrate your fire. What intention do you seal before the curtain falls?",
  "Aug 20": "The shift toward late summer whispers of transition. Your fire doesn't dim — it matures.",
  "Aug 21": "Summer memories of joy, creativity, and love become your personal highlight reel. Savor them.",
  "Aug 22": "Your season's final bow. Take it with grace, pride, and the knowledge that you shone magnificently.",
  "Aug 23": "Virgo season begins. Earth refines your fire into something polished and purposeful.",
  "Aug 24": "Your grand vision meets meticulous execution. The details make the masterpiece.",
  "Aug 25": "Health and wellness routines support your solar vitality. Treat your body like the temple it is.",
  "Aug 26": "Your attention to craft and quality elevates your creative work from good to extraordinary.",
  "Aug 27": "Organizing your creative life — tools, schedules, resources — frees you to flow more beautifully.",
  "Aug 28": "A daily practice of creative expression keeps your fire burning steadily, not just in bursts.",
  "Aug 29": "Your service to others through your art, leadership, or warmth creates lasting impact.",
  "Aug 30": "Practical love — showing up consistently, following through, being reliable — is love in action.",
  "Aug 31": "August ends as your finest month. Your fire blazed, your heart loved, and your crown never slipped.",

  // ── September ──
  "Sep 1": "September channels your magnificent energy into refined, purposeful expression.",
  "Sep 2": "Health routines are the foundation of sustained brilliance. Tend your body with royal attention.",
  "Sep 3": "A creative workspace cleanse organizes your fire into productive channels. Clear the clutter.",
  "Sep 4": "Your generous spirit shows in daily acts: holding doors, genuine compliments, unexpected kindness.",
  "Sep 5": "A detail-oriented creative task reveals your perfectionist side. Excellence is your standard.",
  "Sep 6": "Your body tells you what it needs for peak performance. Eat like royalty — nourishing and vibrant.",
  "Sep 7": "Service through creative teaching or mentoring fulfills your Leo heart more than solo spotlights.",
  "Sep 8": "A health-focused adjustment boosts your solar energy. You burn brighter when your body is tended.",
  "Sep 9": "Daily creative rituals create the momentum that produces masterpieces. Practice today.",
  "Sep 10": "Meal preparation with artistry turns nutrition into an aesthetic experience. Plate beautifully.",
  "Sep 11": "Your warmth holds collective space with dignity today. Your strength comforts others.",
  "Sep 12": "A loyal companion — human, animal, or creative partner — reminds you what devotion looks like.",
  "Sep 13": "Organization that serves creativity, not stifles it, is the balance you're mastering.",
  "Sep 14": "Your creative health check: are you producing what you're proud of? Adjust to match your standards.",
  "Sep 15": "Practical self-care — exercise, nutrition, rest — is the foundation of your sustained radiance.",
  "Sep 16": "Your attention to a colleague or friend's potential helps them shine. Mirror for others what you see.",
  "Sep 17": "A routine change — a new creative medium, a different gym, a novel approach — refreshes your fire.",
  "Sep 18": "Your creative space should inspire magnificence. Add one element today that says 'genius works here.'",
  "Sep 19": "Virgo season has polished your creative output. You're more precise and still brilliantly bold.",
  "Sep 20": "A practical accomplishment brings the satisfaction that flashy gestures sometimes miss.",
  "Sep 21": "Autumn signals a shift from external performance to internal cultivation. Both fuel your fire.",
  "Sep 22": "Libra season begins. Partnerships and harmony activate your generous, romantic heart.",
  "Sep 23": "Balance in relationships means sharing the spotlight. Can you applaud as loudly as you perform?",
  "Sep 24": "Your collaborative creativity produces something neither of you could alone. Partner magnificently.",
  "Sep 25": "Fairness in love means your partner's spotlight matters too. Co-star gracefully today.",
  "Sep 26": "Beauty feeds your creative soul. Art exhibits, gorgeous music, or a stunning sunset — consume beauty.",
  "Sep 27": "Your diplomatic side emerges when you lead with love rather than authority.",
  "Sep 28": "Appreciation from a partner touches the part of you that craves being truly seen. Receive it.",
  "Sep 29": "Balance between leading and following is this season's lesson. True power knows when to yield.",
  "Sep 30": "September refined your brilliance into something sustainable. You shine steadily now, not just spectacularly.",

  // ── October ──
  "Oct 1": "October adds depth and intensity to your golden fire. Surface sparkle meets soul-level power.",
  "Oct 2": "Your relationships enter a more honest phase. Real love doesn't need performance. It needs presence.",
  "Oct 3": "A beautiful artistic or social scene fills your heart with the appreciation you thrive on.",
  "Oct 4": "Your aesthetic of drama and grandeur becomes your calling card. People know your hallmark.",
  "Oct 5": "A partnership grows through shared creative ventures. Build something magnificent together.",
  "Oct 6": "Your ability to make any space feel warm and alive is a gift. Use it tonight.",
  "Oct 7": "Balance between self-expression and partnership: shine your light so it illuminates both of you.",
  "Oct 8": "Your warmth heals a cold connection. Your generous heart opens doors that pride had closed.",
  "Oct 9": "A beautifully staged evening — candles, music, loved ones, and excellent food — is your masterpiece.",
  "Oct 10": "Autumn's cooling doesn't dim your fire — it concentrates it. You burn more intensely, more purposefully.",
  "Oct 11": "A legacy project — something that outlasts you — deserves your attention and creative energy.",
  "Oct 12": "Your contribution to your community or family tradition shines with Leo gold. Be the torchbearer.",
  "Oct 13": "Warm, nourishing cooking shared with people you love is a royal feast, however simple the menu.",
  "Oct 14": "A creative block releases when you remember: perfection isn't the goal. Self-expression is.",
  "Oct 15": "Your creative courage builds throughout autumn. What feels too bold is often exactly right.",
  "Oct 16": "A gift crafted by your hands or heart carries your unique radiance. Give it to someone who'll treasure it.",
  "Oct 17": "Your space during autumn should feel like a warm, golden retreat. Amber light, rich textures, warmth.",
  "Oct 18": "Your partnership skills strengthen through the practice of shared joy and mutual celebration.",
  "Oct 19": "Evening gratitude for your creative gifts and your golden heart warms you from within.",
  "Oct 20": "Depth energy approaches as Scorpio season draws near. Prepare for intensity beneath the sparkle.",
  "Oct 21": "A shared creative project reveals layers of your collaboration. Something beautiful deepens.",
  "Oct 22": "Scorpio season begins. Transformation energy asks you to let some of your fire become internal torch.",
  "Oct 23": "Deep creative truth surfaces. The art that comes from your depths is more powerful than surface polish.",
  "Oct 24": "An emotional truth about your need for validation emerges. Look at it honestly, with courage.",
  "Oct 25": "Your intuition about what's real versus what's performance intensifies. Trust your deeper knowing.",
  "Oct 26": "Intimacy deepens when you remove the crown and let someone see the human underneath.",
  "Oct 27": "Financial or shared creative investments benefit from your heart-centered decision-making.",
  "Oct 28": "Your capacity for emotional transformation equals your capacity for dramatic reinvention. They're connected.",
  "Oct 29": "The depth beneath your golden surface is where true power lives. Go there tonight.",
  "Oct 30": "Creative transformation isn't one blockbuster — it's thousands of brave vulnerable moments.",
  "Oct 31": "Your costume tonight should channel your most powerful self. Dress as the legend you're becoming.",

  // ── November ──
  "Nov 1": "November reveals the courage beneath the charisma. Your fire now burns from deep within.",
  "Nov 2": "Honor those who believed in your light when you couldn't see it yourself. Their faith shaped your fire.",
  "Nov 3": "An emotional purge through creative expression — painting, writing, performing — releases what's heavy.",
  "Nov 4": "Shared resources and creative collaborations benefit from your generous but discerning energy.",
  "Nov 5": "Your trust, once earned, is unwavering. Give it today to someone whose loyalty matches your own.",
  "Nov 6": "Vulnerability without an audience is the bravest performance of all. Be real in private today.",
  "Nov 7": "Your resilience surprises even you. Fire doesn't just burn — it forges. You've been forged beautifully.",
  "Nov 8": "A creative or personal matter requires your bravest honesty. Speak from your magnificent heart.",
  "Nov 9": "Creative dreams carry messages about your deepest artistic desires. Follow their golden thread.",
  "Nov 10": "A transformation in creative identity ripples into every area of your life. Reinvent gloriously.",
  "Nov 11": "Remember with pride. Your contributions to others' lives burn brightly in their memories.",
  "Nov 12": "Financial confidence built through wise generosity — knowing when to invest and when to withdraw.",
  "Nov 13": "Your creative process during Scorpio season produces depth you didn't know you had. Trust it.",
  "Nov 14": "Boundaries protect your creative fire from those who would use your warmth without reciprocating.",
  "Nov 15": "Halfway through November, your creative transformation is visible. Something deeper shines through.",
  "Nov 16": "Your capacity for holding creative space — incubating ideas, being patient — grows stronger.",
  "Nov 17": "A creative secret or private project generates power through its hiddenness. Not everything needs a stage.",
  "Nov 18": "Transition toward fire season brings your outward energy back. Prepare for expansion.",
  "Nov 19": "A challenging creative conversation reaches resolution through your courageous emotional honesty.",
  "Nov 20": "Release the old creative identity to make room for the brilliant new one emerging.",
  "Nov 21": "Sagittarius season begins! Fellow fire energy ignites your spirit with adventure and philosophy.",
  "Nov 22": "Travel, exploration, and broad horizons call to your adventurous heart. Expand your kingdom.",
  "Nov 23": "Gratitude for your manifold gifts flows powerfully today. Count your creative blessings.",
  "Nov 24": "Your hosting during holidays turns gatherings into legendary events. Orchestrate joy.",
  "Nov 25": "Traditions you establish become the stuff of family legend. Your celebrations are unforgettable.",
  "Nov 26": "Your generous spirit gets philosophical today. Why do you shine so brightly? Because darkness needs your light.",
  "Nov 27": "Adventure doesn't always mean travel. A new creative medium, cuisine, or philosophy expands you.",
  "Nov 28": "Your optimism isn't naivete — it's courageous faith in the goodness you see. Keep believing.",
  "Nov 29": "A bigger creative vision includes international, boundary-crossing ambition. Dream across borders.",
  "Nov 30": "November ends with fire rekindled and creative ambition soaring. You're ready for the grandest stage.",

  // ── December ──
  "Dec 1": "December's festive energy is your natural habitat. Celebrate, host, and glow magnificently.",
  "Dec 2": "Holiday traditions infused with your personal flair become legendary. Add gold to everything.",
  "Dec 3": "A philosophical conversation about purpose and creative legacy deepens your sense of mission.",
  "Dec 4": "Your gifts are always spectacular — not just expensive, but chosen with a storyteller's eye for drama.",
  "Dec 5": "Winter's darkness is the backdrop that makes your light visible. Shine against the dark.",
  "Dec 6": "Holiday cooking and entertaining is your stage. Every detail matters, every guest is honored.",
  "Dec 7": "Family dynamics during holidays benefit from your warm leadership. Be the heart of the gathering.",
  "Dec 8": "A dramatic, beautiful, perfectly chosen gift tells a story about the bond you share.",
  "Dec 9": "Year-end reflection on creative accomplishments fills you with well-deserved pride. You made art.",
  "Dec 10": "Holiday decorating is performance art. Every light, every ornament is a scene in your production.",
  "Dec 11": "Your home during December should feel like a magnificent stage set for love and celebration.",
  "Dec 12": "Rest is part of the creative cycle. Even the sun sets to rise more brilliantly tomorrow.",
  "Dec 13": "A holiday performance, concert, or celebration reminds you of the transcendent power of shared joy.",
  "Dec 14": "Your holiday generosity knows no bounds, but remember: you can't light fires if you burn out.",
  "Dec 15": "The year's creative highlight reel shows more courage, more brilliance, and more heart than ever.",
  "Dec 16": "A quiet evening reflecting on your growth is its own kind of celebration. Acknowledge yourself.",
  "Dec 17": "Your flair for making occasions memorable — the toast, the decoration, the gesture — is legendary.",
  "Dec 18": "Even in winter, your fire warms everyone around you. You are the hearth in the cold season.",
  "Dec 19": "Creative love isn't always easy, but it's always worth the dramatic investment. Love boldly.",
  "Dec 20": "Your year of creative and personal growth has been remarkable. Braver, warmer, and more genuinely golden.",
  "Dec 21": "Winter solstice. The darkest night only proves that light always returns — and your light is permanent.",
  "Dec 22": "Capricorn season begins. Ambition meets creativity — you're ready to build your legacy brick by golden brick.",
  "Dec 23": "Holiday preparations are your choreography. Every detail you place is a step in the dance of love.",
  "Dec 24": "Tonight, your home glows with the accumulated warmth of every performance of love this year.",
  "Dec 25": "Today, receive the adoration you so freely give. Let love flow toward you. Open every gift with wonder.",
  "Dec 26": "Post-holiday warmth: the quiet glow after the flame. Bask in love's aftermath.",
  "Dec 27": "Your creative year-end journal should read like a bestseller. Document the triumphs.",
  "Dec 28": "A New Year intention forms: more authentic creative expression, less performing for approval.",
  "Dec 29": "Your art, your love, and your legacy are the three things you built this year. All three shine golden.",
  "Dec 30": "Tomorrow the year ends. Tonight, take your final bow with dignity, warmth, and magnificent pride.",
  "Dec 31": "The year closes with you standing in your full glory. Proud, generous, and radiantly alive. Happy new year, Leo.",
};
