/** 365 daily quotes for Libra — one for every day of the year. */
export const libraDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new balance. Set intentions that honor both your need for harmony and your personal ambition.",
  "Jan 2": "Your sense of fairness gives this year clear direction. Pursue what's just — for the world and for yourself.",
  "Jan 3": "A harmonious morning routine sets the aesthetic tone. Begin the day surrounded by beauty.",
  "Jan 4": "Your living space should reflect balance: warm and cool, soft and structured. Adjust one element today.",
  "Jan 5": "Someone needs your diplomatic insight today. Your ability to see both sides resolves tension.",
  "Jan 6": "Venus whispers about relationships. Check in: are you giving and receiving in equal measure?",
  "Jan 7": "A partnership conversation benefits from your gift for finding middle ground. Lead with fairness.",
  "Jan 8": "Your people-pleasing tendency isn't weakness — but today, please yourself first.",
  "Jan 9": "Financial balance soothes your equilibrium. Review your spending for alignment with values.",
  "Jan 10": "Your eye for design elevates whatever you touch. Rearrange, curate, or style something beautiful.",
  "Jan 11": "Indecision is your shadow side. Today, practice making a choice quickly and trusting it completely.",
  "Jan 12": "Your charm opens doors, but substance keeps them open. Back your smile with action today.",
  "Jan 13": "A beautiful environment isn't superficial for Libra — it's the air your mind breathes.",
  "Jan 14": "Your scales weigh everything: pros, cons, feelings, logic. Today, let your heart tip the balance.",
  "Jan 15": "Midmonth check: where are your relationships out of balance? Recalibrate with honest conversation.",
  "Jan 16": "Art, music, or beauty of any kind is not a luxury — it's your soul food. Feed yourself today.",
  "Jan 17": "A collaboration benefits from your ability to synthesize different perspectives into harmony.",
  "Jan 18": "Self-expression through aesthetic choices — clothing, decor, plating — is your creative outlet.",
  "Jan 19": "Your graceful handling of conflict earns respect today. Diplomacy is underrated strength.",
  "Jan 20": "A cardinal sign's initiative shows when you start a conversation others are afraid to have.",
  "Jan 21": "Something developing in your relationships will bring unexpected harmony. Stay open.",
  "Jan 22": "Your generous nature is a gift, but the most important relationship to balance is with yourself.",
  "Jan 23": "The partnership of your life — romantic, creative, or professional — deserves renewed commitment.",
  "Jan 24": "A childhood appreciation for fairness still guides your moral compass. It was always right.",
  "Jan 25": "Your charm melts resistance today. Use it for good — open hearts, bridge divides, create peace.",
  "Jan 26": "Joint financial planning with a partner benefits from your balanced perspective.",
  "Jan 27": "Quality aesthetics in daily life — fresh flowers, good music, beautiful dinnerware — feed your soul.",
  "Jan 28": "Your cardinal air nature means you initiate ideas with grace. Launch something new today.",
  "Jan 29": "An act of peacemaking today fills your Libra heart more than any personal victory.",
  "Jan 30": "A gallery, concert, or beautiful film feeds your soul the way food feeds your body.",
  "Jan 31": "January ends with relational clarity. You've weighed, balanced, and chosen with increasing confidence.",

  // ── February ──
  "Feb 1": "February stirs your romantic idealism. Love should be beautiful, balanced, and deeply fair.",
  "Feb 2": "Your intuition about relational dynamics is sharp today. Trust what you sense beneath smiles.",
  "Feb 3": "A creative collaboration produces something more beautiful than either of you could alone.",
  "Feb 4": "Your space needs an aesthetic refresh. New arrangement, fresh flowers, or a curated color palette.",
  "Feb 5": "Emotional boundaries in relationships aren't selfish — they're the fences that make good neighbors.",
  "Feb 6": "Your air sign nature craves intellectual stimulation alongside beauty. Read something provocative.",
  "Feb 7": "A relationship needs honest communication more than it needs peace-keeping. Be kind AND truthful.",
  "Feb 8": "Your inner mediator sometimes suppresses your own needs. Today, advocate for yourself boldly.",
  "Feb 9": "Grace under pressure defines you. A challenging moment reveals your elegant composure.",
  "Feb 10": "Your social intelligence creates belonging wherever you go. People feel balanced in your presence.",
  "Feb 11": "Beautiful objects in your space aren't materialistic — they're your external emotional landscape.",
  "Feb 12": "Your love language is quality time and aesthetic experience. Plan both for someone special.",
  "Feb 13": "Pre-Valentine: your idea of romance involves equality, beauty, and thoughtful reciprocity. That's evolved love.",
  "Feb 14": "Love is your ruling planet's domain. Today, embody Venus fully: beautiful, loving, and fair.",
  "Feb 15": "After Valentine's intensity, restore balance with solitude or quiet beauty. Recharge aesthetically.",
  "Feb 16": "Your connection to Venus guides your values. What do you truly find beautiful? Pursue that.",
  "Feb 17": "A beautifully plated meal shared with someone you love satisfies body, eyes, and heart simultaneously.",
  "Feb 18": "Your aesthetic sense is a gift. What you find beautiful often IS beautiful. Trust your taste.",
  "Feb 19": "People-pleasing surfaces. Check: are you agreeing because you agree, or to avoid discomfort?",
  "Feb 20": "Emotional honesty in partnership creates the true balance you crave. Symmetry requires truth.",
  "Feb 21": "Your dreams tonight invite creative and relational insights. Pay attention to the imagery.",
  "Feb 22": "Confidence built on genuine self-worth, not external validation, creates the stability you need.",
  "Feb 23": "A beautiful or stimulating environment reminds you what thriving looks like. Create that today.",
  "Feb 24": "Your moods respond to aesthetic disruption. If you feel unbalanced, restore beauty in your space.",
  "Feb 25": "Your flexible cardinal nature allows you to lead from the middle — orchestrating rather than dictating.",
  "Feb 26": "A beautiful outfit or intentional styling choice shifts your energy for the entire day.",
  "Feb 27": "Your ability to hold opposing views without choosing sides is rare wisdom, not indecisiveness.",
  "Feb 28": "February taught you that beauty and truth are partners, not rivals. Pursue both.",
  "Feb 29": "Rare day, rare balance. Use the extra 24 hours for something that's equally beautiful and meaningful.",

  // ── March ──
  "Mar 1": "Spring stirs your social nature. Reconnect with people who bring beauty and balance to your life.",
  "Mar 2": "Your balanced perspective solves a dilemma that one-sided thinking couldn't. Weigh wisely.",
  "Mar 3": "Fill your own aesthetic cup before curating beauty for others. Visit a gallery, garden, or boutique.",
  "Mar 4": "Your sensitivity to disharmony today alerts you to an imbalance that needs gentle correction.",
  "Mar 5": "A creative outlet that involves partnership or collaboration produces your best work.",
  "Mar 6": "The people who truly appreciate you value your fairness and grace. Acknowledge them today.",
  "Mar 7": "Venus stirs romantic or creative desire tonight. Beauty calls — answer with openness.",
  "Mar 8": "Diplomatic leadership means solving conflicts before they escalate. Your radar detects tension early.",
  "Mar 9": "A beautifully written letter, note, or message from you carries unusual grace. Send one today.",
  "Mar 10": "Your environment should be a gallery of your values. Does it reflect what you believe is beautiful?",
  "Mar 11": "Emotional intimacy in a relationship deepens when you risk expressing an unpopular feeling.",
  "Mar 12": "Your cardinal nature initiates new social connections today. Introduce yourself with charm.",
  "Mar 13": "Fresh air and beautiful scenery recalibrate your air sign's inner compass. Get outside.",
  "Mar 14": "Your love of balance doesn't mean avoiding extremes. It means knowing when intensity is appropriate.",
  "Mar 15": "Feeding your aesthetic sensibility is self-care. Museum, concert, or simply a beautiful walk.",
  "Mar 16": "A quiet act of diplomatic genius today smooths a situation no one else could handle.",
  "Mar 17": "Your luck comes through social grace and genuine charm. Opportunities arrive through people.",
  "Mar 18": "Your ideal partnership includes intellectual stimulation, aesthetic alignment, and mutual respect.",
  "Mar 19": "Spring equinox approaches. The balance of light and dark is YOUR cosmic holiday.",
  "Mar 20": "Spring equinox. Perfect balance of day and night. You feel this equilibrium in your bones.",
  "Mar 21": "Aries season activates your relationship axis. Bold new partnerships or honest conversations emerge.",
  "Mar 22": "Your opposite sign's assertive energy challenges you to take a stand. Be diplomatic AND decisive.",
  "Mar 23": "A relationship benefits from direct communication. Your honest approach helps, even if it feels risky.",
  "Mar 24": "Partnership dynamics shift this season. What you initiate in love now has lasting power.",
  "Mar 25": "Your authentic self, unfiltered by people-pleasing, is actually more attractive. Be real.",
  "Mar 26": "Bold partnership moves honor your cardinal nature. Start the conversation you've been avoiding.",
  "Mar 27": "Your fear of conflict sometimes costs more than the conflict itself. Face it gracefully today.",
  "Mar 28": "A partner's directness helps you see what your diplomatic lens sometimes softens too much.",
  "Mar 29": "Balance between assertiveness and grace: this season teaches you both can coexist beautifully.",
  "Mar 30": "Your relational intelligence today navigates a complex dynamic with elegant precision.",
  "Mar 31": "March ends with stronger, more honest relationships. Balance doesn't mean hiding — it means integrating.",

  // ── April ──
  "Apr 1": "Playfulness suits your sociable nature. Lighthearted connection brings genuine joy today.",
  "Apr 2": "Your social awareness picks up on group mood shifts today. You feel the collective energy.",
  "Apr 3": "A friendship deepens through mutual aesthetic appreciation. Share beauty with someone who sees it.",
  "Apr 4": "Group dynamics reveal your role: harmonizer, mediator, the one who helps everyone find common ground.",
  "Apr 5": "Your vision for the future includes beauty, justice, and interconnectedness. Dream elegantly.",
  "Apr 6": "Social energy peaks. Your charm creates the atmosphere where magic conversations happen.",
  "Apr 7": "A cause that promotes fairness and beauty deserves your diplomatic energy today.",
  "Apr 8": "Your friends value your balanced wisdom. Today, offer it generously — but only when asked.",
  "Apr 9": "An innovative idea about design, relationships, or social harmony surfaces. It's ahead of its time.",
  "Apr 10": "Your advocacy for fairness extends to social justice today. Use your voice for balance.",
  "Apr 11": "Spring's beauty speaks directly to your Venusian soul. Absorb it through all your senses.",
  "Apr 12": "Social settings energize you when the conversation is meaningful. Seek depth beneath charm.",
  "Apr 13": "A vision for a more beautiful, just future crystallizes through your unique lens.",
  "Apr 14": "Your humanitarian side sees that individual fairness creates collective beauty. Start with one person.",
  "Apr 15": "Financial decisions benefit from your weighing nature. Consider both practicality and values.",
  "Apr 16": "Your diplomatic radar prevents unnecessary social friction today. Smooth the way gracefully.",
  "Apr 17": "Venus blesses your evening with beauty — a gorgeous sunset, loved company, or aesthetically perfect meal.",
  "Apr 18": "Your need for connection battles your need for personal space today. Balance both with intention.",
  "Apr 19": "Taurus season approaches. Fellow Venus-ruled energy grounds your airy idealism with earthly pleasure.",
  "Apr 20": "Your aesthetic appreciation meets sensual enjoyment. Beauty you can touch, taste, and feel.",
  "Apr 21": "Quality food in a beautiful setting satisfies both your earth and air needs. Dine well.",
  "Apr 22": "Earth Day reflects your belief in balance between humanity and nature. Honor that balance.",
  "Apr 23": "Your hosting combines elegance with warmth: beautiful table, good conversation, and genuine welcome.",
  "Apr 24": "Material beauty that aligns with your values brings lasting satisfaction. Invest in what matters.",
  "Apr 25": "Sensory beauty — flowers, music, silk, fine art — doesn't just please you. It sustains you.",
  "Apr 26": "Your patience with relationships proves that enduring beauty takes time to cultivate.",
  "Apr 27": "A treasured object of beauty tells the story of your refined taste. Display it proudly.",
  "Apr 28": "Your partnerships — real or metaphorical — show the results of consistent attention and care.",
  "Apr 29": "Evening beauty rituals — skincare, ambient lighting, gentle music — are your meditation.",
  "Apr 30": "April ends with social grace and aesthetic richness. You've balanced beautifully this month.",

  // ── May ──
  "May 1": "May brings Venus-blessed abundance. Beauty, partnership, and pleasure are your birthright.",
  "May 2": "Your body responds to beauty as medicine. Surround yourself with what makes your heart say yes.",
  "May 3": "A diplomatic gesture transforms a tense situation. Your balanced approach works wonders again.",
  "May 4": "Financial balance created through thoughtful budgeting brings the stability that supports your idealism.",
  "May 5": "Your space craves something beautiful: a painting, a sculpture, fresh peonies, or redesigned lighting.",
  "May 6": "Past partnerships, even imperfect ones, taught you about balance. Honor those lessons today.",
  "May 7": "A meal that's as beautiful as it is delicious satisfies your Venusian standards perfectly.",
  "May 8": "Your social reserves run deep right now. Share your diplomatic wisdom generously.",
  "May 9": "Your body appreciates balanced nutrition: colorful plates, varied textures, and harmonious flavors.",
  "May 10": "Your gracious nature makes others feel valued. A kind word from you carries unusual weight.",
  "May 11": "Traditions of beauty and connection define your personal culture. Honor one today.",
  "May 12": "Your presence creates a sense of aesthetic calm wherever you go. Walk into a room and watch it relax.",
  "May 13": "An aesthetic upgrade to your space — new art, rearranged furniture, fresh color — shifts your mood.",
  "May 14": "Love expressed through shared beautiful experiences speaks directly to your Venusian heart.",
  "May 15": "Your social intelligence navigates a complex group dynamic with characteristic elegance.",
  "May 16": "Time spent appreciating art, nature, or beauty recharges your Venus-ruled batteries.",
  "May 17": "A beautifully curated space reflects a beautifully curated mind. Tend your environment.",
  "May 18": "Your indecision surfaces. Remember: not choosing IS a choice. Decide and commit today.",
  "May 19": "A beautifully designed evening — candles, music, flowers — feeds your soul like nothing else.",
  "May 20": "A gift chosen with your impeccable taste speaks volumes about your love and attention.",
  "May 21": "Gemini season begins. Intellectual stimulation meets your social grace. Brilliant conversations await.",
  "May 22": "Your diplomatic gifts find clear verbal expression. Articulate your balanced perspective today.",
  "May 23": "A conversation about fairness or beauty goes brilliantly. Words capture your vision perfectly.",
  "May 24": "Your gracious nature finds eloquent expression. Write the thoughtful message, speak the kind truth.",
  "May 25": "Social energy through intellectual exchange lights up your air sign mind. Seek stimulating company.",
  "May 26": "Your listening skills, combined with diplomatic insight, make you the trusted confidant today.",
  "May 27": "Learning about design, philosophy, or relationship dynamics feeds your hungry Venus mind.",
  "May 28": "A neighborhood or community connection benefits from your harmonizing social skills.",
  "May 29": "Your mental balancing act works overtime: weighing options, seeing perspectives, finding center.",
  "May 30": "Movement with grace — yoga, dance, a beautiful walk — aligns your body with your aesthetic soul.",
  "May 31": "May ends with social richness and aesthetic satisfaction intertwined beautifully.",

  // ── June ──
  "Jun 1": "June's light energy matches your sociable air nature. Connection comes easily now.",
  "Jun 2": "Your verbal grace deepens. Choosing the perfect diplomatic phrase becomes effortless.",
  "Jun 3": "An idea about creating beauty, justice, or harmony crystallizes clearly. Share it.",
  "Jun 4": "Your curiosity about human relationships — why people connect, conflict, and resolve — deepens.",
  "Jun 5": "Short outings with aesthetically minded friends refresh your social batteries.",
  "Jun 6": "A conversation with an intellectual equal reveals shared values about beauty and justice.",
  "Jun 7": "Your hands create balance today — arranging flowers, styling a room, plating food artfully.",
  "Jun 8": "Relational energy builds as the year's midpoint approaches. Important partnerships evolve.",
  "Jun 9": "Clear, gracious communication repairs a misunderstanding. Your diplomatic words heal.",
  "Jun 10": "Your mind and heart align on a relationship decision. Logic and feeling agree. Act.",
  "Jun 11": "A book or film about love, justice, or beauty gives you language for what you've always felt.",
  "Jun 12": "Your evening routine should be a ceremony of beauty. Skincare, soft light, and gentle reflections.",
  "Jun 13": "Summer approaches, and your social calendar fills with the connections your air sign craves.",
  "Jun 14": "Your connection to Venus intensifies during the longer days. Beauty everywhere you look.",
  "Jun 15": "Halfway through the year: are your relationships balanced? Are you receiving as much as you give?",
  "Jun 16": "A beautifully curated gathering — even two friends at a lovely table — is your idea of heaven.",
  "Jun 17": "Your pursuit of fairness sometimes means having uncomfortable conversations. Truth is beautiful too.",
  "Jun 18": "Golden hour light was made for Libra appreciation. Bathe in beauty tonight.",
  "Jun 19": "Relational insights deepen as summer begins. You understand the architecture of harmony.",
  "Jun 20": "Summer solstice eve. The longest light illuminates what needs balancing in your life.",
  "Jun 21": "Summer solstice. Maximum light, maximum social energy. Your air sign soars in the brightness.",
  "Jun 22": "Cancer season begins. Emotional depth asks you to balance heart with head.",
  "Jun 23": "Home aesthetics deserve Cancerian nurturing. Create beauty that also feels like a warm embrace.",
  "Jun 24": "Emotional honesty in your closest partnership creates the balanced intimacy you need.",
  "Jun 25": "Family dynamics benefit from your diplomatic skills. You harmonize what others polarize.",
  "Jun 26": "Your home should be beautiful AND emotionally nurturing. Today, combine aesthetics with comfort.",
  "Jun 27": "A family member's appreciation for your peacemaking touches your harmonious heart.",
  "Jun 28": "Emotional intuition deepens when you stop analyzing feelings and just let yourself feel.",
  "Jun 29": "A quiet evening restoring beauty in your space is the perfect Libra-Cancer blend.",
  "Jun 30": "June ends with emotional depth enriching your aesthetic perspective. Feelings make beauty real.",

  // ── July ──
  "Jul 1": "July asks for nurturing warmth beneath your social polish. Lead with heart today.",
  "Jul 2": "Emotional expression in your closest partnership deepens your connection beyond surface beauty.",
  "Jul 3": "Home as a beautiful, nurturing space: your aesthetic meets emotional intelligence.",
  "Jul 4": "Independence and partnership can coexist beautifully. Freedom within commitment is the Libra ideal.",
  "Jul 5": "Emotional honesty with yourself about what you truly want in relationships clears the static.",
  "Jul 6": "Kitchen creativity combines your aesthetic eye with emotional nurturing. Make a gorgeous, comforting meal.",
  "Jul 7": "Family relationships reveal patterns your balanced perspective can help heal. Mediate gently.",
  "Jul 8": "Trust your emotional instincts today. Your heart weighs truth as accurately as your mind.",
  "Jul 9": "Vulnerability with a trusted partner creates the deep balance surface harmony can't achieve.",
  "Jul 10": "A home beautification project feeds both your aesthetic and emotional needs. Start one.",
  "Jul 11": "Your gracious hosting creates the emotional safety that lets real conversations happen.",
  "Jul 12": "Emotional inheritance from your family — patterns of relating — can be understood and balanced.",
  "Jul 13": "Your nervous system craves harmony. If noise or conflict abounds, create a peaceful sanctuary.",
  "Jul 14": "Water energy (pool, ocean, rain) combined with beauty (sunset, flowers) deeply restores you.",
  "Jul 15": "Mid-July: your emotional and aesthetic lives are integrating. Inner beauty meets outer beauty.",
  "Jul 16": "A creative-relational project starts during this emotional season. It carries unusual depth.",
  "Jul 17": "Your space transformation this month should honor both beauty and emotional comfort.",
  "Jul 18": "Financial decisions during Cancer season should balance practical security with aesthetic values.",
  "Jul 19": "Leo energy approaches, asking you to step into the creative spotlight. Prepare gracefully.",
  "Jul 20": "Evening beauty rituals combined with emotional self-care create the perfect end-of-day balance.",
  "Jul 21": "Emotional journaling reveals what your diplomatic face sometimes hides. Write honestly.",
  "Jul 22": "Leo season begins. Creative self-expression calls you to show your beauty boldly.",
  "Jul 23": "Your aesthetic vision combined with Leo's courage produces something strikingly beautiful.",
  "Jul 24": "Playful creativity breaks through your sometimes-careful composure. Let art be messy and fun.",
  "Jul 25": "Your inner artist — the one behind the diplomat — wants to create without committee approval.",
  "Jul 26": "Romantic gestures during Leo season should be beautiful AND bold. Love with drama and grace.",
  "Jul 27": "A creative partnership produces something dazzling when your aesthetic sense meets fiery passion.",
  "Jul 28": "Heart-centered creative expression reveals beauty you didn't know you were capable of making.",
  "Jul 29": "Joy as a creative force: let happiness, not just beauty, guide your choices today.",
  "Jul 30": "Bold aesthetic choices aren't out of character — they're your character unleashed. Be brave.",
  "Jul 31": "July ends with emotional depth adding soul to your already beautiful perspective.",

  // ── August ──
  "Aug 1": "August's creative warmth activates your artistic side. Beauty through bold expression.",
  "Aug 2": "Creative projects shine when Leo's confidence meets your refined taste. Produce something stunning.",
  "Aug 3": "Your mentoring style combines aesthetic guidance with warm encouragement. Help someone see beauty.",
  "Aug 4": "A playful approach to beauty production makes the work feel effortless and joyful.",
  "Aug 5": "Joy in beautiful details: the perfect color, the right proportion, the harmonious composition.",
  "Aug 6": "Your refined eye serves a creative project brilliantly. The art of editing is your superpower.",
  "Aug 7": "Romance during Leo season asks for grand aesthetic gestures. Create a beautiful moment of love.",
  "Aug 8": "A creative collaborator reminds you that passion and precision together produce the best art.",
  "Aug 9": "Your space becomes a gallery during creative season. Display what you've made or curated.",
  "Aug 10": "Your balanced approach overcomes a creative impasse. Seeing from multiple angles reveals the solution.",
  "Aug 11": "A beautiful creative piece shared with the world brings the recognition your Venus heart enjoys.",
  "Aug 12": "Sunshine, beautiful scenery, and creative conversations energize your air sign soul.",
  "Aug 13": "Your devotion to beauty is itself a form of service. Making the world lovelier helps everyone.",
  "Aug 14": "Summer's peak invites peak beauty appreciation. Notice and celebrate the gorgeous world around you.",
  "Aug 15": "Mid-August balance check: are you creating enough? Receiving enough beauty? Sharing enough love?",
  "Aug 16": "A creative partner's feedback enhances your vision. Collaboration elevates solo effort.",
  "Aug 17": "Your refined taste serves a practical purpose today. Quality choices save time and money.",
  "Aug 18": "Evening beauty: a gorgeous sunset, a styled dinner table, candlelight and conversation.",
  "Aug 19": "Late summer whispers of autumn — YOUR season approaches. Can you feel the scales preparing?",
  "Aug 20": "The transition toward your energy begins with an internal rebalancing. Center yourself.",
  "Aug 21": "Summer's beautiful memories become your aesthetic reference library. What inspired you most?",
  "Aug 22": "Practicality meets beauty as Virgo season approaches. Functionality can be gorgeous.",
  "Aug 23": "Virgo season begins. Refine and organize the beautiful life you're building.",
  "Aug 24": "Your aesthetic vision gets practical execution support. Detail work makes beauty last.",
  "Aug 25": "Health routines support the beautiful life you want. Your body is the vessel for your art.",
  "Aug 26": "Your spaces benefit from thoughtful organization that serves both function and aesthetics.",
  "Aug 27": "Organizing your social life with the same care you give your aesthetics creates sustainable joy.",
  "Aug 28": "Daily practices of beauty appreciation — noticing light, color, proportion — sharpen your eye.",
  "Aug 29": "Service through beauty: creating lovely environments, mediating gracefully, adding charm to function.",
  "Aug 30": "Practical beauty — beautifully organized spaces, elegant solutions to everyday problems — is your art.",
  "Aug 31": "August ends with your creative and practical sides in beautiful alignment.",

  // ── September ──
  "Sep 1": "September channels your relationship energy into refined, purposeful connections.",
  "Sep 2": "Health-focused beauty routines support the radiance you naturally embody. Tend your glow.",
  "Sep 3": "A space purge that removes what's ugly or useless creates room for what's beautiful and meaningful.",
  "Sep 4": "Daily acts of beauty: choosing the right cup, arranging your desk, styling an outfit with care.",
  "Sep 5": "A detail-oriented aesthetic task reveals that beauty truly lives in the small things.",
  "Sep 6": "Your body responds to balanced eating: harmonious meals in beautiful settings.",
  "Sep 7": "Service through aesthetic improvement lifts environments and spirits simultaneously.",
  "Sep 8": "A wellness adjustment that makes you feel more beautiful also makes you feel more you.",
  "Sep 9": "Daily aesthetic rituals create a rhythm of beauty that sustains you through challenges.",
  "Sep 10": "Beautifully prepared meals nourish body and soul simultaneously. Plate with artistry.",
  "Sep 11": "Your diplomatic grace holds collective space with beauty and dignity today. You bring peace.",
  "Sep 12": "A creative or social partner reminds you that your taste is a genuine gift to the world.",
  "Sep 13": "Organization that enhances beauty rather than suppressing it is the balance you're mastering.",
  "Sep 14": "Your relational health check: are your partnerships as beautiful as your aesthetic standards?",
  "Sep 15": "Practical self-care that also makes you feel beautiful: the intersection of wellness and aesthetics.",
  "Sep 16": "Your attention to someone's need for harmony creates healing. Balance is medicine.",
  "Sep 17": "A routine change that adds beauty — a bouquet, better lighting, curated music — transforms daily life.",
  "Sep 18": "Your space during pre-Libra season should start reflecting your signature aesthetic at full power.",
  "Sep 19": "Virgo's refinement has polished your beauty standards. You see more clearly what truly matters.",
  "Sep 20": "Practical elegance: beauty that functions, aesthetics that serve. Your mastery deepens.",
  "Sep 21": "Autumn equinox. YOUR cosmic holiday. Light and dark in perfect, fleeting balance. Feel it in your soul.",
  "Sep 22": "The scales tip toward your season. Balance energy intensifies. You're coming into your power.",
  "Sep 23": "LIBRA SEASON BEGINS! The sun enters your sign. Harmony, beauty, and balance orbit around you now.",
  "Sep 24": "Happy Libra season! Your cosmic birthday month activates maximum charm and aesthetic power.",
  "Sep 25": "Relationships during your season reach their most harmonious potential. Connect deeply.",
  "Sep 26": "Beauty during your season is not just visual — it's emotional, intellectual, and spiritual.",
  "Sep 27": "Your diplomatic gifts peak during your season. Every mediation, every compromise, is elegant.",
  "Sep 28": "A partnership blessed during your season carries unusual grace and potential for harmony.",
  "Sep 29": "Balance during your season extends to work-life, give-receive, and introvert-extrovert. Find center.",
  "Sep 30": "September ends with your season in ascendance. The world needs your vision of beauty and justice.",

  // ── October ──
  "Oct 1": "October IS your peak month. Beauty, balance, and relational wisdom reach their annual zenith.",
  "Oct 2": "Your season's relational magic is in full effect. Every connection you make today is golden.",
  "Oct 3": "A beautifully curated autumn scene fills your Libra heart with seasonal aesthetic joy.",
  "Oct 4": "Your reputation for fairness and grace is your most beautiful accomplishment.",
  "Oct 5": "Partnership during your season feels fated. The connections you deepen now are significant.",
  "Oct 6": "Your ability to make any environment more beautiful is magic. Cast that spell today.",
  "Oct 7": "Balance between your needs and others' needs reaches a harmonious resolution during your season.",
  "Oct 8": "Your Venusian warmth heals a relational wound. Your grace under pressure is extraordinary.",
  "Oct 9": "Autumn's perfect aesthetic — amber light, falling leaves, warm fabrics — is your season's gift to the senses.",
  "Oct 10": "Your sense of justice meets practical application. Advocacy that creates real change.",
  "Oct 11": "A collaborative creative project during your season produces something of lasting beauty.",
  "Oct 12": "Your contribution to cultural beauty and social harmony is your unique Libra legacy.",
  "Oct 13": "Autumn entertaining with seasonal aesthetics — pumpkins, warm tones, cinnamon — is your art form.",
  "Oct 14": "A decision during your season comes with unusual clarity. Your scales are perfectly calibrated.",
  "Oct 15": "Your creative confidence blooms during your birthday month. Make beautiful things without hesitation.",
  "Oct 16": "A gift from you during your season carries your peak aesthetic energy. It will be perfect.",
  "Oct 17": "Your autumn wardrobe, styled with Libra precision, makes getting dressed a daily creative act.",
  "Oct 18": "Late Libra season relationships carry deep commitment energy. Something beautiful solidifies.",
  "Oct 19": "Evening gratitude for beauty, balance, and love flows naturally from your harmonious heart.",
  "Oct 20": "Your season's final days concentrate your Venusian power. What beautiful intention do you set?",
  "Oct 21": "A relational milestone during your season crystallizes something you've been building all year.",
  "Oct 22": "Your season closes with the grace of a perfect equation. Everything balanced, everything beautiful.",
  "Oct 23": "Scorpio season begins. Depth energy asks you to go beneath surface beauty to soul-deep truth.",
  "Oct 24": "Deep partnership honesty replaces diplomatic smoothing. Real love isn't always pretty — but it's always true.",
  "Oct 25": "Your intuition about relational truth intensifies. See past the charm (even your own) to what's real.",
  "Oct 26": "Intimacy deepens when you drop the social face and show raw humanity. Be imperfect and beloved.",
  "Oct 27": "Financial or shared resource decisions benefit from your balanced yet now-deeper perspective.",
  "Oct 28": "Your capacity for emotional transformation surprises even you. Beauty evolves through depth.",
  "Oct 29": "The deeper layers of your relational patterns reveal truths your diplomatic surface smoothed over.",
  "Oct 30": "Emotional beauty — the kind that comes from depth, not decoration — becomes your new standard.",
  "Oct 31": "Your costume tonight should channel your most powerfully balanced self. Wear grace and guts.",

  // ── November ──
  "Nov 1": "November reveals beauty beneath the surface. What's real is more beautiful than what's perfect.",
  "Nov 2": "Honor the departed through the beauty they brought to your life. Their aesthetic lives in you.",
  "Nov 3": "An emotional release through art — creating or experiencing — transforms grief into grace.",
  "Nov 4": "Shared resources and relational investments benefit from your newly deepened balanced view.",
  "Nov 5": "Your trust in relationships is evolving: not naive harmony, but eyes-open love. That's growth.",
  "Nov 6": "Vulnerability that goes beyond social grace creates the real intimacy you've always wanted.",
  "Nov 7": "Your resilience is elegant: you rebuild with beauty and balance, even after disruption.",
  "Nov 8": "A partnership conversation requires your bravest honesty. Diplomacy AND truth together.",
  "Nov 9": "Dreams during this season show you the deeper beauty beyond the surface. Follow their imagery.",
  "Nov 10": "A shift in your aesthetic values reflects an inner transformation. Depth becomes the new beauty.",
  "Nov 11": "Remember beautifully. Your tributes carry the grace of genuine love and appreciation.",
  "Nov 12": "Financial beauty: investments that align with your values, spending that reflects your evolving taste.",
  "Nov 13": "Your inner world undergoes a gorgeous transformation as depth replaces surface as your standard.",
  "Nov 14": "Relational boundaries set with grace protect the love worth protecting. Kindness with backbone.",
  "Nov 15": "Halfway through November, notice how your definition of beauty has deepened and expanded.",
  "Nov 16": "Holding space for difficult truths while maintaining grace is your evolved superpower.",
  "Nov 17": "A private creative pursuit produces surprisingly deep and beautiful work. Share it selectively.",
  "Nov 18": "Higher vision approaches as Sagittarius season draws near. Beauty expands beyond the personal.",
  "Nov 19": "A challenging relational dynamic resolves through your patient, balanced persistence.",
  "Nov 20": "Release the need for everyone to like you. True balance means accepting that harmony has limits.",
  "Nov 21": "Sagittarius season begins. Philosophical beauty, global aesthetics, and expansive partnerships.",
  "Nov 22": "Travel or cultural exploration introduces you to beauty you've never imagined. Expand your palette.",
  "Nov 23": "Gratitude for the beauty in your life — people, spaces, experiences — flows powerfully today.",
  "Nov 24": "Your holiday gathering aesthetic begins taking shape. You envision events like art installations.",
  "Nov 25": "Traditions of beauty and connection define your holiday celebrations. Honor them.",
  "Nov 26": "Your gracious nature gets philosophical today. Why do you pursue beauty? Because it heals the world.",
  "Nov 27": "Cultural exploration — cuisine, art, music from unfamiliar traditions — expands your beauty vocabulary.",
  "Nov 28": "Optimism about beauty's power to heal and connect isn't naive — it's visionary.",
  "Nov 29": "A broader vision for your life includes global connections, cross-cultural beauty, and far-reaching harmony.",
  "Nov 30": "November ends with deeper, more soulful beauty as your new compass. Your scales have evolved.",

  // ── December ──
  "Dec 1": "December's festive beauty is your annual aesthetic celebration. Decorate, host, and glow.",
  "Dec 2": "Holiday aesthetics are serious business for Libra. Begin planning the most beautiful season.",
  "Dec 3": "A philosophical conversation about beauty, love, and meaning deepens your holiday spirit.",
  "Dec 4": "Your gifts are always beautifully wrapped, thoughtfully chosen, and perfectly matched to the recipient.",
  "Dec 5": "Winter's stark beauty — bare branches, frost, candlelight — speaks to your aesthetic soul.",
  "Dec 6": "Holiday meals styled with your aesthetic eye turn dinners into gallery events.",
  "Dec 7": "Family dynamics benefit from your diplomatic warmth during the holiday season.",
  "Dec 8": "A beautifully presented gift tells the whole story of your relationship in one gorgeous gesture.",
  "Dec 9": "Year-end reflection on relational and aesthetic growth fills you with balanced pride.",
  "Dec 10": "Holiday decorating is your art installation. Each light, each ribbon, each ornament is curated.",
  "Dec 11": "Your home during December is a destination for beauty and warmth. The ultimate Libra sanctuary.",
  "Dec 12": "Rest surrounded by beauty: a beautiful view, a cozy blanket, tea in a gorgeous cup.",
  "Dec 13": "A holiday concert or art event fills your aesthetic reservoir for the winter months.",
  "Dec 14": "Your holiday generosity balances material gifts with presence, attention, and genuine care.",
  "Dec 15": "The year's relational highlight reel shows deeper, more honest, and more beautiful connections.",
  "Dec 16": "A quiet evening appreciating the beauty you've created this year brings satisfying peace.",
  "Dec 17": "Your flair for making events beautiful and balanced ensures everyone feels welcome and valued.",
  "Dec 18": "Winter beauty — candlelight, evergreens, warm scarves — feeds your aesthetic nature deeply.",
  "Dec 19": "Relational beauty isn't always easy. But your commitment to harmony made love more possible this year.",
  "Dec 20": "Your year of aesthetic and relational growth has been remarkable. More balanced, deep, and genuinely beautiful.",
  "Dec 21": "Winter solstice. The perfect darkness that makes light meaningful. You understand this balance innately.",
  "Dec 22": "Capricorn season begins. Structural beauty — architecture, tradition, enduring legacy — calls to you.",
  "Dec 23": "Holiday preparations reflect your aesthetic standard: nothing less than beautiful will do.",
  "Dec 24": "Tonight, your home radiates the beauty of every connection you nurtured this year. Luminous.",
  "Dec 25": "Today, receive love as gracefully as you give beauty. Let admiration flow toward you. Be adored.",
  "Dec 26": "Post-holiday beauty: the quiet aftermath, leftover elegance, and the peace of shared satisfaction.",
  "Dec 27": "Your year-end journal should read like an art review. Document the beauty you created and found.",
  "Dec 28": "A New Year intention forms: even deeper beauty, bolder balance, and love that's both graceful and raw.",
  "Dec 29": "Your relationships, your aesthetics, and your sense of justice are the three pillars you strengthened. All stand beautifully.",
  "Dec 30": "Tomorrow the year ends. Tonight, sit in the beauty of everything you balanced and created.",
  "Dec 31": "The year closes with you standing in gorgeous equilibrium. Graceful, fair, and radiantly balanced. Happy new year, Libra.",
};
