/** 365 daily quotes for Pisces — one for every day of the year. */
export const piscesDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new dream. Set intentions that honor both your mystical nature and your tender heart.",
  "Jan 2": "Neptune's dissolving energy invites you to release last year's heaviness. Flow into fresh possibility.",
  "Jan 3": "A morning ritual that includes meditation, music, or creative expression sets your intuitive tone.",
  "Jan 4": "Your living space should feel like a sanctuary: soft, dreamy, and filled with beauty that soothes.",
  "Jan 5": "Someone needs your empathic listening today. Your ability to feel what others feel is a genuine gift.",
  "Jan 6": "Neptune's dissolving nature asks: what illusions are you ready to release this year?",
  "Jan 7": "A musical or artistic experience over morning coffee moves you more deeply than words could.",
  "Jan 8": "Your sensitivity isn't weakness — it's advanced perception. But today, protect your energy.",
  "Jan 9": "Financial intuition guides you today. Trust the feeling about the investment or the expense.",
  "Jan 10": "Your creative instinct lights up. Express what you feel — your art heals both you and others.",
  "Jan 11": "Boundaries feel harsh to your fluid nature. But today, one gentle boundary protects your peace.",
  "Jan 12": "Your intuitive perspective reveals emotional truths that logic alone would never find.",
  "Jan 13": "Home is your retreat from the world's noise. Tend your sanctuary with devotion today.",
  "Jan 14": "Your mutable water nature means your emotions shift like tides — and that's sensitivity, not instability.",
  "Jan 15": "Midmonth dreaminess intensifies. Journal a vivid image or feeling before it dissolves.",
  "Jan 16": "Water elements in your space — a fountain, an aquarium, a rain soundtrack — soothe your fish soul.",
  "Jan 17": "A creative project benefits from your ability to channel emotion into form. Feel it, then shape it.",
  "Jan 18": "Self-improvement through spiritual practice, artistic expression, and compassionate connection is your path.",
  "Jan 19": "Your gentle humor makes people feel seen and safe. Warmth is your comedy style.",
  "Jan 20": "Aquarius season asks your dreamy nature to consider community alongside personal vision.",
  "Jan 21": "Humanitarian feelings surface. Your compassion wants a cause, a channel, a way to help.",
  "Jan 22": "Group creativity feeds your artistic nature. Collaboration that produces beauty fulfills you.",
  "Jan 23": "The meaningful work of your life combines creativity with compassion. Both are non-negotiable.",
  "Jan 24": "A childhood love of imagination and make-believe still drives your creative spirit. Honor it.",
  "Jan 25": "Your gentle empathy inspires someone to open up about feelings they've been hiding.",
  "Jan 26": "Financial planning benefits from your intuitive sense of what's truly valuable versus merely expensive.",
  "Jan 27": "Music, poetry, film, and visual art feed your ever-hungry soul more than any material comfort.",
  "Jan 28": "Your mutable water nature means you absorb the emotions around you. Choose your environments wisely.",
  "Jan 29": "An act of quiet compassion — a kind word, a listening ear, a gentle touch — heals someone today.",
  "Jan 30": "A dreamy film, a mystical book, or evocative music carries your spirit where it needs to go tonight.",
  "Jan 31": "January ends with your intuitive nature fully awake and your creative channels clearing for your season.",

  // ── February ──
  "Feb 1": "February builds toward your season. Intuition, creativity, and spiritual depth intensify daily.",
  "Feb 2": "Your psychic sensitivity today picks up on currents that rational analysis completely misses.",
  "Feb 3": "A creative expression of your inner world — art, writing, music — touches someone unexpectedly.",
  "Feb 4": "Your space needs ethereal beauty: soft lighting, flowing fabrics, ocean colors, or dreamy art.",
  "Feb 5": "Emotional expression IS your natural state. Today, channel the deeper feelings into creative form.",
  "Feb 6": "Your water sign nature craves emotional and spiritual flow. Seek beauty, music, and connection.",
  "Feb 7": "Someone needs your compassionate presence today. Simply sitting with someone in their pain heals.",
  "Feb 8": "Your inner mystic sometimes overshadows your practical self. Today, balance dreams with action.",
  "Feb 9": "Creativity fueled by genuine emotion produces art that resonates across time and space.",
  "Feb 10": "Your social nature thrives in intimate, soulful gatherings. Seek depth, not crowds.",
  "Feb 11": "Beautiful, meaningful possessions — a crystal, a painting, a handmade gift — are your autobiography.",
  "Feb 12": "Your love language is presence — being fully, empathically, spiritually WITH someone.",
  "Feb 13": "Pre-Valentine: your idea of romance involves soul connection, creative expression, and tender vulnerability.",
  "Feb 14": "Love for Pisces is oceanic — boundless, deep, and mystical. Today, swim in that love fully.",
  "Feb 15": "After Valentine's intensity, your sensitive spirit needs quiet beauty. Nature, music, or solitude.",
  "Feb 16": "Your connection to Neptune deepens as your season approaches. Dreams become increasingly vivid.",
  "Feb 17": "An intuitively prepared meal — cooking by feeling rather than recipe — satisfies your creative soul.",
  "Feb 18": "Your season's doorstep. Can you feel the cosmic ocean rising to meet your Piscean shores?",
  "Feb 19": "PISCES SEASON BEGINS! The sun enters your sign. Maximum intuition, creativity, and spiritual depth.",
  "Feb 20": "Your season's second day deepens the mystical current. Dreams, art, and compassion flow freely.",
  "Feb 21": "Happy Pisces season! Your cosmic birthday month activates your most creative, intuitive energy.",
  "Feb 22": "Confidence rooted in spiritual knowing — in trusting what you feel beyond what you can prove — is your power.",
  "Feb 23": "A creative soul-friend reminds you that shared mystical experience doubles its magic.",
  "Feb 24": "Your emotions move like ocean currents — deep, powerful, and sometimes pulling you where you need to go.",
  "Feb 25": "Your mutable nature allows you to flow around obstacles. Water finds a way when force cannot.",
  "Feb 26": "Flowing, beautiful clothing that moves with you reflects your fluid spirit perfectly.",
  "Feb 27": "Your ability to find beauty in sadness AND joy is uniquely Piscean. Both are art's raw material.",
  "Feb 28": "February's last day in your season. The mystical tide rises higher. Surrender to the creative flow.",
  "Feb 29": "Rare day, rare magic. The veil is thinnest today. Trust every intuitive whisper.",

  // ── March ──
  "Mar 1": "March continues your powerful season. Creativity and intuition at their cosmic peak.",
  "Mar 2": "Your intuitive wisdom guides a decision that analytical thinking couldn't reach. Trust the knowing.",
  "Mar 3": "Rest your empathic nature before the energy shifts. Even the ocean needs calm before the tides change.",
  "Mar 4": "Your psychic awareness today reveals an emotional undercurrent that nobody else has noticed.",
  "Mar 5": "A creative masterwork surfaces from the depths. Something you've been feeling finds its form.",
  "Mar 6": "Your creative companions, spiritual friends, and soul partners deserve celebration today.",
  "Mar 7": "Neptune deepens your evening meditation. The boundary between waking and dreaming thins beautifully.",
  "Mar 8": "Compassionate leadership means feeling the group's needs before they're spoken. You do this naturally.",
  "Mar 9": "A heartfelt message to someone you love carries the healing energy of your entire Piscean heart.",
  "Mar 10": "Your home should feel like a temple: quiet, beautiful, and charged with spiritual intention.",
  "Mar 11": "Deep emotional intimacy is your natural habitat. Don't settle for surface connection today.",
  "Mar 12": "Your mutable nature flows around emotional blocks. Adapt, dissolve resistance, and proceed gently.",
  "Mar 13": "Water bodies — ocean, lake, river, bath — restore your depleted energy immediately.",
  "Mar 14": "Your truth is felt rather than proven. Share your intuition today — the validation comes later.",
  "Mar 15": "Nourishing your body supports your sensitive nervous system. Eat gently and well.",
  "Mar 16": "A creative detour today leads to an expression you didn't know was waiting inside you.",
  "Mar 17": "Your luck is mystical because you sense opportunities on frequencies others can't receive.",
  "Mar 18": "Your ideal home includes soft textures, beautiful art, natural light, and quiet spaces for dreaming.",
  "Mar 19": "The final day of Pisces season concentrates your mystical power. Set one sacred intention.",
  "Mar 20": "Spring equinox. Renewal washes through you like the first warm tide. Reborn, refreshed, ready.",
  "Mar 21": "Aries season begins. Fiery energy activates your usually gentle nature into decisive action.",
  "Mar 22": "Your creative visions need Aries courage to become real. Act on one dream today.",
  "Mar 23": "Financial matters benefit from a moment of practical attention before you return to the creative stream.",
  "Mar 24": "Material security gives your dreamy nature a stable shore. Tend your practical foundations.",
  "Mar 25": "Your values and resources deserve the same creative attention you give your art. Invest in beauty.",
  "Mar 26": "Bold self-worth. Your creative gifts, your empathy, and your spiritual depth have enormous value.",
  "Mar 27": "Your earning potential increases when your unique Piscean talents are properly valued. Charge what you're worth.",
  "Mar 28": "Sensory pleasure — flowers, music, silk, chocolate — isn't indulgence. It's fuel for your art.",
  "Mar 29": "Quality possessions that bring beauty into your daily life are investments in your creative spirit.",
  "Mar 30": "Your growing material confidence supports rather than competes with spiritual depth.",
  "Mar 31": "March ends with grounding energy supporting your dreams and practical foundations solidifying.",

  // ── April ──
  "Apr 1": "April's lighter energy serves your gentle humor. You find magic where others see ordinary.",
  "Apr 2": "Your empathic presence makes every space feel safer. People relax in your gentle energy.",
  "Apr 3": "A friendship deepens through shared creative or spiritual experience and mutual vulnerability.",
  "Apr 4": "Group dynamics reveal your role: the empath, the creative visionary, and the gentle healer.",
  "Apr 5": "Your wish for the future includes beauty, compassion, and healing for the world. Never shrink it.",
  "Apr 6": "Intimate gatherings energize you more than parties. Seek the meaningful conversation, not the crowd.",
  "Apr 7": "A cause that promotes arts, healing, or compassionate care deserves your energy today.",
  "Apr 8": "Your friends see you as the one who truly understands. That empathic gift is rare and precious.",
  "Apr 9": "A creative vision surfaces through emotional connection. Art born from real feeling resonates forever.",
  "Apr 10": "Your protective instincts activate for the vulnerable. Your compassion shields those who can't shield themselves.",
  "Apr 11": "Spring's gentle growth mirrors your blooming creativity. Unfurl like a water lily in warm light.",
  "Apr 12": "Creative settings energize you best when emotion flows freely. Seek the vulnerable conversation.",
  "Apr 13": "A grand creative vision crystallizes through imagination, emotion, and mystical inspiration.",
  "Apr 14": "Your instinct says: art and compassion change everything. Start with one beautiful gesture.",
  "Apr 15": "Financial decisions benefit from your intuitive sense of value — feel the right choice.",
  "Apr 16": "Your gentle humor at a gathering creates warmth that feels like coming home for everyone.",
  "Apr 17": "Neptune dissolves your evening boundaries between self and universe. Meditate in the oneness.",
  "Apr 18": "Your need for solitude balances with your growing social connections. Both nourish you.",
  "Apr 19": "Taurus season approaches. Earthy stability asks your watery depths to materialize your dreams.",
  "Apr 20": "Your creative visions meet tangible form. Can you paint, write, or build what you've imagined?",
  "Apr 21": "Hands-on creation grounds your mystical energy. Making art is meditation with a product.",
  "Apr 22": "Earth Day connects your water nature with the earth that channels your flow.",
  "Apr 23": "Hosting with Piscean grace means beautiful ambiance, flowing conversation, and soulful food.",
  "Apr 24": "Material comfort isn't shallow. It's the beautiful shore your ocean nature needs.",
  "Apr 25": "Sensory beauty — soft fabrics, gentle music, fragrant flowers — feeds your spirit directly.",
  "Apr 26": "Your patience with slow creative processes is natural. Art grows at its own mystical pace.",
  "Apr 27": "A meaningful object — a seashell, a crystal, a handmade treasure — carries spiritual energy.",
  "Apr 28": "Your creative projects grow roots when you let them develop at the pace of natural unfolding.",
  "Apr 29": "Evening reflection: your creative and spiritual path has always guided you true. Trust its direction.",
  "Apr 30": "April ends with your creative visions beginning to take beautiful, tangible shape.",

  // ── May ──
  "May 1": "May grounds your flowing nature. Earthy beauty gives your watery creativity solid form.",
  "May 2": "Your body is a sensitive instrument. Treat it with the gentle care it requires to function optimally.",
  "May 3": "A heartfelt recommendation of art, music, or a spiritual practice changes someone's inner landscape.",
  "May 4": "Financial intuition today reveals what truly matters versus what merely glitters. Trust the feeling.",
  "May 5": "Your space benefits from natural beauty: fresh flowers, crystals, flowing water, and ocean colors.",
  "May 6": "Past creative expressions still resonate in others' hearts. Your art has traveled further than you know.",
  "May 7": "An intuitively prepared meal — guided by feeling, not measuring — nourishes body and soul.",
  "May 8": "Your emotional wisdom overflows. Share your insights about human nature with a receptive listener.",
  "May 9": "Your body needs gentle, nourishing food. Harsh or artificial ingredients jar your sensitive system.",
  "May 10": "Your mentoring nature combines empathy with creative vision. Your students don't just learn — they feel.",
  "May 11": "Spiritual traditions that honor the sacred in daily life speak your Piscean language.",
  "May 12": "Your entrance into any space shifts the emotional atmosphere toward gentleness and depth.",
  "May 13": "A home improvement that adds beauty, softness, or spiritual significance enriches your daily experience.",
  "May 14": "Love expressed through presence, tenderness, and creative devotion speaks your heart's deepest language.",
  "May 15": "Your intuitive perspective navigates emotional complexity with graceful understanding.",
  "May 16": "Swimming, water aerobics, or simply bathing mindfully is your most natural form of healing.",
  "May 17": "A collection of poetry, mystical texts, and art books maps your spiritual and creative journey.",
  "May 18": "Your creative restlessness signals that something new wants to be born through you. Listen.",
  "May 19": "An evening of music — playing, listening, or creating — feeds your mutable water soul.",
  "May 20": "A gift chosen intuitively for someone carries the healing energy of your compassionate heart.",
  "May 21": "Gemini season begins. Quick-minded energy stimulates your usually dreamy thinking into articulate form.",
  "May 22": "Your intuitive wisdom meets clear communication. Deep feelings find precise, shareable words.",
  "May 23": "Lighter conversation balances your emotional depth. Surface play is rest for the deep-diver.",
  "May 24": "Your communication skills bloom when your emotional intelligence meets articulate expression.",
  "May 25": "Social sparkle from sharing creative ideas and emotional insights in lively exchanges.",
  "May 26": "Your storytelling weaves feeling, imagery, and meaning into something others can experience viscerally.",
  "May 27": "Learning a new creative skill gives your imaginative nature fresh tools for expression.",
  "May 28": "Local beauty — a park, a gallery, a quiet café — provides creative inspiration close to home.",
  "May 29": "Your mind weaves emotional threads into creative tapestry tonight. Journal the patterns.",
  "May 30": "Gentle movement through beautiful spaces aligns body, spirit, and creative vision.",
  "May 31": "May ends with creative grounding and verbal expression enriching your mystical nature.",

  // ── June ──
  "Jun 1": "June's light energy invites your dreamy nature into the vivid, sun-warmed world.",
  "Jun 2": "Your emotionally intelligent communication touches hearts today. Words carry feeling.",
  "Jun 3": "A creative idea finds its verbal or written form. The dream becomes shareable art.",
  "Jun 4": "Your curiosity about human nature leads to an empathic understanding that surprises others.",
  "Jun 5": "A quick creative exchange or soulful conversation delivers more meaning per moment than expected.",
  "Jun 6": "A creative soul-friend matches your emotional wavelength perfectly. The exchange is pure alchemy.",
  "Jun 7": "Your hands create something that carries spiritual intention. Craft as prayer.",
  "Jun 8": "Partnership energy deepens. Summer invites your receptive nature to explore mutual devotion.",
  "Jun 9": "Gentle honesty from your compassionate heart clears the air without wounding. Speak soft truths.",
  "Jun 10": "Your creative intuition and practical instincts agree today. Trust both equally.",
  "Jun 11": "A book, poem, or spiritual text feeds your eternal hunger for mystical understanding.",
  "Jun 12": "Your routine should include sacred pauses — moments of beauty, prayer, or creative reverie.",
  "Jun 13": "Summer approaches, and your creative flow expands with the warmth. Art multiplies.",
  "Jun 14": "Your connection to Neptune intensifies as the year's midpoint nears. Dreams become prophetic.",
  "Jun 15": "Midyear creative check: have you created enough beauty? Felt enough? Healed enough?",
  "Jun 16": "A soulful dinner with beloved friends is your ideal gathering. Feelings, food, and flow.",
  "Jun 17": "Your gentle communication style sometimes needs directness added. Today, kindness plus clarity.",
  "Jun 18": "Golden hour near water is your soul's purest nourishment. Seek the shore or the fountain.",
  "Jun 19": "Summer creative planning reaches its intuitive peak. Feel the projects that want to be born.",
  "Jun 20": "Summer solstice eve. The longest light illuminates the creative depths within you.",
  "Jun 21": "Summer solstice. Maximum daylight meets your oceanic depth. The surface sparkles; the depths remain.",
  "Jun 22": "Cancer season begins. Fellow water sign energy validates your emotional approach to everything.",
  "Jun 23": "Home as sanctuary: soft, beautiful, and charged with the spiritual energy of your love.",
  "Jun 24": "Emotional honesty with family comes naturally during Cancer season. You feel what they need.",
  "Jun 25": "Your nurturing is intuitive, gentle, and exactly what each person needs without being asked.",
  "Jun 26": "Family stories carry emotional truth your psychic nature has always sensed. Now it's confirmed.",
  "Jun 27": "Cooking as an act of love — infusing food with care, intention, and beauty — is your art form.",
  "Jun 28": "Your emotional intelligence, always present, receives full validation during this water season.",
  "Jun 29": "A quiet, beautiful evening feeds your introverted Piscean need for solitude and reflection.",
  "Jun 30": "June ends with emotional depth, creative beauty, and spiritual nourishment in perfect Piscean balance.",

  // ── July ──
  "Jul 1": "July deepens your water nature. Emotional connection, creative flow, and intuitive clarity peak.",
  "Jul 2": "Your emotional wisdom is everyone's anchor. But check: who anchors you? Accept support today.",
  "Jul 3": "Home as creative sanctuary: soft lighting, meaningful art, and spaces that feel like warm water.",
  "Jul 4": "Freedom for you means the liberty to feel, create, and love without limitation.",
  "Jul 5": "Emotional depth is your natural element. Today, swim deeper than anyone else would dare.",
  "Jul 6": "Kitchen creativity guided by intuition produces a meal that nourishes souls, not just bodies.",
  "Jul 7": "Family emotional currents carry information your psychic nature decodes effortlessly.",
  "Jul 8": "Trust your deepest emotional intuition today. Your feelings are data from dimensions logic can't reach.",
  "Jul 9": "Vulnerability is your superpower. Where others guard, you soften — and that's the braver choice.",
  "Jul 10": "An emotional intention set now carries the full force of your oceanic, compassionate heart.",
  "Jul 11": "Your protective love for those closest to you manifests as fierce, tender devotion today.",
  "Jul 12": "Ancestral emotional patterns flow through you. Understanding them frees both past and future.",
  "Jul 13": "Gentle movement near or in water — swimming, walking by a stream — restores your depleted spirit.",
  "Jul 14": "Summer water activities are spiritual practice for you. Immersion IS prayer.",
  "Jul 15": "Mid-July: your emotional and creative depths are fully accessible. Create from the deepest place.",
  "Jul 16": "A creative project born from genuine emotion produces something hauntingly beautiful.",
  "Jul 17": "Your space evolution should honor comfort and beauty. Every surface should soothe your senses.",
  "Jul 18": "Financial decisions guided by intuitive values — not greed, not fear — lead to lasting security.",
  "Jul 19": "Leo season approaches. Fiery creative confidence asks you to show your art to the world.",
  "Jul 20": "Evening near water as the sun sets combines your two most healing elements. Seek it.",
  "Jul 21": "Emotional processing through creative expression — painting, writing, music — is your therapy.",
  "Jul 22": "Leo season begins. Bold creative fire warms your watery depths. Create with confidence.",
  "Jul 23": "Your creative vision gains Leo's confident expression. Share your art without apologizing.",
  "Jul 24": "Playful creativity: sometimes art doesn't need to be profound. It can simply be joyful.",
  "Jul 25": "Your inner child wants to play in the waves of imagination. Let them lead the creative process.",
  "Jul 26": "Romantic devotion during Leo season: express your love with creative gestures and heartfelt words.",
  "Jul 27": "A creative collaboration where your emotional depth meets bold expression produces magic.",
  "Jul 28": "Heart-centered creativity gives your art emotional power. The best works come from love.",
  "Jul 29": "Joy as spiritual practice: pure delight in beauty IS meditation. Find something that makes you glow.",
  "Jul 30": "Sharing your creative work publicly reveals your courage. Vulnerability displayed as art transforms both.",
  "Jul 31": "July ends with emotional mastery and creative courage raising your artistic expression to new heights.",

  // ── August ──
  "Aug 1": "August's creative peak activates your artistic gifts. Everything you create this month carries magic.",
  "Aug 2": "Creative-spiritual projects shine: music, visual art, healing work, and intuitive expression.",
  "Aug 3": "Your teaching combines empathy with creative wisdom. Others learn to feel their way to truth.",
  "Aug 4": "A playful creative challenge awakens your inner child's boundless imagination.",
  "Aug 5": "Joy in beauty: every sunset, every flower, every kindness registers as profound in your Piscean heart.",
  "Aug 6": "Your emotional intelligence serves a creative project today. Feelings ARE data for the artist.",
  "Aug 7": "Romance built on soul connection, creative devotion, and tender vulnerability fulfills your deepest need.",
  "Aug 8": "A creative partner who honors your sensitivity produces something neither could create alone.",
  "Aug 9": "Your space becomes a gallery of your emotional truth: art that reveals your inner landscape.",
  "Aug 10": "Your courage to feel everything fully while others numb themselves IS your defining feature.",
  "Aug 11": "A bold creative share — publishing a poem, showing a painting, performing — reveals your brave soul.",
  "Aug 12": "Summer near water energizes your spirit at the cellular level. Swim, float, or simply sit by the shore.",
  "Aug 13": "Your devoted emotional approach to everything you love is itself a form of art.",
  "Aug 14": "Summer's creative peak invites your most ambitious artistic expression. Create the dream.",
  "Aug 15": "Mid-August: your creative-intuitive power is at maximum. Channel it into lasting beauty.",
  "Aug 16": "Emotional feedback from someone your art has touched confirms the power of vulnerable creation.",
  "Aug 17": "Your intuitive long-view sees emotional and creative trends years before they manifest.",
  "Aug 18": "Evening by water — ocean, pool, or candlelit bath — is your soul's renewable energy source.",
  "Aug 19": "Late summer hints at autumn's reflective depth. Your water nature prepares for quiet, deep creating.",
  "Aug 20": "The shift toward more analytical energy helps you refine raw emotional expression into polished art.",
  "Aug 21": "Summer creations solidify into a body of work. Document your artistic journey.",
  "Aug 22": "Virgo energy approaches. Your opposite sign's detail asks your oceanic visions to find precise form.",
  "Aug 23": "Virgo season begins. Practical refinement shapes your boundless creativity into communicable art.",
  "Aug 24": "Your sweeping emotional visions receive gentle editorial attention. Form serves feeling.",
  "Aug 25": "Health routines for your sensitive system: gentle, nourishing, and respectful of your emotional body.",
  "Aug 26": "Attention to craft improves your art's impact. Technique serves the emotion you want to convey.",
  "Aug 27": "Organizing your creative works creates a portfolio of your emotional and spiritual journey.",
  "Aug 28": "Daily practices that honor your sensitive nature: meditation, creative time, and protective solitude.",
  "Aug 29": "Service through healing, creative offering, and compassionate presence fulfills your Neptunian purpose.",
  "Aug 30": "Practical creative habits — daily practice, regular output — give your mystical gifts worldly presence.",
  "Aug 31": "August ends with your creative gifts refined, your emotional courage proven, and your art ready.",

  // ── September ──
  "Sep 1": "September channels your creative water energy into focused, refined artistic practice.",
  "Sep 2": "Health routines for your sensitive system: gentle exercises, clean foods, and plenty of rest.",
  "Sep 3": "A creative audit: what have you made this year? What needs finishing? What wants to be born next?",
  "Sep 4": "Your empathic nature makes daily interactions unexpectedly meaningful. Every exchange is connection.",
  "Sep 5": "Detailed creative refinement produces improvements that broad imagination missed. Edit with care.",
  "Sep 6": "Your sensitive body needs gentle, nourishing fuel. Avoid harsh or artificial ingredients.",
  "Sep 7": "Healing service flows naturally from you. Offer gentle care where it's needed most today.",
  "Sep 8": "A health practice that honors your emotional sensitivity becomes a permanent self-care ritual.",
  "Sep 9": "Daily creative practice — even twenty minutes — keeps your artistic channel open and flowing.",
  "Sep 10": "A meal prepared with love and beautiful presentation is art for the body. Cook with intention.",
  "Sep 11": "Your empathic perspective helps others process difficult emotions. Be the gentle witness.",
  "Sep 12": "A creative or spiritual partner reminds you that shared vulnerability deepens artistic power.",
  "Sep 13": "Organization of your creative works and spiritual practices creates a map of your soul's journey.",
  "Sep 14": "Your sensitivity health check: are you protecting your energy? Creating enough? Resting enough?",
  "Sep 15": "Gentle fitness — yoga, swimming, tai chi — supports your sensitive body without overwhelming it.",
  "Sep 16": "Your compassionate guidance helps someone process emotions they've been avoiding. You hold space.",
  "Sep 17": "A routine update that protects creative and spiritual time refreshes your entire being.",
  "Sep 18": "Creative planning during this practical season gives mystical visions workable timelines.",
  "Sep 19": "Virgo season's detail has refined your emotional expression into more precise, impactful art.",
  "Sep 20": "A practical creative achievement demonstrates that dreams can take solid, beautiful form.",
  "Sep 21": "Autumn equinox. Balance between your inner ocean and the outer world. Both need your attention.",
  "Sep 22": "Libra season begins. Beauty and partnership harmonize perfectly with your aesthetic soul.",
  "Sep 23": "Relationships deepen through your empathic attention and creative expressions of love.",
  "Sep 24": "A partnership flourishes when you share your emotional truth with artistic grace.",
  "Sep 25": "Balanced relationships honor both your need for solitude and your capacity for deep connection.",
  "Sep 26": "Beauty in all forms — art, nature, music, love — is your spiritual language. Speak it fluently.",
  "Sep 27": "Your diplomatic gifts emerge when empathy guides your words toward harmony and healing.",
  "Sep 28": "A partner loves your sensitivity and creative depth. Someone sees and cherishes your true nature.",
  "Sep 29": "Partnership that provides emotional safety without emotional suffocation is the Piscean ideal.",
  "Sep 30": "September refined your creative gifts into more accessible, more beautiful, more shareable form.",

  // ── October ──
  "Oct 1": "October's deepening energy feeds your already oceanic emotional and creative depths.",
  "Oct 2": "Relationships reveal spiritual truths when you attune empathically to your partner's unspoken needs.",
  "Oct 3": "A beautiful, emotionally resonant experience — museum, concert, autumn walk — nourishes your soul.",
  "Oct 4": "Your reputation for genuine empathy and creative sensitivity is your most valued gift.",
  "Oct 5": "A creative partnership deepens when both partners share from the most vulnerable places.",
  "Oct 6": "Your ability to shift emotional atmosphere through your gentle presence is genuine magic.",
  "Oct 7": "Balance between solitary creative time and intimate partnership requires daily negotiation.",
  "Oct 8": "Your compassionate honesty heals emotional wounds that pretense kept festering. Gentle truth heals.",
  "Oct 9": "An autumn evening of music, candlelight, and deep emotional conversation is your paradise.",
  "Oct 10": "Seasonal transition activates your awareness of impermanence. Every moment is precious art.",
  "Oct 11": "A long-term creative project — a collection, a series, a body of work — deserves renewed devotion.",
  "Oct 12": "Your appreciation for beauty across cultures feeds the universal compassion that defines you.",
  "Oct 13": "Autumn cooking with warming, nourishing ingredients is a love letter to your physical self.",
  "Oct 14": "A creative breakthrough dissolves what felt blocked. The art was waiting for you to feel ready.",
  "Oct 15": "Your emotional depth grows with autumn's reflective quality. Deeper feelings produce deeper art.",
  "Oct 16": "A creative gift — handmade, heartfelt, or spiritually meaningful — is the most Piscean gesture.",
  "Oct 17": "Your autumn space should feel like a cozy retreat: warm, soft, and filled with beautiful things.",
  "Oct 18": "Emotional truth in relationships deepens when you trust someone with your most tender feelings.",
  "Oct 19": "Evening near water under autumn moonlight connects your Piscean nature to cosmic rhythm.",
  "Oct 20": "Scorpio season approaches. Deep emotional transformation prepares you for the most creative depths.",
  "Oct 21": "An artistic or spiritual event delivers an experience that changes your inner landscape.",
  "Oct 22": "Scorpio season begins. Fellow water sign energy validates and deepens your emotional approach.",
  "Oct 23": "Creative depth meets emotional intensity. Your art accesses places few artists ever reach.",
  "Oct 24": "An uncomfortable emotional truth surfaces. Your water nature can hold it. Feel it, then release.",
  "Oct 25": "Your psychic perception, always present, sharpens during Scorpio's water season. Trust it fully.",
  "Oct 26": "Intimate creative and emotional sharing produces profound vulnerability and profound beauty.",
  "Oct 27": "Shared creative or financial resources benefit from emotionally honest, intuitive assessment.",
  "Oct 28": "Your capacity for emotional transformation is oceanic: you can dissolve old pain and reconstitute joy.",
  "Oct 29": "The deeper you feel, the more powerful your art becomes. Depth is your creative advantage.",
  "Oct 30": "Internal emotional transformation ripples outward as healing energy touching everyone around you.",
  "Oct 31": "Your costume reveals your mystical nature: the oracle, the mermaid, the shapeshifter, the dream.",

  // ── November ──
  "Nov 1": "November deepens everything, including your already oceanic emotional and creative life.",
  "Nov 2": "Honor those who touched your soul. Artists, healers, lovers, and spiritual teachers across your life.",
  "Nov 3": "A creative breakthrough through emotional depth produces art that makes people cry and heal.",
  "Nov 4": "Shared creative resources and deep partnerships produce work that transcends individual capacity.",
  "Nov 5": "Trust built through emotional vulnerability runs deeper than trust built through shared interests.",
  "Nov 6": "Emotional investment — the deep, scary, boundless kind — is what you were born for. Dive in.",
  "Nov 7": "Your resilience is fluid: you recover by flowing around obstacles and dissolving pain into art.",
  "Nov 8": "A profound truth about love and surrender surfaces. Real love requires real letting go.",
  "Nov 9": "Dreams during Scorpio season carry messages from your deepest intuitive knowing. Honor them.",
  "Nov 10": "An emotional transformation ripples into your creative work, making everything more authentic.",
  "Nov 11": "Remember the artists, healers, and mystics who shaped your creative path. Their art lives in yours.",
  "Nov 12": "Financial decisions guided by values rather than fear produce intuitively correct results.",
  "Nov 13": "Your creative depth during water season produces art that will mean more with every passing year.",
  "Nov 14": "Psychic boundaries protect your sensitive nature without blocking the empathy you're designed for.",
  "Nov 15": "Halfway through November, your emotional depths have been explored. New creative territory found.",
  "Nov 16": "Holding emotional complexity without needing resolution is advanced spiritual practice.",
  "Nov 17": "A private creative project generates the most vulnerable, most powerful work of your year.",
  "Nov 18": "An emotional challenge resolves through your characteristically compassionate approach.",
  "Nov 19": "Release emotional patterns that no longer serve your growth. Let the old tide go out.",
  "Nov 20": "Sagittarius season approaches. Philosophical fire warms your emotional depths productively.",
  "Nov 21": "Adventurous energy challenges your quiet nature to share your gifts with a wider audience.",
  "Nov 22": "Faith and feeling combine. Your spirituality takes on optimistic, expansive qualities.",
  "Nov 23": "Holiday season begins with your sensitive, creative touch making everything more beautiful.",
  "Nov 24": "Thanksgiving resonates deeply. Gratitude is your natural spiritual practice, not just a holiday.",
  "Nov 25": "Your creative gifts — handmade, heartfelt, spiritually charged — carry more love than any purchase.",
  "Nov 26": "Compassionate presence during holiday gatherings makes you the emotional heart of every group.",
  "Nov 27": "Your gentle nature during social events creates safe space for others to be authentic.",
  "Nov 28": "Gratitude for your sensitive, creative, mystical nature fills your evening with warm light.",
  "Nov 29": "A creative vision set during the dreaming season carries your most authentic spiritual truth.",
  "Nov 30": "November ends with emotionally intelligent creativity flowing stronger than any other time this year.",

  // ── December ──
  "Dec 1": "December's mystical energy builds toward your most spiritually powerful creative season.",
  "Dec 2": "Holiday magic IS your element. Your Piscean nature thrives in wonder, beauty, and generosity.",
  "Dec 3": "A creative, handmade, or spiritually meaningful gift carries more love than any store-bought luxury.",
  "Dec 4": "Holiday decorating with Piscean sensitivity: soft lights, natural elements, and dreamy beauty.",
  "Dec 5": "Winter's dreamy quality matches your mystical nature perfectly. The veil thins with every dark night.",
  "Dec 6": "Holiday cooking infused with love and creative flair turns meals into spiritual nourishment.",
  "Dec 7": "Your gentle presence at holiday gatherings creates warmth that everyone feels but no one can name.",
  "Dec 8": "A holiday gift chosen intuitively for someone lands with the precision of empathic understanding.",
  "Dec 9": "Year-end spiritual review: how has your soul grown? What has your art revealed about your path?",
  "Dec 10": "Holiday decorating with Piscean taste: ethereal, dreamy, and soft as moonlight on water.",
  "Dec 11": "Your home during December feels like a fairy tale: warm, magical, and gently glowing.",
  "Dec 12": "Creative rest during the holiday season isn't laziness — it's the tide drawing back before rushing forward.",
  "Dec 13": "Winter's reflective energy feeds your most introspective creative depths. Dream inward.",
  "Dec 14": "Your holiday generosity flows from your boundless compassion. Give what heals, not just what shines.",
  "Dec 15": "Year-end creative highlights reveal more beauty, more depth, and more healing art than ever before.",
  "Dec 16": "A quiet evening of music or meditation during the busy season returns you to your center.",
  "Dec 17": "Your emanation of peace at holiday gatherings is the greatest gift you give, without even trying.",
  "Dec 18": "Your season approaches from behind winter's veil. Can you feel Neptune's creative tide rising?",
  "Dec 19": "Your emotional truth, creative courage, and spiritual depth have carried you beautifully this year.",
  "Dec 20": "Art created with love and patience outlasts everything made from ambition alone. You know this.",
  "Dec 21": "Winter solstice. In the deepest darkness, your mystical light shines like a beacon on the water.",
  "Dec 22": "Capricorn season provides structure for your dreams. Let form support your boundless feeling.",
  "Dec 23": "Holiday preparations benefit from your intuitive sense of what will make people feel loved.",
  "Dec 24": "Tonight, your sensitive soul feels the magic in the air more intensely than anyone. Let it fill you.",
  "Dec 25": "Today, receive love, beauty, and the knowledge that your gentle presence is someone's greatest gift.",
  "Dec 26": "Post-holiday quiet is your sanctuary. Restore your empathic reserves with beautiful solitude.",
  "Dec 27": "Your year-end journal should flow like a dream diary — images, feelings, symbols, and creative revelations.",
  "Dec 28": "A New Year intention forms: deeper art, wider compassion, and braver creative vulnerability.",
  "Dec 29": "Your art, your empathy, and your spiritual depth are the three pillars of this year. All shimmer.",
  "Dec 30": "Tomorrow the year ends. Tonight, let gratitude flow through you like warm water. You've felt so much.",
  "Dec 31": "The year closes with you standing in your full, luminous sensitivity. Dreaming, feeling, and creating beauty endlessly. Happy new year, Pisces.",
};
