/** 365 daily quotes for Sagittarius — one for every day of the year. */
export const sagittariusDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, new adventure. Set intentions that honor your need for freedom AND your hunger for meaning.",
  "Jan 2": "Your optimistic vision already sees this year's possibilities stretching to the horizon. Aim your arrow high.",
  "Jan 3": "A morning ritual that includes learning or inspiration sets your adventurous tone. Read, explore, grow.",
  "Jan 4": "Your living space should reflect your travels, your philosophies, and your love of the world.",
  "Jan 5": "Someone needs your uplifting honesty today. Your blunt truth-telling is a gift when wrapped in warmth.",
  "Jan 6": "Jupiter's expansive energy fuels your year. Think bigger than practical. Think legendary.",
  "Jan 7": "A philosophical conversation over coffee fires up your morning better than caffeine ever could.",
  "Jan 8": "Your bluntness isn't rudeness — it's radical honesty. But today, soften the delivery.",
  "Jan 9": "Financial freedom is your version of luxury. One strategic step toward independence today.",
  "Jan 10": "Your teaching instinct lights up. Share what you've learned — your enthusiasm is contagious.",
  "Jan 11": "Commitment feels like a cage sometimes. Today, find the freedom within structure — it exists.",
  "Jan 12": "Your broad perspective reveals connections others miss. Write down the insight before it gallops away.",
  "Jan 13": "Home is wherever your heart expands. But even nomads need a base — tend yours today.",
  "Jan 14": "Your mutable fire nature means your passions change direction — and that's exploration, not fickleness.",
  "Jan 15": "Midmonth wanderlust check: where does your soul want to travel? Plan it, even if it's just a day trip.",
  "Jan 16": "Outdoor adventure, even in winter, is your church. Fresh air and open space are your sacrament.",
  "Jan 17": "A project benefits from your big-picture vision. You see the forest while others count trees.",
  "Jan 18": "Self-improvement through travel, study, or cultural exploration is your lifelong love affair.",
  "Jan 19": "Your humor can defuse any tension. Deploy the jokes today — laughter is your diplomacy.",
  "Jan 20": "A mutable sign's adaptability shows today. Plans change? New plans are just new adventures.",
  "Jan 21": "Something developing in your philosophical understanding will reshape your worldview. Stay curious.",
  "Jan 22": "Your generous spirit gives freely, but ensure your own reserves aren't depleted by over-giving.",
  "Jan 23": "The meaningful work of your life combines purpose with adventure. Both are non-negotiable.",
  "Jan 24": "A childhood love of exploration still drives you. Follow that same curious impulse today.",
  "Jan 25": "Your infectious enthusiasm inspires someone to take a leap they've been avoiding.",
  "Jan 26": "Financial planning for future adventures makes the practical side of freedom real.",
  "Jan 27": "World music, international cuisine, and global perspectives feed your ever-hungry mind.",
  "Jan 28": "Your mutable fire nature means you burn in many directions at once. Focus concentrates your flame.",
  "Jan 29": "An act of philosophical generosity — sharing wisdom, recommending a life-changing book — fulfills you.",
  "Jan 30": "A documentary, memoir, or travel film expands your world tonight. Knowledge is your adventure.",
  "Jan 31": "January ends with your arrow aimed at the horizon. The adventure of this year has officially begun.",

  // ── February ──
  "Feb 1": "February asks your expansive nature to focus on intimate connections alongside grand visions.",
  "Feb 2": "Your philosophical insight today reveals truth that rote thinking couldn't reach. Trust your broad view.",
  "Feb 3": "A creative expression of your worldview — writing, teaching, storytelling — inspires others to dream bigger.",
  "Feb 4": "Your space needs an element of the exotic: a global artifact, a travel photo, or a world map.",
  "Feb 5": "Emotional honesty doesn't come as naturally as philosophical honesty. Practice the personal kind today.",
  "Feb 6": "Your fire sign nature craves movement and expansion. Plan a trip, a hike, or a new experience.",
  "Feb 7": "Someone needs your optimistic perspective. Your faith in life's goodness is genuinely healing.",
  "Feb 8": "Your inner teacher sometimes drowns out your inner student. Today, learn more than you teach.",
  "Feb 9": "Enthusiasm shared with genuine passion makes ordinary conversations extraordinary.",
  "Feb 10": "Your social nature thrives in diverse groups. Seek people different from you today.",
  "Feb 11": "Travel souvenirs, books, and maps aren't clutter — they're your autobiography in objects.",
  "Feb 12": "Your love language is adventure — shared experiences that expand the soul together.",
  "Feb 13": "Pre-Valentine: your idea of romance involves grand adventures, philosophical connection, and spontaneous joy.",
  "Feb 14": "Love for Sagittarius is a journey without a destination. Today, enjoy exactly where you are with someone.",
  "Feb 15": "After Valentine's intensity, your wandering spirit needs open space. Take a long walk with no destination.",
  "Feb 16": "Your connection to Jupiter fuels expansive thinking. Dream without limits today.",
  "Feb 17": "An international recipe or cuisine experiment satisfies your wanderlust without a plane ticket.",
  "Feb 18": "Your broad perspective is your gift. What you see from altitude gives everyone else direction.",
  "Feb 19": "Restlessness surfaces. Check: is this genuine need for adventure, or avoidance of something deeper?",
  "Feb 20": "Emotional depth in a relationship requires the one adventure that scares you: staying put.",
  "Feb 21": "Your dreams carry you to places you've never been. Some are travel invitations. Follow them.",
  "Feb 22": "Confidence rooted in faith — in yourself, in life, in the universe — is your unshakable foundation.",
  "Feb 23": "A travel companion or philosophical friend reminds you that shared exploration multiplies joy.",
  "Feb 24": "Your moods expand and contract like breathing. Wide joy, deep reflection, and back again.",
  "Feb 25": "Your mutable nature allows you to find the adventure in any situation. Even mundane days hold discovery.",
  "Feb 26": "Bold, colorful clothing that reflects your vibrant spirit changes the entire energy of your day.",
  "Feb 27": "Your ability to find meaning in suffering AND joy is uniquely Sagittarian. Both teach you.",
  "Feb 28": "February taught you that the deepest adventures happen within the heart, not on the map.",
  "Feb 29": "Rare day, rare freedom. Do something you've never done. The whole point is newness.",

  // ── March ──
  "Mar 1": "Spring awakens your perennial wanderlust. The roads are calling — even if they're local.",
  "Mar 2": "Your philosophical wisdom guides a decision that narrow thinking couldn't solve. Trust the big picture.",
  "Mar 3": "Refuel your adventure reserves before planning the next expedition. Rest is part of the journey.",
  "Mar 4": "Your broad awareness today reveals a connection between unrelated things. That's your genius.",
  "Mar 5": "A creative expression of your worldview — writing, speaking, filming — reaches an appreciative audience.",
  "Mar 6": "Your travel companions, philosophical friends, and growth partners deserve celebration today.",
  "Mar 7": "Jupiter expands your evening thoughts. Dream of distant places, big ideas, and boundless horizons.",
  "Mar 8": "Teaching leadership means lighting the way, not dragging people forward. Inspire by example.",
  "Mar 9": "A handwritten postcard, even to yourself, captures the spirit of a Sagittarian heart in transit.",
  "Mar 10": "Your home should feel like a launching pad: comfortable, inspiring, and always ready for departure.",
  "Mar 11": "Emotional vulnerability in relationships is the one frontier you sometimes avoid. Explore it.",
  "Mar 12": "Your mutable nature finds new routes when old paths are blocked. Adaptability is your compass.",
  "Mar 13": "Open spaces — parks, fields, mountains, or just an open window — expand your contracted spirit.",
  "Mar 14": "Your love of truth doesn't mean you must speak every one. Timing is part of honesty too.",
  "Mar 15": "Nourishing your body for the journey ahead is practical adventure prep. Eat for energy.",
  "Mar 16": "A spontaneous detour today leads to an experience you didn't know you needed.",
  "Mar 17": "Your luck is legendary because you say 'yes' more than most. Luck favors the adventurous.",
  "Mar 18": "Your ideal home includes a library, a world map, and the scent of somewhere far away.",
  "Mar 19": "Spring equinox approaches. The balance point fires your restless Sagittarian spirit into new orbits.",
  "Mar 20": "Spring equinox. Renewal ignites your fire. The world is reborn, and so is your sense of possibility.",
  "Mar 21": "Aries season activates fellow fire energy. Creativity, play, and passionate self-expression explode.",
  "Mar 22": "Your playful nature ignites. Life doesn't have to be a philosophy lecture — sometimes it's a game.",
  "Mar 23": "A creative project benefits from your expansive vision. Dream it wide, then fill in the details.",
  "Mar 24": "Romance and adventure merge beautifully. Take someone special on an unexpected side quest.",
  "Mar 25": "Your authentic self-expression requires no filter today. Be the arrow: sharp, direct, true.",
  "Mar 26": "Bold creative moves honor your fire nature. Start the project, book the trip, make the call.",
  "Mar 27": "Your fear of missing out sometimes prevents going deep. Today, choose depth over breadth.",
  "Mar 28": "A creative or romantic alliance benefits from your contagious enthusiasm. Fire up someone's spirit.",
  "Mar 29": "Joy and meaning aren't opposites. The most profound experiences are often the most joyful.",
  "Mar 30": "Your entertaining storytelling makes every experience twice as vivid. Tell a great story today.",
  "Mar 31": "March ends with your fire burning bright and your compass pointing toward new horizons.",

  // ── April ──
  "Apr 1": "April Fool's energy is your natural habitat. Humor, pranks, and lighthearted chaos — you thrive.",
  "Apr 2": "Your social enthusiasm fills every room with warmth. People expand in your presence.",
  "Apr 3": "A friendship deepens through shared adventure — a hike, a road trip, a new restaurant.",
  "Apr 4": "Group dynamics reveal your role: morale booster, vision-caster, and the one who says 'why not?'",
  "Apr 5": "Your wish for the future is global, philosophical, and impossibly optimistic. Never shrink it.",
  "Apr 6": "Social energy surges. Your warmth and humor create connections that feel like mini-adventures.",
  "Apr 7": "A cause that promotes education, freedom, or cross-cultural understanding deserves your fire today.",
  "Apr 8": "Your friends span countries, cultures, and belief systems. That diversity IS your richness.",
  "Apr 9": "An innovative philosophical idea surfaces. It's too big for others but perfectly sized for you.",
  "Apr 10": "Your protective instincts activate for freedom — yours and everyone's. Advocate loudly.",
  "Apr 11": "Spring's wild growth mirrors your expansive nature. Spread in every direction like wildflowers.",
  "Apr 12": "Group settings energize you when ideas are flying. Seek the brainstorm, not the small talk.",
  "Apr 13": "A grand vision crystallizes through optimistic imagination and bold philosophical thinking.",
  "Apr 14": "Your humanitarian instinct says: freedom and education change everything. Start with one person.",
  "Apr 15": "Financial decisions benefit from your ability to see long-term potential others miss.",
  "Apr 16": "Your read on group energy inspires the right joke at the right moment. Comedy timing is a gift.",
  "Apr 17": "Jupiter expands your evening contemplations. Stargaze and imagine beyond what you can see.",
  "Apr 18": "Your need for freedom balances with growing appreciation for connection. Both expand you.",
  "Apr 19": "Taurus season approaches. Earth energy asks your fire to slow down and savor the moment.",
  "Apr 20": "Your restless fire meets grounded pleasure. Can you enjoy THIS moment without looking ahead?",
  "Apr 21": "Quality food savored slowly is an adventure for your senses. Taste the journey in every bite.",
  "Apr 22": "Earth Day connects your philosophical nature with the physical world that holds your adventures.",
  "Apr 23": "Your hosting involves spontaneity, bold flavors, and conversations that jump between continents.",
  "Apr 24": "Material comfort isn't a trap. It's the basecamp from which expeditions launch. Build yours.",
  "Apr 25": "Sensory pleasure — good food, live music, warm sun — doesn't require analysis. Just enjoy.",
  "Apr 26": "Your patience is tested when grounded energy asks you to wait. Some adventures need preparation.",
  "Apr 27": "A treasured travel memento carries the energy of an experience that changed your worldview.",
  "Apr 28": "Your projects — real or metaphorical — show growth when you let them develop at their own pace.",
  "Apr 29": "Evening reflection on where you've traveled — physically and philosophically — reveals vast distance covered.",
  "Apr 30": "April ends with your fire grounded and your optimism informed. Ready for the next adventure.",

  // ── May ──
  "May 1": "May grounds your fire nature. Earthy stability supports your grand adventures.",
  "May 2": "Your body expresses your adventurous spirit. It wants to run, stretch, and carry you to new places.",
  "May 3": "An enthusiastic recommendation transforms someone's reading list, travel plans, or worldview.",
  "May 4": "Financial grounding creates the freedom fund that makes future adventures possible. Practical magic.",
  "May 5": "Your space benefits from global touches: a Turkish rug, Japanese ceramics, Ethiopian coffee.",
  "May 6": "Past adventures remind you of your capacity for wonder. Revisit a transformative memory today.",
  "May 7": "An international meal prepared at home satisfies wanderlust through flavor and cultural connection.",
  "May 8": "Your knowledge reserves overflow. Share your latest fascination with an eager listener.",
  "May 9": "Your body craves adventure fuel: high energy, diverse cuisines, and bold flavors.",
  "May 10": "Your mentoring nature combines encouragement with honest assessment. Your proteges thrive.",
  "May 11": "Traditions of exploration and learning define your personal culture. Pass them on.",
  "May 12": "Your presence elevates any gathering from mundane to memorable. Walk in with your full fire.",
  "May 13": "A home improvement that adds global or philosophical elements enriches your daily inspiration.",
  "May 14": "Love expressed through shared adventures and honest conversation speaks your heart's language.",
  "May 15": "Your broad perspective navigates a narrow situation with surprising ease. Zoom out for truth.",
  "May 16": "Outdoor time — hiking, cycling, or simply walking with purpose — is your meditation practice.",
  "May 17": "A bookshelf filled with diverse subjects tells the story of a mind that never stops exploring.",
  "May 18": "Your restlessness surfaces. Is it time to plan an adventure or time to practice presence?",
  "May 19": "A bonfire evening — friends, stories, and stars — feeds your primal fire sign soul.",
  "May 20": "A gift chosen from your travels or your knowledge carries the spirit of adventure.",
  "May 21": "Gemini season begins. Your opposite sign's curious energy matches your philosophical hunger.",
  "May 22": "Your broad vision meets detailed communication. Grand ideas find precise, shareable words.",
  "May 23": "A stimulating conversation jumps between topics — and you love every tangent. Follow them all.",
  "May 24": "Your teaching and learning skills activate simultaneously. Every conversation is a classroom.",
  "May 25": "Social energy sparkles through quick-witted exchanges and intellectual adventures.",
  "May 26": "Your storytelling reaches peak entertainment. Hold court and share the tales that shaped you.",
  "May 27": "Learning something entirely new — a language, a skill, a subject — satisfies your perpetual hunger.",
  "May 28": "Local exploration during Gemini season reveals adventures in your own neighborhood.",
  "May 29": "Your mind races with connected ideas tonight. Journal the philosophical threads before they scatter.",
  "May 30": "Movement that goes somewhere — walking to a destination, cycling a new route — aligns body with spirit.",
  "May 31": "May ends with intellectual stimulation fueling your philosophical fire beautifully.",

  // ── June ──
  "Jun 1": "June's light energy matches your bright, expansive outlook. The world is vivid and available.",
  "Jun 2": "Your verbal enthusiasm is irresistible. Every description of your latest passion recruits converts.",
  "Jun 3": "A grand idea finds clear, communicable form. Write it, pitch it, share it — it's ready.",
  "Jun 4": "Your curiosity about everything — literally everything — leads to an unexpected discovery today.",
  "Jun 5": "A quick trip or spontaneous outing delivers more adventure per hour than you expected.",
  "Jun 6": "A philosophical friend matches your intellectual energy perfectly. The conversation goes cosmic.",
  "Jun 7": "Your hands create something inspired by a cultural tradition you've studied. Cross-pollination art.",
  "Jun 8": "Partnership energy builds. Summer asks your free spirit to explore commitment as its own adventure.",
  "Jun 9": "Direct, honest communication clears the air more effectively than diplomatic dance. Be you.",
  "Jun 10": "Your philosophical mind and your practical instincts agree today. The vision IS the plan.",
  "Jun 11": "A book, podcast, or lecture on travel, philosophy, or world culture feeds your eternal hunger.",
  "Jun 12": "Your evening routine should leave room for spontaneity. Structured freedom — your paradox.",
  "Jun 13": "Summer approaches, and your energy expands with the light. Adventures multiply ahead.",
  "Jun 14": "Your connection to Jupiter intensifies as the year's midpoint approaches. Expand everything.",
  "Jun 15": "Halfway through the year: have you explored enough? Learned enough? Said 'yes' enough?",
  "Jun 16": "A spirited dinner with adventurous friends is your ideal gathering. Big food, bigger ideas.",
  "Jun 17": "Your honest speech patterns occasionally need a filter. Today, truth plus tact equals impact.",
  "Jun 18": "Golden hour spent outdoors is your soul's renewable energy source. Soak it up.",
  "Jun 19": "Summer adventure planning reaches fever pitch. Maps, lists, dreams — line them all up.",
  "Jun 20": "Summer solstice eve. The longest light illuminates your path to the year's biggest adventure.",
  "Jun 21": "Summer solstice. Maximum daylight fuels your maximum expansion. The fire sign thrives in the light.",
  "Jun 22": "Cancer season begins. Emotional depth invites your philosophical fire to tend the home hearth.",
  "Jun 23": "Home can be an adventure too. Transform your space with something from a faraway place.",
  "Jun 24": "Emotional honesty with family creates the security your free spirit secretly needs.",
  "Jun 25": "Your nurturing side expresses through teaching, inspiring, and expanding others' worldviews.",
  "Jun 26": "A family story reveals philosophical depth you hadn't noticed before. Your roots have wisdom.",
  "Jun 27": "A home-cooked meal from a culture you love bridges your wanderlust with your nesting needs.",
  "Jun 28": "Your emotional intuition, usually overshadowed by your intellect, speaks clearly today. Listen.",
  "Jun 29": "A quiet evening feels appropriate when it includes a great book or an evocative film.",
  "Jun 30": "June ends with emotional depth adding roots to your usually airborne philosophical nature.",

  // ── July ──
  "Jul 1": "July asks for emotional connection alongside intellectual exploration. Feel, don't just think.",
  "Jul 2": "Your emotional avoidance pattern is gently challenged. Can you stay present with a feeling?",
  "Jul 3": "Home as adventure base: comfortable, inspiring, and stocked with global treasures.",
  "Jul 4": "Freedom and belonging can coexist. Today, find liberty in love, not apart from it.",
  "Jul 5": "Emotional honesty is the one journey you sometimes postpone. Today, start the trek inward.",
  "Jul 6": "Kitchen adventure with an unfamiliar cuisine turns cooking into cultural exploration.",
  "Jul 7": "Family wisdom, passed in stories and traditions, contains the philosophy you've been seeking.",
  "Jul 8": "Trust your emotional gut today. Your instincts aren't just intellectual — they're primal.",
  "Jul 9": "Vulnerability isn't a trap. It's the price of admission to the deepest human experience.",
  "Jul 10": "An emotional intention set now carries your Jupiter-sized heart behind it. Feel it fully.",
  "Jul 11": "Your fierce devotion to freedom also applies to the freedom of those you love. Liberate someone today.",
  "Jul 12": "Ancestral stories carry philosophical gold. Ask an older family member about their adventures.",
  "Jul 13": "Your restless energy needs physical outlets today. Run, hike, dance, or ride. Move big.",
  "Jul 14": "Water activities under summer sun combine cooling with adventure. Swim, kayak, or splash.",
  "Jul 15": "Mid-July: your emotional landscape is richer than usual. Feelings add color to philosophy.",
  "Jul 16": "A creative project with emotional depth surprises you with its power. Vulnerability creates art.",
  "Jul 17": "Your space transformation this month should honor both adventure and comfort. Base camp luxury.",
  "Jul 18": "Financial planning that includes a travel fund brings your dreams closer to reality.",
  "Jul 19": "Leo's fire season approaches. Fellow fire energy amplifies your courage and creative expression.",
  "Jul 20": "Evening storytelling — campfire style or kitchen table — is your natural spiritual practice.",
  "Jul 21": "Emotional processing through philosophical framing helps you understand what you feel and why.",
  "Jul 22": "Leo season begins. Creative fire meets philosophical fire. Your expression becomes passionate art.",
  "Jul 23": "Your creative vision, already expansive, gains Leo's bold confidence. Create fearlessly.",
  "Jul 24": "Playful expression of your big ideas makes philosophy accessible and entertaining. Teach through fun.",
  "Jul 25": "Your inner child is an explorer — curious, fearless, and delighted by newness. Let them lead.",
  "Jul 26": "Romantic adventure during Leo season: spontaneous trips, surprise dates, and passionate honesty.",
  "Jul 27": "A creative collaboration with a fellow fire sign or kindred spirit produces something spectacular.",
  "Jul 28": "Heart-centered creative expression gives your philosophy emotional power. Ideas need feeling.",
  "Jul 29": "Joy as philosophy: maybe the meaning of life IS the capacity for wild, unbridled happiness.",
  "Jul 30": "Dramatic expression of your truth isn't exaggeration — it's accurate representation of your fire.",
  "Jul 31": "July ends with emotional depth and creative fire enriching your philosophical worldview.",

  // ── August ──
  "Aug 1": "August's creative peak activates your storytelling gifts. Every experience becomes an epic.",
  "Aug 2": "Creative-philosophical projects shine: books, courses, travel writing, or inspirational speaking.",
  "Aug 3": "Your mentoring combines entertainment with education. You make learning feel like an adventure.",
  "Aug 4": "A playful philosophical challenge — a debate, a thought experiment — makes your day.",
  "Aug 5": "Joy in discovery: every new fact, every novel perspective, every surprising connection delights.",
  "Aug 6": "Your broadly informed mind serves a creative project today. Cross-disciplinary thinking is your edge.",
  "Aug 7": "Romance filled with spontaneity, honest passion, and shared adventure fulfills your fiery heart.",
  "Aug 8": "A creative collaborator matches your energy and pushes your ideas further. Partnership elevates.",
  "Aug 9": "Your space becomes a gallery of your adventures: photos, artifacts, and stories on every surface.",
  "Aug 10": "Your courage to speak honestly, live openly, and love freely is your defining feature.",
  "Aug 11": "A bold creative share — publishing, performing, or exhibiting — puts your vision into the world.",
  "Aug 12": "Sunshine and outdoor adventure feed your fire nature at the cellular level. Get outside.",
  "Aug 13": "Your enthusiastic devotion to ideas, people, and experiences is itself a form of art.",
  "Aug 14": "Summer's peak invites peak adventure. Plan or execute the boldest experience of the season.",
  "Aug 15": "Mid-August: your creative-philosophical fire is at maximum. Channel it into something lasting.",
  "Aug 16": "Enthusiastic feedback from someone you've inspired confirms the power of your teaching gift.",
  "Aug 17": "Your strategic broadmindedness serves long-term vision brilliantly. You plan in decades, not days.",
  "Aug 18": "Evening adventure — a new restaurant, an outdoor concert, or a spontaneous road trip — satisfies.",
  "Aug 19": "Late summer whispers of autumn's philosophical depth. Your fire prepares for wisdom season.",
  "Aug 20": "The transition toward more reflective energy feels like preparation for your approaching season.",
  "Aug 21": "Summer adventures crystallize into stories you'll tell for years. Capture the best ones.",
  "Aug 22": "Virgo energy approaches. Detail supports your broad vision — the arrows need precision too.",
  "Aug 23": "Virgo season begins. Practical refinement sharpens your philosophical arrows to fine points.",
  "Aug 24": "Your expansive ideas get organized structure. Plans become actionable when details align.",
  "Aug 25": "Health routines support your adventurous lifestyle. Your body is your adventure vehicle — maintain it.",
  "Aug 26": "Attention to detail improves your teaching, writing, and communication. Precision adds credibility.",
  "Aug 27": "Organizing your knowledge — notes, books, experiences — creates a wisdom library for future reference.",
  "Aug 28": "Daily practices that support your fire nature: exercise, learning, and intentional social connection.",
  "Aug 29": "Service through education and inspiration fulfills your Jupiter-guided purpose.",
  "Aug 30": "Practical adventure planning turns dreams into itineraries. The best journeys begin with good maps.",
  "Aug 31": "August ends with your expansive nature refined and your creative fire purposefully directed.",

  // ── September ──
  "Sep 1": "September channels your adventurous fire into focused, productive learning.",
  "Sep 2": "Health routines support the demanding pace your adventurous lifestyle requires.",
  "Sep 3": "A knowledge audit: what have you learned this year? What's missing? Fill the philosophical gaps.",
  "Sep 4": "Your enthusiasm for sharing knowledge makes you a natural teacher in daily interactions.",
  "Sep 5": "A detailed exploration of a philosophical idea produces insights that broad thinking missed.",
  "Sep 6": "Your body needs fuel for adventure: wholesome, energizing, and varied as your interests.",
  "Sep 7": "Service through joyful teaching helps more than solemn instruction. Make learning fun.",
  "Sep 8": "A health habit that supports your active lifestyle becomes a permanent upgrade.",
  "Sep 9": "Daily contact with something that expands your mind — a podcast, a book, a conversation — is essential.",
  "Sep 10": "An internationally inspired meal prepared with care bridges your love of world culture and daily joy.",
  "Sep 11": "Your broad philosophical perspective helps others find meaning in difficulty. Share your faith.",
  "Sep 12": "A travel companion, study buddy, or philosophical partner reminds you how shared exploration multiplies joy.",
  "Sep 13": "Organization of your knowledge and travel memories creates a resource for future adventures.",
  "Sep 14": "Your adventure health check: are you exploring enough? Learning enough? Living broadly enough?",
  "Sep 15": "Health and adventure align: the fitter you are, the bigger the adventure you can handle.",
  "Sep 16": "Your enthusiastic guidance helps someone take a leap they've been afraid to take. You're their arrow.",
  "Sep 17": "A routine update that makes room for spontaneous learning and exploration refreshes your spirit.",
  "Sep 18": "Your travel planning during the practical season produces workable itineraries for grand visions.",
  "Sep 19": "Virgo season has refined your approach. Your arrows now fly straighter and land more precisely.",
  "Sep 20": "A practical achievement in service of your bigger vision confirms that details matter too.",
  "Sep 21": "Autumn equinox. Philosophical balance: what you know versus what you've yet to discover.",
  "Sep 22": "Libra season begins. Partnership and beauty add grace to your bold adventures.",
  "Sep 23": "Relationships benefit from your honest, enthusiastic attention. Love is an adventure too.",
  "Sep 24": "A partnership deepens when you share your philosophical discoveries with genuine excitement.",
  "Sep 25": "Balanced relationships give your free spirit a beautiful place to return to.",
  "Sep 26": "Beauty and philosophy intersect. The sublime — nature, art, music — is philosophy made visible.",
  "Sep 27": "Your diplomatic skills emerge when your honest nature learns to speak truth through beauty.",
  "Sep 28": "A partner's appreciation for your adventurous spirit touches your freedom-loving heart.",
  "Sep 29": "Balance between freedom and partnership is possible. It looks like mutual support for growth.",
  "Sep 30": "September refined your philosophical fire into something more precise and more beautiful.",

  // ── October ──
  "Oct 1": "October's deepening atmosphere adds philosophical weight to your usually buoyant perspective.",
  "Oct 2": "Relationships reveal deeper truths when you slow down enough to really listen.",
  "Oct 3": "An aesthetically rich experience — museum, concert, autumn landscape — provokes philosophical insight.",
  "Oct 4": "Your reputation for honest enthusiasm is your most valuable social currency.",
  "Oct 5": "A partnership adventure — travel, study, or shared exploration — deepens your bond.",
  "Oct 6": "Your ability to make any location feel like the start of an adventure is genuine magic.",
  "Oct 7": "Balance between your independence and your love: both need tending and both need space.",
  "Oct 8": "Your enthusiastic honesty heals a wound that polite distance couldn't. Truth is medicine.",
  "Oct 9": "An autumn evening of big questions, bold ideas, and warm conversation is your paradise.",
  "Oct 10": "Seasonal transition activates philosophical reflection. What does this season teach about impermanence?",
  "Oct 11": "A long-term project — a book, a course, a life philosophy — deserves renewed commitment.",
  "Oct 12": "Your cultural appreciation honors the diversity that makes the world an endless adventure.",
  "Oct 13": "Autumn cooking with bold flavors from various cuisines celebrates your love of global culture.",
  "Oct 14": "A philosophical breakthrough simplifies what used to feel complicated. Truth is often simple.",
  "Oct 15": "Your philosophical courage grows with the season. Bigger questions deserve bolder answers.",
  "Oct 16": "A gift of a book, experience, or adventure ticket is the most Sagittarian gesture possible.",
  "Oct 17": "Your autumn space should feel like a study and a launchpad: warm, inspiring, full of possibility.",
  "Oct 18": "Truth in relationships deepens when you're as honest about feelings as you are about ideas.",
  "Oct 19": "Evening stargazing connects your philosophical nature to the cosmos. You are THAT big.",
  "Oct 20": "Depth approaches as Scorpio season draws near. Your philosophy is about to go underground.",
  "Oct 21": "A cultural or educational event delivers an insight that reshapes your thinking beautifully.",
  "Oct 22": "Scorpio season begins. Deep transformation challenges your usual optimistic buoyancy.",
  "Oct 23": "Philosophical depth meets emotional intensity. Your broad view gets a deep-water lens.",
  "Oct 24": "An uncomfortable truth about your avoidance pattern surfaces. Face it — it's the adventure you need.",
  "Oct 25": "Your intuition, usually focused outward on possibilities, turns inward with unusual precision.",
  "Oct 26": "Intimacy challenges your freedom reflex. The deepest exploration happens with another soul.",
  "Oct 27": "Financial or shared investment decisions benefit from deep rather than broad analysis.",
  "Oct 28": "Your capacity for philosophical transformation: can you let a cherished belief die to be reborn?",
  "Oct 29": "The deeper you go, the more you discover. Not all adventure is horizontal. Some digs down.",
  "Oct 30": "Internal philosophical transformation is as big an adventure as crossing continents.",
  "Oct 31": "Your costume should tell a story of adventure: the explorer, the philosopher, the mythic hero.",

  // ── November ──
  "Nov 1": "November deepens everything, including your philosophical convictions. Examine beneath the surface.",
  "Nov 2": "Honor those who expanded your worldview. Teachers, mentors, and guides across your lifetime.",
  "Nov 3": "An emotional breakthrough through philosophical understanding integrates head and heart.",
  "Nov 4": "Shared resources and deep partnerships benefit from your honest philosophical assessment.",
  "Nov 5": "Trust built through radical honesty runs deeper than trust built through agreement.",
  "Nov 6": "Emotional vulnerability — the adventure you sometimes avoid — rewards you with unprecedented connection.",
  "Nov 7": "Your resilience is philosophical: you bounce back because you find meaning in every chapter.",
  "Nov 8": "A profound truth about freedom and responsibility surfaces. Real freedom includes accountability.",
  "Nov 9": "Deep dreams carry messages about your evolving philosophy of life. Journal the symbols.",
  "Nov 10": "A transformation in worldview ripples into every area of life. You see everything differently now.",
  "Nov 11": "Remember the teachers, adventurers, and truth-seekers who shaped your arrow. Their aim lives in you.",
  "Nov 12": "Financial wisdom built through philosophical understanding of value, not just numbers.",
  "Nov 13": "Your philosophical depth during Scorpio season produces ideas that will take years to fully explore.",
  "Nov 14": "Boundaries based on philosophical clarity protect your energy and your freedom.",
  "Nov 15": "Halfway through November, your worldview has evolved. Some beliefs have been beautifully destroyed.",
  "Nov 16": "Holding philosophical complexity without needing resolution is a sign of wisdom. Sit with questions.",
  "Nov 17": "A private philosophical project generates ideas that will eventually change how you teach and live.",
  "Nov 18": "YOUR SEASON IS ALMOST HERE. Can you feel Jupiter gathering your energy for the year's peak?",
  "Nov 19": "A philosophical challenge resolves through your characteristically honest approach.",
  "Nov 20": "Release outdated beliefs that no longer serve your expanding truth. Make room for new philosophy.",
  "Nov 21": "SAGITTARIUS SEASON BEGINS! The sun enters your sign. Maximum optimism, adventure, and expansion.",
  "Nov 22": "Happy Sagittarius season! Your cosmic birthday month activates your brightest fire.",
  "Nov 23": "Your season's Thanksgiving energy aligns perfectly: gratitude is your truest philosophy.",
  "Nov 24": "Holiday gatherings become philosophical salons under your enthusiastic guidance. Talk about everything.",
  "Nov 25": "Traditions from various cultures blended into your celebrations reflect your global heart.",
  "Nov 26": "Your philosophical generosity overflows. Share wisdom, stories, and inspiration freely.",
  "Nov 27": "Adventure during your season carries extra magic. Every trip, every exploration, every new idea is amplified.",
  "Nov 28": "Your optimism during your season isn't naive — it's a philosophical stance backed by experience.",
  "Nov 29": "A grand vision set during your season has Jupiter's full support behind it. Dream legendarily.",
  "Nov 30": "November ends in YOUR fire. Sagittarius season is in full blaze. The philosopher-adventurer reigns.",

  // ── December ──
  "Dec 1": "December continues your powerful season. Holidays AND your cosmic birthday month — maximum joy.",
  "Dec 2": "Your birthday season combined with holiday energy creates double celebration. You were made for this.",
  "Dec 3": "A philosophical gift — a meaningful book, a course enrollment — carries more weight than material luxury.",
  "Dec 4": "Your birthday season gifts should include experiences: tickets, trips, and transformative adventures.",
  "Dec 5": "Winter's philosophical quietude contrasts beautifully with your fiery season. Fire on snow.",
  "Dec 6": "Holiday cooking becomes a global exploration. Every recipe is a passport stamp on a plate.",
  "Dec 7": "Family gatherings during your season feature your storytelling at its finest. Hold court.",
  "Dec 8": "A birthday or holiday gift that symbolizes your next adventure is the perfect Sagittarian present.",
  "Dec 9": "Year-end philosophical review: what did you learn, where did you grow, and where does the arrow point next?",
  "Dec 10": "Holiday decorating reflects your global aesthetic: ornaments from travels, lights with meaning.",
  "Dec 11": "Your home during December buzzes with your birthday-season energy: warm, expansive, and joyful.",
  "Dec 12": "Even rest can be an adventure during your season. Explore dreams, books, and inner landscapes.",
  "Dec 13": "A celebratory gathering combines holiday cheer with birthday fire. Double the joy.",
  "Dec 14": "Your seasonal generosity is legendary. Give wisdom, experiences, and your infectious optimism.",
  "Dec 15": "The year's adventure highlight reel shows more exploration, more learning, and more living than ever.",
  "Dec 16": "A quiet philosophical evening during your busy season refreshes your ever-hungry mind.",
  "Dec 17": "Your storytelling at holiday gatherings makes you the main event. Every tale is better with your fire.",
  "Dec 18": "The final days of Sagittarius season concentrate your power. What last grand gesture will you make?",
  "Dec 19": "Freedom during the holidays means the liberty to celebrate, connect, and be your fullest self.",
  "Dec 20": "Your year of adventure and growth has been extraordinary. Bolder, wiser, and more joyfully alive.",
  "Dec 21": "Winter solstice. The darkest night asks your fire to burn for what matters most. It always does.",
  "Dec 22": "Capricorn season begins. Structure meets your vision — you're ready to build on your adventures.",
  "Dec 23": "Holiday prep meets your legendary spontaneity. The best moments aren't planned — they're sparked.",
  "Dec 24": "Tonight, your warm fire gathers people together. Your enthusiasm is the holiday itself.",
  "Dec 25": "Today, receive adventures, books, and experiences. Let others fuel your next chapter.",
  "Dec 26": "Post-holiday adventuring — a hike, a new film, a philosophical deep-dive — is your recovery style.",
  "Dec 27": "Your year-end journal should read like a travelogue of the mind. Document the philosophical miles.",
  "Dec 28": "A New Year intention forms: even bigger adventures, deeper philosophy, and braver honesty.",
  "Dec 29": "Your adventures, your wisdom, and your joy are the three pillars of this year. All stand tall.",
  "Dec 30": "Tomorrow the year ends. Tonight, raise a glass to every adventure, every truth, and every laugh.",
  "Dec 31": "The year closes with you standing in your full, fiery optimism. Free, wise, and boundlessly alive. Happy new year, Sagittarius.",
};
