/** 365 daily quotes for Scorpio — one for every day of the year. */
export const scorpioDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New year, deep intentions. Set goals that honor your relentless drive for transformation and truth.",
  "Jan 2": "Your penetrating insight already sees what this year requires. Trust the knowing that lives in your depths.",
  "Jan 3": "A powerful morning ritual — meditation, journaling, or breathwork — anchors your intense energy.",
  "Jan 4": "Your private space is your regeneration chamber. Make it dark, comfortable, and deeply yours.",
  "Jan 5": "Someone needs your unwavering support today. Your loyalty in a crisis is legendary.",
  "Jan 6": "Pluto's transformative power stirs beneath your surface. What needs to die so something new can live?",
  "Jan 7": "A deep conversation cuts through small talk to reach truth. You don't do surface — dive.",
  "Jan 8": "Your protective intensity isn't paranoia — it's survival intelligence. Trust your radar.",
  "Jan 9": "Financial strategy comes naturally to you. Your ability to see hidden value is your edge.",
  "Jan 10": "Your research skills are unmatched. Whatever you investigate today, you'll find the buried truth.",
  "Jan 11": "Control is your comfort zone and your cage. Today, practice surrendering one thing to the unknown.",
  "Jan 12": "Your loyalty runs ocean-deep. Ensure the people receiving it are worthy of that sacred commitment.",
  "Jan 13": "Home as fortress. Your space should feel impenetrable — the one place your guard can drop.",
  "Jan 14": "Your emotional intensity is not too much. It's exactly the right amount for the depth you seek.",
  "Jan 15": "Midmonth power check: where are you giving your power away? Reclaim it silently and completely.",
  "Jan 16": "Water heals your water sign soul. A long, hot bath is therapy, meditation, and rebirth in one.",
  "Jan 17": "A project benefits from your obsessive focus today. Your intensity turns average into extraordinary.",
  "Jan 18": "Self-transformation through shadow work is your spiritual practice. Face one shadow today.",
  "Jan 19": "Your silence speaks volumes. Sometimes saying nothing is the most powerful move.",
  "Jan 20": "A fixed sign's determination at its fiercest: once you commit, nothing in this world stops you.",
  "Jan 21": "Something transforming in your inner world will soon break the surface. Let it rise.",
  "Jan 22": "Your trust, once broken, rarely repairs. But today, consider that forgiveness frees you more than them.",
  "Jan 23": "The passionate work of your life deserves the same obsessive focus you give everything that matters.",
  "Jan 24": "A childhood wound still holds power. Today, look at it not as damage but as origin story.",
  "Jan 25": "Your magnetic presence commands attention without trying. Today, use that pull consciously.",
  "Jan 26": "Financial power comes through understanding what others overlook. Your detective eye sees value everywhere.",
  "Jan 27": "Privacy is not secrecy — it's self-preservation. Protect your inner world from careless observation.",
  "Jan 28": "Your fixed water nature means emotions run deep and hold firm. That's not stubbornness — it's depth.",
  "Jan 29": "An act of profound generosity today surprises everyone. Your giving side is as intense as your other sides.",
  "Jan 30": "A mystery, thriller, or deeply psychological experience feeds your soul tonight.",
  "Jan 31": "January ends with your power intact and growing. You've descended into your depths and found strength.",

  // ── February ──
  "Feb 1": "February stirs your deepest romantic longings. You don't want love — you want soul fusion.",
  "Feb 2": "Your x-ray vision today sees through facades to the truth beneath. Trust what you perceive.",
  "Feb 3": "A creative expression of your intensity — dark art, passionate writing, raw music — releases pressure.",
  "Feb 4": "Your private space needs to feel like a cocoon of transformation. Dark, warm, and protected.",
  "Feb 5": "Emotional boundaries are your moat. Build them with intention: they protect your kingdom.",
  "Feb 6": "Your water nature craves emotional depth even in casual interactions. Seek it today.",
  "Feb 7": "Someone needs your transformative honesty. Deliver truth with compassion, not as a weapon.",
  "Feb 8": "Your regenerative power means you can rebuild from anything. Remember that when doubt creeps in.",
  "Feb 9": "Passionate words spoken in private mean more than public declarations. Whisper your truth.",
  "Feb 10": "Your magnetic intensity draws people without effort. Be discerning about who gets close.",
  "Feb 11": "Mementos of transformation — symbols of what you survived — are your trophies. Honor them.",
  "Feb 12": "Your love is all-consuming, all-or-nothing. Today, channel that intensity wisely.",
  "Feb 13": "Pre-Valentine: your idea of romance involves soul-baring, electrifying connection, and absolute devotion.",
  "Feb 14": "Love for Scorpio is a journey to the underworld and back. Today, let someone journey with you.",
  "Feb 15": "Post-Valentine emotional processing goes deep. You felt everything. Now integrate it.",
  "Feb 16": "Your connection to Pluto drives transformation. What old skin are you ready to shed?",
  "Feb 17": "A meal cooked with passionate intention carries your energy. Everything you touch transforms.",
  "Feb 18": "Your investigative skills uncover truth today. What you find might be uncomfortable but necessary.",
  "Feb 19": "Jealousy or possessiveness surfaces. Examine it: is it genuine threat detection or old wound activation?",
  "Feb 20": "Emotional honesty at its most raw: tell someone exactly how you feel. No editing. No diplomacy.",
  "Feb 21": "Your dream life is a direct line to your subconscious. Tonight's messages are important. Write them down.",
  "Feb 22": "Power built on self-knowledge never fades. The deeper you know yourself, the more formidable you become.",
  "Feb 23": "A trusted confidant receives a truth you've been carrying alone. Sharing lightens the load.",
  "Feb 24": "Your moods run deep and intense but shift like underground rivers. Ride the current, don't fight it.",
  "Feb 25": "Your fixed nature means you hold emotional positions firmly. Today, check if any need updating.",
  "Feb 26": "Black, deep red, or midnight blue in your wardrobe channels your power visually. Wear it.",
  "Feb 27": "Your ability to hold both destruction and creation simultaneously is uniquely Scorpio. Phoenix energy.",
  "Feb 28": "February taught you about the power of vulnerable honesty. Your depths are your greatest asset.",
  "Feb 29": "Rare day, rare depth. Name the desire you've been afraid to admit. Naming it gives you power over it.",

  // ── March ──
  "Mar 1": "Spring stirs restlessness in your depths. Transformation energy builds — something wants to emerge.",
  "Mar 2": "Your emotional intelligence solves a problem that surface-level thinking couldn't touch.",
  "Mar 3": "Regenerate your own reserves before pouring power into others' transformations.",
  "Mar 4": "Your psychic awareness is heightened today. You sense undercurrents others completely miss.",
  "Mar 5": "A creative outlet for your intensity prevents emotional buildup. Create something raw and real.",
  "Mar 6": "The people who've earned your trust know how rare and precious that gift is. Appreciate them.",
  "Mar 7": "Pluto stirs your evolution tonight. Transformation usually starts as an uncomfortable feeling. Let it be.",
  "Mar 8": "Your transformative leadership shows. You help people become who they're meant to be.",
  "Mar 9": "A deeply personal message from you carries the weight of absolute sincerity. Send one.",
  "Mar 10": "Your home should reflect your depth: moody lighting, rich textures, and spaces for private retreat.",
  "Mar 11": "Emotional vulnerability in a trusted relationship creates the merging you crave. Risk being seen.",
  "Mar 12": "Your phoenix nature knows: sometimes the indirect path through destruction leads to greater creation.",
  "Mar 13": "Deep water — ocean, lake, or bathtub — restores your soul to equilibrium. Submerge yourself.",
  "Mar 14": "Your love of mystery isn't escapism. It's a quest for truth hidden beneath the obvious.",
  "Mar 15": "Nourishing your dark side with understanding, not suppression, creates wholeness.",
  "Mar 16": "A transformation happening just below your awareness is about to break through. Stay ready.",
  "Mar 17": "Your luck comes through instinct and timing. The stinger strikes when the moment is right.",
  "Mar 18": "Your ideal home is a bunker of transformation: private, powerful, and unapologetically intense.",
  "Mar 19": "Spring approaches and even the phoenix feels the pull of rebirth. What version of you emerges?",
  "Mar 20": "Spring equinox. Death and rebirth on nature's stage. You understand this cycle better than any sign.",
  "Mar 21": "Aries season ignites your work ethic and daily routines. Passionate focus on health and craft.",
  "Mar 22": "Your ambition stirs with fiery energy. The phoenix rises with new determination and drive.",
  "Mar 23": "A health or work matter benefits from your investigative thoroughness. Research deeply.",
  "Mar 24": "Daily routines infused with passionate intention transform mundane life into sacred practice.",
  "Mar 25": "Your private self and public image merge when you're authentic about your intensity.",
  "Mar 26": "Obsessive focus on health or a project yields breakthrough results. Your persistence pays off.",
  "Mar 27": "Your fear of vulnerability sometimes manifests as control. Today, release grip on one thing.",
  "Mar 28": "A work collaboration benefits from your transformative vision. You see potential others miss.",
  "Mar 29": "Power and service aren't opposites. Use your formidable energy to help someone transform.",
  "Mar 30": "Your contribution today may go unnoticed, but its impact runs deeper than anyone knows.",
  "Mar 31": "March ends with transformative energy building. Something in you is ready to emerge reborn.",

  // ── April ──
  "Apr 1": "Even the intense Scorpio has a darkly funny side. Let your wicked humor play today.",
  "Apr 2": "Your emotional radar picks up shifts others miss completely. Trust your deep perception.",
  "Apr 3": "A friendship deepens when you share something from your hidden depths. Trust earns trust.",
  "Apr 4": "Group dynamics reveal your natural role: the power behind the throne, the unseen strategist.",
  "Apr 5": "Your wish for the future is built on radical transformation and uncompromising truth.",
  "Apr 6": "Social energy is selective for you. One deep conversation trumps a room full of small talk.",
  "Apr 7": "A cause involving justice, transformation, or exposing truth deserves your formidable energy.",
  "Apr 8": "Your trusted inner circle is small and fierce. Today, honor those few with your deepest loyalty.",
  "Apr 9": "A transformative idea surfaces from your subconscious. It's radical, uncomfortable, and necessary.",
  "Apr 10": "Your protective instincts for your inner circle rival a scorpion's ferocity. Guard what matters.",
  "Apr 11": "Spring's rebirth energy mirrors your phoenix nature. You're shedding old skin — let it fall.",
  "Apr 12": "Social settings work for you when depth is available. Seek the corner conversations, not the crowd.",
  "Apr 13": "A dream or vision for transformation crystallizes through emotional courage and radical honesty.",
  "Apr 14": "Your humanitarian side shows through transformative justice. You fight for what's right in the shadows.",
  "Apr 15": "Financial intelligence deepens. Your ability to see hidden value makes you a natural strategist.",
  "Apr 16": "Your perception of group dynamics prevents a power play. You see the chess board others can't.",
  "Apr 17": "Pluto whispers transformative messages tonight. Sit in darkness and listen to what wants to emerge.",
  "Apr 18": "Your need for privacy battles any pressure to share. Your depths are yours to reveal — or not.",
  "Apr 19": "Taurus season approaches. Your opposite sign's grounding energy stabilizes your intense depths.",
  "Apr 20": "Your intensity meets earthy pleasure. Ground your transformative energy through sensory satisfaction.",
  "Apr 21": "Quality food prepared with passionate intention satisfies body and soul simultaneously.",
  "Apr 22": "Earth connects you to the physical world your water sign sometimes transcends. Touch, taste, feel.",
  "Apr 23": "Your hosting style is intimate and intentional: few guests, deep conversation, significant food.",
  "Apr 24": "Financial matters during opposite sign season reveal what you truly value beneath strategy.",
  "Apr 25": "Sensory grounding — massage, warm food, earthy textures — anchors your intense emotions.",
  "Apr 26": "Your patience with deep transformation is tested. Trust: the metamorphosis has its own timeline.",
  "Apr 27": "A valued possession represents a transformative period. It's not just an object — it's a survival token.",
  "Apr 28": "Your garden — real or metaphorical — shows that even buried things can grow toward light.",
  "Apr 29": "Evening grounding through physical comfort balances your day's emotional intensity.",
  "Apr 30": "April ends with deep transformation meeting earthly stability. The phoenix builds a nest.",

  // ── May ──
  "May 1": "May grounds your transformative energy. Earthy stability supports deep emotional work.",
  "May 2": "Your body holds emotional truth in its depths. Tension, heat, or stillness — listen to the messages.",
  "May 3": "A quietly powerful gesture transforms someone's perception completely. Your influence is volcanic.",
  "May 4": "Financial security built through strategic insight brings the power-base you need for deeper work.",
  "May 5": "Your space benefits from sensory richness: velvet, candles, and dark, lush textures.",
  "May 6": "Past transformations remind you of your regenerative power. You've survived everything. Remember.",
  "May 7": "A meal cooked with passionate focus carries your transformative energy. Others taste the intention.",
  "May 8": "Your emotional reserves are deep enough to hold space for someone else's crisis today.",
  "May 9": "Your body craves nourishment that matches your intensity: bold flavors, deep reds, powerful spices.",
  "May 10": "Your transformative influence on others is usually invisible. Today, notice the ripples you create.",
  "May 11": "Traditions of survival and transformation define your personal mythology. Honor your phoenix story.",
  "May 12": "Your magnetic presence commands attention without trying. Walk into a room and feel the shift.",
  "May 13": "A home improvement that adds depth and privacy — better curtains, moodier lighting — enhances your sanctuary.",
  "May 14": "Love expressed through unflinching emotional presence speaks louder than grand gestures.",
  "May 15": "Your emotional intelligence navigates a complex interpersonal dynamic with strategic grace.",
  "May 16": "Deep water heals you. A swim, a bath, or time by a body of water restores your equilibrium.",
  "May 17": "A treasured object from a pivotal transformation holds power for you. It's not just nostalgia — it's a talisman.",
  "May 18": "Your controlling tendencies surface. Ask yourself: am I protecting something real, or just afraid?",
  "May 19": "Evening solitude in darkness isn't loneliness — it's your recharging station. Embrace the dark.",
  "May 20": "A gift chosen with intimate knowledge of someone's hidden self shows love through deep seeing.",
  "May 21": "Gemini season begins. Your deep emotional intelligence meets nimble mental communication.",
  "May 22": "Your depth meets breadth of expression. You can finally articulate what usually stays unspoken.",
  "May 23": "A conversation about emotional truth goes deeper than expected. Gemini energy gives your depths a voice.",
  "May 24": "Your ability to articulate transformation and complexity helps someone understand their own journey.",
  "May 25": "Social settings that allow deep one-on-one conversations within larger gatherings suit you perfectly.",
  "May 26": "Your listening goes beyond hearing — you perceive what isn't said. Today, that skill changes a dynamic.",
  "May 27": "Research, investigation, or deep learning feeds your relentless hunger for hidden knowledge.",
  "May 28": "A neighborhood or community matter benefits from your strategic perception. You see the real issue.",
  "May 29": "Your subconscious messages become verbal tonight. Journal the insights before they submerge again.",
  "May 30": "Movement with intensity — martial arts, powerful swimming, intense hiking — matches your energy.",
  "May 31": "May ends with deep truths finding clearer expression. Your intensity now has eloquence.",

  // ── June ──
  "Jun 1": "June lightens the atmosphere, but your depths remain YOUR domain. Surface when you choose.",
  "Jun 2": "Your verbal power intensifies. Words spoken with Scorpio conviction can transform or destroy. Choose wisely.",
  "Jun 3": "An idea about transformation, power dynamics, or hidden truth crystallizes. Pursue it.",
  "Jun 4": "Your curiosity about human psychology is insatiable. Today, an insight into motivation satisfies it.",
  "Jun 5": "Short journeys or local explorations reveal hidden gems — your favorite kind of discovery.",
  "Jun 6": "A conversation with someone who matches your emotional depth creates rare, electric connection.",
  "Jun 7": "Your hands create with intensity today — detailed research, powerful writing, or transformative work.",
  "Jun 8": "Relationship energy builds. Summer asks your fixed water nature to flow toward partnership.",
  "Jun 9": "Deep communication repairs what surface pleasantries couldn't. Say the uncomfortable true thing.",
  "Jun 10": "Your mind and emotional instincts align today. Perception and analysis point to the same truth.",
  "Jun 11": "A book or film about psychological depth or hidden worlds feeds your soul completely.",
  "Jun 12": "Your evening ritual should honor your need for darkness, quiet, and private regeneration.",
  "Jun 13": "Summer energy builds while you maintain your preferred depth. Not everything needs sunlight.",
  "Jun 14": "Your psychic perception intensifies with the longer days. You see more, feel more, know more.",
  "Jun 15": "Halfway through the year: what have you transformed? What transformation remains? Assess honestly.",
  "Jun 16": "An intimate dinner with one significant person feeds you more than any party.",
  "Jun 17": "Your fierce protection of what matters accelerates. Summer isn't all lightness — some things need guarding.",
  "Jun 18": "Water time — ocean, pool, rain — connects you to your elemental source. Immerse yourself.",
  "Jun 19": "Transformative energy builds toward its summer peak. Something is about to change — permanently.",
  "Jun 20": "Summer solstice eve. The longest light reveals what you've been hiding — even from yourself.",
  "Jun 21": "Summer solstice. Maximum exposure challenges your private nature. What truth can the light show?",
  "Jun 22": "Cancer season begins. Fellow water energy validates your emotional depth. You feel understood.",
  "Jun 23": "Home and emotional security take center stage. Build your fortress of intimacy and trust.",
  "Jun 24": "Emotional truth-telling with family or close partners creates the safety you need to transform.",
  "Jun 25": "Your nurturing side — fierce, protective, and uncompromising — shows in how you guard loved ones.",
  "Jun 26": "Family patterns visible through your x-ray perception can now be consciously transformed.",
  "Jun 27": "A family gathering where you feel emotionally safe allows your rarely-seen softer side to emerge.",
  "Jun 28": "Your intuition about family dynamics is profound. Trust what you sense beneath the pleasantries.",
  "Jun 29": "A solitary evening by or in water restores your emotional equilibrium completely.",
  "Jun 30": "June ends with emotional depth meeting familial love. Your waters and Cancer's merge beautifully.",

  // ── July ──
  "Jul 1": "July asks for emotional nurturing from a sign that sometimes equates vulnerability with danger.",
  "Jul 2": "Emotional expression in your closest bond deepens the merger you crave. Risk tenderness.",
  "Jul 3": "Home as emotional power center: create spaces that hold your intensity and your softness.",
  "Jul 4": "True freedom for Scorpio is emotional liberation — the freedom to feel everything without fear.",
  "Jul 5": "Emotional honesty with yourself about what you truly want creates unstoppable direction.",
  "Jul 6": "Kitchen alchemy with passionate intensity transforms simple ingredients into something profound.",
  "Jul 7": "Family patterns from the past offer transformative insight. What cycle are you here to break?",
  "Jul 8": "Trust your deepest instincts today. Your gut has survived everything — it's trustworthy.",
  "Jul 9": "Vulnerability isn't weakness for the most powerful sign. It's the ultimate show of strength.",
  "Jul 10": "An emotional intention set now carries the power of your full depth. Be specific in your desire.",
  "Jul 11": "Your loyalty to family and intimate partners is unwavering. Let them feel the depth of your devotion.",
  "Jul 12": "Ancestral patterns, family secrets, and inherited power — your DNA carries transformative potential.",
  "Jul 13": "Your intensity needs release today. Physical exertion, deep conversation, or creative catharsis.",
  "Jul 14": "Water of every kind restores you: ocean, river, rain, tears. Don't hold back what needs to flow.",
  "Jul 15": "Mid-July: your emotional nature is softened by Cancer's nurturing. Allow tenderness its full expression.",
  "Jul 16": "A creative project informed by emotional depth carries transformative power. Share it selectively.",
  "Jul 17": "Your space should feel like a womb of transformation — dark, warm, safe, and profoundly private.",
  "Jul 18": "Financial decisions guided by emotional wisdom, not just strategy, create richer outcomes.",
  "Jul 19": "Leo energy approaches, asking you to reveal more of your power publicly. Prepare to emerge.",
  "Jul 20": "Evening rituals of decompression — bath, darkness, silence — regenerate your formidable energy.",
  "Jul 21": "Emotional journaling reveals what your controlled surface never shows. Write in red ink if it helps.",
  "Jul 22": "Leo season begins. Creative self-expression asks you to transform from private power to visible force.",
  "Jul 23": "Your creative intensity, when given a stage, is unforgettable. Let your depths become art.",
  "Jul 24": "A playful approach to your usually serious nature surprises everyone — including yourself.",
  "Jul 25": "Your inner child is intense too. They don't need lightening — they need passionate play.",
  "Jul 26": "Romance during Leo season asks for visible passion. Your love, usually underground, erupts beautifully.",
  "Jul 27": "A creative partnership meets your standards when it goes past surface to soul. Demand depth.",
  "Jul 28": "Heart-centered creative expression reveals the beauty hiding in your darkness. It's stunning.",
  "Jul 29": "Joy as a transformative force: what if pleasure, not pain, was the catalyst for your next evolution?",
  "Jul 30": "Bold emotional expression isn't betrayal of your private nature. It's a conscious choice to be seen.",
  "Jul 31": "July ends with emotional depth enriching your creative output. Your art carries power.",

  // ── August ──
  "Aug 1": "August's creative warmth challenges your hidden nature to express itself boldly.",
  "Aug 2": "Creative projects shine when your emotional depth meets Leo's courageous expression.",
  "Aug 3": "Your mentoring style is transformative: you see what people can become and push them toward it.",
  "Aug 4": "Playful intensity is uniquely Scorpionic. You make even fun feel meaningful.",
  "Aug 5": "Joy discovered in depth: the satisfaction of understanding what others barely perceive.",
  "Aug 6": "Your powerful emotional intelligence serves a creative vision today. Depth makes art unforgettable.",
  "Aug 7": "Romance that matches your intensity — passionate, all-consuming, utterly devoted — fulfills you.",
  "Aug 8": "A creative collaborator earns your trust by matching your commitment. Partnership of equals.",
  "Aug 9": "Your space becomes a gallery of your transformation journey. Display what represents your evolution.",
  "Aug 10": "Your courage to face what others run from is your defining quality. Face something today.",
  "Aug 11": "A creative risk involving emotional vulnerability produces something devastatingly beautiful.",
  "Aug 12": "Sunlight feels exposing, but today, let the light show what usually hides. You're magnificent in it.",
  "Aug 13": "Your devotion is fierce and absolute. The art of how you love could fill volumes.",
  "Aug 14": "Summer's peak intensity meets your natural state. You feel at home in the heat.",
  "Aug 15": "Mid-August: your creative and emotional power combine for maximum impact. Use it wisely.",
  "Aug 16": "Feedback from someone who truly sees your depth validates what you secretly hoped was true.",
  "Aug 17": "Your strategic mind serves creative projects brilliantly. You play the long game — even in art.",
  "Aug 18": "Evening intensity — a gripping film, a deep conversation, or passionate connection — satisfies your soul.",
  "Aug 19": "Your season approaches on the horizon. Can you feel your power concentrating, preparing?",
  "Aug 20": "The transition toward autumn — your natural season — feels like coming home to yourself.",
  "Aug 21": "Summer's lessons about visibility and creative courage prepare you for your transformation season.",
  "Aug 22": "Virgo energy approaches. Analytical refinement meets your emotional depth productively.",
  "Aug 23": "Virgo season begins. Your transformative vision gets detailed, practical support. Powerful combination.",
  "Aug 24": "Health practices that support your intense emotional nature: exercise, nutrition, rest, release.",
  "Aug 25": "A wellness protocol that addresses your tendency to hold tension transforms your physical energy.",
  "Aug 26": "Your detail-oriented focus during this season produces work of exceptional quality and depth.",
  "Aug 27": "Organizing your transformation process with Virgo's precision creates sustainable metamorphosis.",
  "Aug 28": "Daily practices that support emotional release prevent unhealthy buildup. Move, write, or speak it.",
  "Aug 29": "Service through transformation: you help others heal by your willingness to go into the darkness first.",
  "Aug 30": "Practical self-care — nutrition, exercise, routine — supports the immense emotional work you do.",
  "Aug 31": "August ends with your power refined and your creative courage expanded. The phoenix preens.",

  // ── September ──
  "Sep 1": "September channels your intense energy into productive, refined expression.",
  "Sep 2": "Health routines support the immense emotional processing your sign does constantly.",
  "Sep 3": "A deep purge — possessions, habits, old identities — creates space for approaching transformation.",
  "Sep 4": "Your transformative influence shows in daily acts: sharp insight, precise help, unflinching honesty.",
  "Sep 5": "A detail-oriented investigation reveals what's hidden. Your research-and-destroy approach works.",
  "Sep 6": "Your body needs fuel that matches your intensity: protein, spices, deep nourishment.",
  "Sep 7": "Service through honest, transformative feedback helps someone more than comfortable lies.",
  "Sep 8": "A health-focused adjustment supports your emotional intensity. Strong body, deep soul.",
  "Sep 9": "Daily rituals create the container for your power. Without structure, intensity scatters.",
  "Sep 10": "Strategic meal preparation fuels your capacity for sustained emotional and mental work.",
  "Sep 11": "Your ability to sit with collective grief without flinching is rare and essential today.",
  "Sep 12": "A trusted partner — human or animal — knows your real face. Their unconditional loyalty mirrors yours.",
  "Sep 13": "Organization of your private world creates the order that lets your depths flow freely.",
  "Sep 14": "Your emotional health check: are you processing or suppressing? Release is always the healthier path.",
  "Sep 15": "Practical self-care supports your emotional intensity. You can't do deep work on an empty tank.",
  "Sep 16": "Your insight into someone's hidden struggle helps them more than they'll ever fully realize.",
  "Sep 17": "A routine change — new workout, different relaxation method — refreshes your intense energy.",
  "Sep 18": "Your private space should support your approaching power season. Prepare your transformation chamber.",
  "Sep 19": "Virgo season has refined your approach to transformation. More precise, more sustainable.",
  "Sep 20": "A practical accomplishment built on emotional intelligence proves that depth has tangible results.",
  "Sep 21": "Autumn arrives — your season of power. Feel the energy gathering like storm clouds.",
  "Sep 22": "Libra season begins. Partnership energy asks you to balance your intensity with harmony.",
  "Sep 23": "Relationships benefit from vulnerability, not just intensity. Show softness alongside your strength.",
  "Sep 24": "A partnership conversation goes deeper when you lead with honesty rather than control.",
  "Sep 25": "Balance between power and partnership, between depth and grace. Both are possible today.",
  "Sep 26": "Beauty and depth together. The most beautiful things you've ever seen had darkness in them too.",
  "Sep 27": "Your diplomatic skills emerge when you choose transformation over domination in a conflict.",
  "Sep 28": "A partner's appreciation for your depth touches where surface compliments can't reach.",
  "Sep 29": "Balance between control and surrender in relationships creates the merger you seek.",
  "Sep 30": "September taught you that refined transformation is more powerful than chaotic upheaval.",

  // ── October ──
  "Oct 1": "October is the gateway to your power season. The veil thins, and you feel it in your bones.",
  "Oct 2": "Your relationships enter their truest phase. Superficial connections naturally fall away.",
  "Oct 3": "A dark, beautiful aesthetic experience — film noir, moody music, candlelit space — feeds your soul.",
  "Oct 4": "Your reputation for intensity either attracts or intimidates. Either way, authenticity wins.",
  "Oct 5": "A partnership built on radical honesty reaches new depth this month. Truth deepens love.",
  "Oct 6": "Your ability to transform any environment from ordinary to atmospheric is supernatural.",
  "Oct 7": "Balance between your fierce independence and your need for merger plays out today.",
  "Oct 8": "Your transformative influence heals a wounded dynamic. Your power directed toward healing is medicine.",
  "Oct 9": "An autumn evening of dark beauty — candles, deep music, rich wine — is your temple service.",
  "Oct 10": "The thinning seasonal veil heightens your already-powerful intuition. Trust every psychic hit.",
  "Oct 11": "A legacy project — something that transforms beyond your lifetime — deserves your passionate commitment.",
  "Oct 12": "Your connection to ancestry, death, and transformation makes this season feel like homecoming.",
  "Oct 13": "Autumn cooking with dark, rich ingredients is your elemental practice. Nourish with intensity.",
  "Oct 14": "A power dynamic shifts in your favor because you see what others don't. Strategic vision pays off.",
  "Oct 15": "Your transformative courage builds as your season approaches. The phoenix feels its resurrection coming.",
  "Oct 16": "A gift of deep significance — chosen with intimate knowledge — reveals the depth of your attention.",
  "Oct 17": "Your space during October should be moody, dark, and powerful. Candles, not overhead lights.",
  "Oct 18": "Intimate partnership reaches peak honesty. The naked truth creates the deepest bond.",
  "Oct 19": "Evening meditation reveals what's ready to transform. Listen in the darkness — it speaks your language.",
  "Oct 20": "Your season is upon you. Can you feel the power rising from your depths like magma?",
  "Oct 21": "A transformative realization reshapes something you thought was permanent. You love this.",
  "Oct 22": "Your season begins its approach. The scorpion, the eagle, and the phoenix all stir within you.",
  "Oct 23": "SCORPIO SEASON BEGINS! The sun enters your sign. Your darkest power becomes your brightest light.",
  "Oct 24": "Happy Scorpio season! Your cosmic birthday month activates maximum transformative force.",
  "Oct 25": "Intuition during your season is prophetic. Trust every whisper from the deep.",
  "Oct 26": "Intimacy reaches soul-fusion levels during your season. Love at its most raw and real.",
  "Oct 27": "Financial and emotional power peak during your season. Invest in what transforms.",
  "Oct 28": "Your capacity for rebirth during your season means anything can be transformed. Anything.",
  "Oct 29": "The veil is thinnest now. Your connection to the unseen world is your hidden sixth sense.",
  "Oct 30": "Transformative power concentrates. Today, direct it toward your most important evolution.",
  "Oct 31": "Halloween is YOUR night. The celebration of darkness, death, and transformation belongs to Scorpio.",

  // ── November ──
  "Nov 1": "November continues your powerful season. Dia de los Muertos energy, ancestors, and transformation.",
  "Nov 2": "Honor the departed with the depth they deserve. Your connection to the other side is real and sacred.",
  "Nov 3": "An emotional purge during your season carries extraordinary cleansing power. Let it rip.",
  "Nov 4": "Shared resources, joint finances, and power dynamics during your season require transformative honesty.",
  "Nov 5": "Your trust during your season reaches its most sacred expression. Give it to those who've earned it.",
  "Nov 6": "Vulnerability during your season is your most powerful act. The strongest sign choosing softness.",
  "Nov 7": "Your resilience peaks during your season. Nothing has ever defeated you. Nothing ever will.",
  "Nov 8": "A deeply personal truth spoken during your season has life-changing impact. Speak it.",
  "Nov 9": "Dreams during Scorpio season are prophetic. Write every fragment down. The pattern matters.",
  "Nov 10": "A fundamental transformation in identity crystallizes during your birthday month. You emerge changed.",
  "Nov 11": "Remember the warriors, the survivors, the transformed. Their spirit lives in your sign.",
  "Nov 12": "Financial power built during your season through strategic depth creates lasting security.",
  "Nov 13": "Your inner world during your season is a cathedral of transformation. Honor its sacredness.",
  "Nov 14": "Boundaries set during your season carry the force of a Plutonian command. They stick.",
  "Nov 15": "Halfway through November, your transformation is undeniable. The old you would barely recognize this one.",
  "Nov 16": "Your capacity for holding the most difficult truths with steady eyes is your gift to the world.",
  "Nov 17": "A secret project developed during your season carries extraordinary power. Incubate it.",
  "Nov 18": "Your season's end approaches. The final transformation concentrates and crystallizes.",
  "Nov 19": "A challenging emotional dynamic resolves through the sheer force of your honest vulnerability.",
  "Nov 20": "Release what you've outgrown. The phoenix doesn't cling to ashes — it flies.",
  "Nov 21": "Sagittarius season begins. Fire energy expands your vision beyond personal transformation.",
  "Nov 22": "Travel or philosophical exploration takes your depth global. World-sized transformation.",
  "Nov 23": "Gratitude for your capacity to transform, survive, and regenerate flows powerfully today.",
  "Nov 24": "Your intense presence at holiday gatherings adds depth to otherwise superficial celebrations.",
  "Nov 25": "Traditional practices honored with Scorpio depth become sacred rituals, not just customs.",
  "Nov 26": "Your depth gets philosophical today. Why do you transform so relentlessly? Because that IS life.",
  "Nov 27": "Adventure for Scorpio means exploring the hidden: secret histories, banned books, forbidden knowledge.",
  "Nov 28": "Deep optimism — not naive hope, but faith forged through surviving the worst — is yours.",
  "Nov 29": "A bigger vision includes transformative impact on the world, not just your personal orbit.",
  "Nov 30": "November ends with your power season concluded but your transformation permanent. You are remade.",

  // ── December ──
  "Dec 1": "December's holiday light meets your deep darkness. The contrast creates something magnificent.",
  "Dec 2": "Holiday traditions observed with emotional depth become transformative rituals. Add meaning.",
  "Dec 3": "A philosophical conversation about life, death, and transformation makes the holiday season real.",
  "Dec 4": "Your gifts are always deeply significant — chosen with intimate knowledge and emotional weight.",
  "Dec 5": "Winter's darkness is your natural habitat. The longest nights carry the deepest magic.",
  "Dec 6": "Holiday cooking with passionate intensity transforms ordinary recipes into soul food.",
  "Dec 7": "Family dynamics during holidays reveal the transformative work your presence does. You shift energy.",
  "Dec 8": "A gift of profound personal significance tells someone: I see your hidden self, and I love it.",
  "Dec 9": "Year-end reflection on transformation: what died, what was reborn, what still needs releasing.",
  "Dec 10": "Holiday decorating with moody, meaningful touches transforms your space into a winter temple.",
  "Dec 11": "Your home during December holds the tension between festivity and depth. Both are honored.",
  "Dec 12": "Rest in the darkness. Your regenerative power needs quiet, solitude, and time to work.",
  "Dec 13": "A deeply moving seasonal experience — music, story, ritual — touches your soul at its core.",
  "Dec 14": "Your holiday generosity is fierce and particular. You give TO someone, not just at them.",
  "Dec 15": "The year's transformation highlight reel shows more courage, depth, and rebirth than you realized.",
  "Dec 16": "A quiet evening processing the year's transformations reveals how profoundly you've changed.",
  "Dec 17": "Your memory for what matters — the deep moments, the real conversations — guides perfect gift choices.",
  "Dec 18": "The deepening winter matches your inner season. Darkness holds you like a familiar friend.",
  "Dec 19": "Emotional honesty during the holiday season cuts through the superficial and finds what's real.",
  "Dec 20": "Your year of transformation has been unprecedented. Braver, deeper, and more powerfully yourself.",
  "Dec 21": "Winter solstice. The darkest night is your sanctuary. In this darkness, your power is absolute.",
  "Dec 22": "Capricorn season begins. Structural power meets emotional depth — you're ready to build on transformation.",
  "Dec 23": "Holiday preparations infused with your intensity create experiences people remember forever.",
  "Dec 24": "Tonight, your presence adds the depth that transforms a holiday gathering from pleasant to profound.",
  "Dec 25": "Today, receive love without conditions, without armor, without analyzing. Just let it in.",
  "Dec 26": "Post-holiday quiet is your paradise. Solitude, darkness, and the processing of deep emotions.",
  "Dec 27": "Your year-end journal should read like a transformation map. Document every death and rebirth.",
  "Dec 28": "A New Year intention forms: even deeper authenticity, braver vulnerability, and power used for healing.",
  "Dec 29": "Your transformations, your loves, and your rebirths are the three pillars of this year. All stand unshakable.",
  "Dec 30": "Tomorrow the year ends. Tonight, honor everything that died to make room for who you've become.",
  "Dec 31": "The year closes with you standing in your full, transformed power. Unbreakable, reborn, and deeply alive. Happy new year, Scorpio.",
};
