/** 365 daily quotes for Taurus — one for every day of the year. */
export const taurusDaily: Record<string, string> = {
  // ── January ──
  "Jan 1": "New beginnings deserve patience. Build this year slowly, steadily, and with intention — the Taurus way.",
  "Jan 2": "Your body knows what it needs today. Listen to it — a warm meal, a slow walk, a deep breath.",
  "Jan 3": "Stability isn't boring. It's the foundation everything beautiful gets built on. Trust your pace.",
  "Jan 4": "Financial goals set today have the persistence of your sign behind them. Start practical, dream huge.",
  "Jan 5": "Comfort is not weakness. Wrapping yourself in what feels good is how you recharge for greatness.",
  "Jan 6": "Your loyalty is being noticed, even if no one says it aloud. The right people always see steady love.",
  "Jan 7": "A sensory experience — music, food, a soft fabric — restores your spirit today more than any pep talk.",
  "Jan 8": "Stubbornness is just determination wearing a different hat. Wear it proudly when it serves you.",
  "Jan 9": "Change knocks gently today. Let it in on your terms. You adapt better than you think when you choose to.",
  "Jan 10": "Nature calls. Even in winter, fresh air and earth beneath your feet reconnect you to your source.",
  "Jan 11": "A money or resource decision benefits from your natural patience. Don't rush — the right choice will feel solid.",
  "Jan 12": "Your voice — speaking, singing, or just humming — carries healing energy today. Use it.",
  "Jan 13": "Someone needs your groundedness. Just your presence is enough to calm a storm. Show up and be steady.",
  "Jan 14": "A creative urge surfaces. Cooking, gardening, crafting — anything tactile feeds your Taurus soul.",
  "Jan 15": "Your resistance to speed is wisdom in disguise. The world rushes; you endure. That's a superpower.",
  "Jan 16": "Beauty makes you braver. Surround yourself with something aesthetically pleasing today and feel the shift.",
  "Jan 17": "A relationship deepens through shared silence. You don't always need words to communicate devotion.",
  "Jan 18": "Your fixed nature means you finish what you start. Today, pick one thing and see it through.",
  "Jan 19": "Indulgence and self-care are different. Today, choose the one that nourishes rather than just numbs.",
  "Jan 20": "Your values are non-negotiable, and that's beautiful. Stand firm on what matters without apology.",
  "Jan 21": "Comfort zones grow when you expand them slowly. Take one small step outside yours today.",
  "Jan 22": "Your practical wisdom cuts through someone's anxiety today. Ground them with your calm certainty.",
  "Jan 23": "Material security isn't shallow — it's the earth you plant your dreams in. Honor your need for it.",
  "Jan 24": "Slow mornings are sacred for you. Protect that ritual fiercely — it sets the tone for everything.",
  "Jan 25": "Your sensuality is a gift. Today, notice textures, scents, flavors, and light with full presence.",
  "Jan 26": "A long-term investment — financial, emotional, or creative — asks for your commitment. You were built for the long game.",
  "Jan 27": "Forgiveness is hard for fixed signs. But today, releasing one grudge could lighten your whole body.",
  "Jan 28": "Your determination outlasts everyone else's enthusiasm. That's not stubbornness — that's endurance.",
  "Jan 29": "Someone tries to rush you. Hold your ground gracefully. Your timing is impeccable.",
  "Jan 30": "A home improvement — even rearranging one shelf — shifts your energy beautifully today.",
  "Jan 31": "January ends with a sense of rootedness. You've built a foundation this month. Now it holds.",

  // ── February ──
  "Feb 1": "February's romantic energy suits your sensual nature perfectly. Open to love in all its forms.",
  "Feb 2": "Your patience with others is a form of love they rarely recognize. Today, someone does.",
  "Feb 3": "A creative project benefits from your hands-on approach. Touch, shape, and mold something real.",
  "Feb 4": "Your fixed earth energy grounds the scattered energy around you. Be the anchor today.",
  "Feb 5": "Financial clarity comes through simple math, not complicated schemes. Trust your practical instincts.",
  "Feb 6": "Your body is your temple — and today, it's asking for movement, nourishment, and rest in equal measure.",
  "Feb 7": "Silence speaks your language today. Let the quiet say what words cannot.",
  "Feb 8": "A stubborn pattern reveals itself. You can keep it or release it, but first, honestly see it.",
  "Feb 9": "Music moves you more deeply today than usual. Let a song carry you somewhere healing.",
  "Feb 10": "Your devotion to people you love is rare and precious. Today, let them know how deep it runs.",
  "Feb 11": "Material pleasures aren't guilty pleasures — they're legitimate needs. Enjoy something beautiful without apology.",
  "Feb 12": "A garden metaphor applies: prune what's dead, water what's growing, trust what's still underground.",
  "Feb 13": "Your love language is presence and touch. Express it today the way only a Taurus can.",
  "Feb 14": "Love is your domain. Whether giving or receiving, let your heart be as lush as a spring meadow.",
  "Feb 15": "After the romantic peak, your practical side returns. Love is also groceries, clean sheets, and showing up daily.",
  "Feb 16": "A possession or space that brings you comfort isn't materialistic — it's your way of creating security.",
  "Feb 17": "Your voice carries weight today. What you say will be remembered. Speak with your natural authenticity.",
  "Feb 18": "Change arrives in a nonthreatening package today. Accept it — your roots are strong enough to flex.",
  "Feb 19": "Your earthy wisdom helps someone make a grounded decision. Be the counsel others seek.",
  "Feb 20": "Cooking or sharing a meal is your love language in action. Feed someone today — literally or figuratively.",
  "Feb 21": "Your resistance to rushing is protecting you today. The slow path is the right path.",
  "Feb 22": "Something you've been nurturing patiently begins to show signs of growth. See? Your timing was right.",
  "Feb 23": "Self-worth isn't earned through performance. You are inherently valuable — period. Let that land.",
  "Feb 24": "A tactile creative outlet — pottery, baking, woodwork — satisfies on a soul level today.",
  "Feb 25": "Your loyalty is fierce and unwavering. Today, direct some of that fierce loyalty toward yourself.",
  "Feb 26": "Financial wisdom whispers: save where it's smart, spend where it brings genuine quality of life.",
  "Feb 27": "Your calm in chaos isn't apathy — it's strength. Others borrow your steadiness today.",
  "Feb 28": "The month closes with simple satisfaction. You showed up, stayed grounded, and held space. Enough.",
  "Feb 29": "Bonus day, bonus grace. Plant an extra seed — you have time to tend it into something real.",

  // ── March ──
  "Mar 1": "March energy pushes for speed, but your gift is pacing. Set the rhythm today — others will fall in step.",
  "Mar 2": "A creative impulse doesn't need to be perfect to be started. Begin the messy middle.",
  "Mar 3": "Your throat chakra is active — speak, sing, hum, or express vocally. Your voice heals today.",
  "Mar 4": "The ground is still cold, but seeds planted now by Taurus hands will bloom spectacularly.",
  "Mar 5": "Comfort isn't lazy — it's strategic recovery. Rest today to perform tomorrow.",
  "Mar 6": "Your practical side helps someone in a muddle. A clear list, a firm hug, a simple plan — your gifts.",
  "Mar 7": "Sensuality heightens today. Notice how things feel — fabric, air, water, someone's hand in yours.",
  "Mar 8": "Your determination quietly inspires everyone around you. You don't need to be loud to be powerful.",
  "Mar 9": "A material goal clarifies. What do you want to build, buy, or create? Name it and start.",
  "Mar 10": "Nature is waking up, and so is something in you. A new energy stirs beneath patient earth.",
  "Mar 11": "Financial discipline now creates summer abundance later. Your future self thanks today's choices.",
  "Mar 12": "Your resistance to change protects you from fads. Stay true to what's proven and genuine.",
  "Mar 13": "A home-cooked meal, a clean space, a moment of quiet — these are revolutionary acts of self-care for you.",
  "Mar 14": "Romance brews slowly for Taurus, and what brews slowly tastes richest. Be patient with love.",
  "Mar 15": "Your stamina outpaces every other sign. Whatever marathon you're running — you'll finish. Keep going.",
  "Mar 16": "Beauty is not frivolous to you — it's spiritual. Surround yourself with what moves your heart.",
  "Mar 17": "Luck meets preparation, and Taurus is always prepared. Today, something fortunate arrives because you earned it.",
  "Mar 18": "Your stubbornness about quality over quantity is vindicated today. Never settle for less than excellent.",
  "Mar 19": "Spring approaches, and your earth sign body feels it before anyone else. Something is ready to bloom.",
  "Mar 20": "Spring equinox. New growth energy meets your patient cultivation. The harvest will be beautiful.",
  "Mar 21": "Aries season fires up the world, but you stay grounded. Your steadiness is medicine for the frenetic energy around you.",
  "Mar 22": "Your values act as a compass today. When uncertain, ask yourself what truly matters. The answer is always there.",
  "Mar 23": "Physical touch — a massage, a hug, hands in soil — reconnects you to your center today.",
  "Mar 24": "A financial plan or budget review energizes rather than bores you. Numbers are poetry to practical Taurus.",
  "Mar 25": "Someone's impatience tests yours. Hold steady. Their rush is not your emergency.",
  "Mar 26": "Your love for the finer things isn't vanity — it's an appreciation for craftsmanship and effort. Honor that taste.",
  "Mar 27": "Creative energy flows through your hands today. Make, build, arrange, or cook something that brings you joy.",
  "Mar 28": "Your capacity to simply be — without performing, proving, or producing — is deeply healing to others.",
  "Mar 29": "A garden, real or metaphorical, needs tending today. Pull a weed, add water, and trust the seasons.",
  "Mar 30": "Comfort and ambition are not opposites. Today, pursue your goals from a place of grounded ease.",
  "Mar 31": "March ends with earthy satisfaction. You've been steady all month, and steadiness always wins.",

  // ── April ──
  "Apr 1": "Playfulness doesn't come naturally, but today, surprise yourself. Laughter loosens even the most fixed earth.",
  "Apr 2": "Your season approaches. Feel the anticipation building — the earth is about to celebrate you.",
  "Apr 3": "A possession or investment begins to appreciate. Your eye for lasting value always pays off.",
  "Apr 4": "Your body knows spring before your calendar does. Stretch, move, feel the energy rising.",
  "Apr 5": "Patience is your love letter to the future. Everything you tend today becomes tomorrow's abundance.",
  "Apr 6": "Someone's erratic energy tests your calm. Breathe, root, and remember: you are the mountain, not the weather.",
  "Apr 7": "Your senses are heightened today. Eat something exquisite, listen to music that moves you, be fully alive.",
  "Apr 8": "Stability doesn't mean stagnation. You can grow while staying rooted — trees prove this every day.",
  "Apr 9": "A commitment you made long ago is quietly paying dividends. The long game is your game.",
  "Apr 10": "Your artistic eye notices what others miss. A color, a pattern, a composition — you see beauty everywhere.",
  "Apr 11": "Self-worth flows from within, not from what you own or earn. Though you appreciate both, know the difference.",
  "Apr 12": "Your earth element heals through grounding. Walk barefoot, garden with bare hands, touch something ancient.",
  "Apr 13": "A culinary adventure — a new recipe, a farmers market, a bold flavor — feeds your soul today.",
  "Apr 14": "Your stubbornness about integrity is never wrong. Hold that line.",
  "Apr 15": "Financial awareness peaks. Whether saving, investing, or spending wisely — your instincts are sharp.",
  "Apr 16": "Nature mirrors your inner state today. Step outside and find yourself reflected in the landscape.",
  "Apr 17": "Your presence is a gift that doesn't need wrapping. Just being there is more than enough.",
  "Apr 18": "Something you've been building is almost ready to reveal. Don't rush the unveiling — perfect it.",
  "Apr 19": "Tomorrow begins your season. Tonight, honor what you've cultivated this year. It's more than you realize.",
  "Apr 20": "Happy Taurus season. The earth celebrates you — lush, sensual, steadfast, and magnificently real.",
  "Apr 21": "Your birthday energy radiates stability and warmth. Everyone wants to be in your orbit right now.",
  "Apr 22": "Earth Day lands in your season for a reason. You embody the planet's patience, beauty, and resilience.",
  "Apr 23": "Your season amplifies your natural magnetism. What you desire is drawn to your groundedness.",
  "Apr 24": "Luxury isn't excess for you — it's quality at its peak. Indulge in one exquisite thing today.",
  "Apr 25": "Your fixed nature means when you decide, the universe rearranges. Decide something important today.",
  "Apr 26": "Gardens, both literal and metaphorical, are your cathedral. Tend yours with love.",
  "Apr 27": "Your voice carries extra power during your season. Sing, speak, laugh out loud. Let it ring.",
  "Apr 28": "Financial and material blessings flow toward those who appreciate them — and no one appreciates like Taurus.",
  "Apr 29": "Your stubborn belief in goodness is revolutionary. Keep believing when the world says not to.",
  "Apr 30": "April ends with your season in full bloom. You are exactly where you need to be. Root here.",

  // ── May ──
  "May 1": "May Day is Taurus energy incarnate — fertility, abundance, and earthly pleasure. Celebrate.",
  "May 2": "Your season peaks with sensual, grounded power. Own every molecule of your being today.",
  "May 3": "A material possession brings unexpected emotional comfort today. Your instinct to invest in quality proves right again.",
  "May 4": "Someone tries to hurry your process. Smile, nod, and maintain your pace. History rewards the tortoise.",
  "May 5": "Celebration is not optional today. What you've built deserves recognition — even if only from yourself.",
  "May 6": "Your love for beauty extends to the people you surround yourself with. Curate your circle with care.",
  "May 7": "Physical comfort and emotional security merge today. A cozy space heals a weary heart.",
  "May 8": "Your reliability is someone's lifeline. That consistency you offer? It's more valuable than any grand gesture.",
  "May 9": "Spring is at peak richness, and so are you. Absorb the beauty around you — it refuels your very essence.",
  "May 10": "A nurturing instinct surfaces powerfully. Whether for a person, a pet, or a plant — tend something living.",
  "May 11": "Your practical magic turns chaos into order today. Someone's mess becomes manageable in your hands.",
  "May 12": "Your taste is impeccable and today it's needed. Make the aesthetic decision others hesitate on.",
  "May 13": "Resist the urge to splurge impulsively. The thing worth having is worth waiting and saving for.",
  "May 14": "Love expressed through action — cooking, fixing, holding, staying — is more eloquent than any sonnet.",
  "May 15": "Midway through the month, your Taurus energy is at its most centered. Ground into this feeling.",
  "May 16": "A walk through a garden or forest reconnects you to your earth element. This isn't leisure — it's medicine.",
  "May 17": "Your determination is a quiet force that reshapes reality. Apply it to your biggest dream today.",
  "May 18": "Touch is communication for you. A handshake, a hug, a shoulder squeeze — connect physically today.",
  "May 19": "Your season wanes but your power doesn't. The qualities you embody are needed all year long.",
  "May 20": "The last day of your solar season. Honor what you are: patient, strong, devoted, and irreplaceable.",
  "May 21": "Gemini season begins. Mental agility asks you to flex your curiosity and lighten your grip.",
  "May 22": "Adapt to the air energy without losing your ground. You can think fast and still move at your pace.",
  "May 23": "A conversation opens a door you didn't see. Let ideas in, even the ones that challenge your certainties.",
  "May 24": "Your voice is your instrument — literally and metaphorically. Express something you've been holding in.",
  "May 25": "Variety may not be your comfort zone, but today it's your growth edge. Try one new thing.",
  "May 26": "Financial wisdom says: diversify, but don't abandon what's proven. You know the difference intuitively.",
  "May 27": "Your steady nature provides the bass note in a world of treble. Keep that low hum going.",
  "May 28": "A friendship deepens through honest conversation. Your realness is a magnet for authentic connection.",
  "May 29": "Your body holds tension in predictable places. Offer it targeted care today — massage, stretching, or warmth.",
  "May 30": "A practical skill you possess is admired or needed today. Share it generously.",
  "May 31": "May ends with quiet pride. Your season left you richer in all the ways that matter.",

  // ── June ──
  "Jun 1": "June lightness asks your earth to dance. Let a breeze move you — figuratively, if not literally.",
  "Jun 2": "Communication sharpens today. Say the thing you've been mulling over — your words carry weight.",
  "Jun 3": "A short trip or local exploration satisfies your wanderlust without disrupting your routine.",
  "Jun 4": "Learning something new engages your determined mind. Once you commit to knowledge, you absorb deeply.",
  "Jun 5": "Your practical nature applies even to friendships: show up when it's hard, not just when it's fun.",
  "Jun 6": "Music is your direct line to emotion today. Create a playlist that matches your inner landscape.",
  "Jun 7": "Social energy increases. You don't need to be the loudest — your warm presence draws people in.",
  "Jun 8": "A dual perspective on a problem reveals a solution your fixed nature might have missed. Stay open.",
  "Jun 9": "Your sensuality finds expression through food today. Cook with love, eat with presence.",
  "Jun 10": "Financial opportunities arrive through connections. Network from your genuine self, not a script.",
  "Jun 11": "Routine is your rhythm, but today, jazz it up slightly. A small change refreshes the whole pattern.",
  "Jun 12": "Your stubborn optimism about someone or something is validated today. You were right to believe.",
  "Jun 13": "Physical comfort is non-negotiable, and that's fine. Arrange your space for maximum ease.",
  "Jun 14": "Your quiet confidence is attractive today. People see your solidity and want to lean on it.",
  "Jun 15": "Half the year gone. Your Taurus consistency means you're ahead of those who sprinted and burned out.",
  "Jun 16": "A home project or nesting instinct takes priority. Your space is an extension of your Self.",
  "Jun 17": "Patience with a loved one is tested. Dig into your deep earthen reserves — they're boundless.",
  "Jun 18": "Your creative energy flows through physical making today. Use your hands to express your heart.",
  "Jun 19": "A commitment you're considering becomes clearer. When a Taurus finally decides, the universe aligns.",
  "Jun 20": "Summer approaches and your earthy nature prepares for abundance. Tend what you've planted.",
  "Jun 21": "Summer solstice. The longest day fuels your steady flame. Bask in light and warmth — you've earned it.",
  "Jun 22": "Emotional depth surfaces in still waters. Feel your feelings today without rushing to resolve them.",
  "Jun 23": "Your home becomes a sanctuary today. Clean, beautify, or simply sit in your sacred space.",
  "Jun 24": "A creative collaboration benefits from your grounding energy. Be the anchor in a sea of ideas.",
  "Jun 25": "Self-care is not selfish for you — it's essential infrastructure. Maintain it without guilt.",
  "Jun 26": "Trust your body's wisdom over anyone's diet advice. You know what fuels you best.",
  "Jun 27": "Your material world reflects your inner state. What does your environment say? Adjust accordingly.",
  "Jun 28": "A nostalgia wave hits. Let it wash over you, but don't plant your flag there. Memories nourish; they don't sustain.",
  "Jun 29": "Your loyalty to what works might prevent you from what's better. Be discerning about when to hold and when to fold.",
  "Jun 30": "June ends with earthy contentment. Half the year down, and you've been exactly what the world needed: steady.",

  // ── July ──
  "Jul 1": "Cancer season warms your already nurturing nature. A home-focused day recharges everything.",
  "Jul 2": "Emotional security is as important as financial security. Invest in your inner peace today.",
  "Jul 3": "Your kitchen is your laboratory today. Create something nourishing and share it freely.",
  "Jul 4": "Freedom looks different for you — it's the freedom to build, tend, and grow at your own pace.",
  "Jul 5": "Your protective instincts strengthen in Cancer season. Guard what matters with gentle fierceness.",
  "Jul 6": "Water nurtures earth. Let emotions flow today instead of damming them. Feeling IS strength.",
  "Jul 7": "A family connection deepens through shared tradition or a simple meal together. You set the table for love.",
  "Jul 8": "Your physical comfort needs are amplified. Honor them without apology — silk sheets aren't a sin.",
  "Jul 9": "A financial opportunity connected to home or family deserves investigation. Your instincts say yes — verify with numbers.",
  "Jul 10": "Your steady love is someone's safe harbor. Today, acknowledge how much your consistency means to those around you.",
  "Jul 11": "Nostalgia and progress can coexist. Keep the lessons from the past while walking into the future.",
  "Jul 12": "Gardening — or any tending of living things — is not just a hobby for you. It's spiritual practice.",
  "Jul 13": "Your patience with a slow-developing situation is almost at its limit. Hold a little longer — the breakthrough is near.",
  "Jul 14": "Sensory pleasures peak today. Eat something extraordinary, listen to something beautiful, touch something soft.",
  "Jul 15": "Mid-month grounds you into what matters: health, home, love, and the tangible beauty of daily life.",
  "Jul 16": "Your loyalty to your routines borders on sacred. And maybe it should be. Rituals create reality.",
  "Jul 17": "An emotional conversation requires your earthy groundedness. Be the steady voice of reason and love.",
  "Jul 18": "Property, real estate, or home-related matters favor your sign today. Trust your material instincts.",
  "Jul 19": "Your bull nature can be tender as well as tremendous. Show the tender side today.",
  "Jul 20": "Domestic harmony is your masterpiece. Today, paint another brushstroke of peace in your space.",
  "Jul 21": "A stubborn issue resolves when you apply patience instead of force. Water wears stone, not the other way around.",
  "Jul 22": "Your emotional reserves are deeper than the ocean. Draw from them when a loved one needs stability.",
  "Jul 23": "Leo season begins. Fire meets earth — passion meets patience. Let the warmth enliven without burning.",
  "Jul 24": "Your creative expression takes a bolder turn. Let yourself be seen more than usual.",
  "Jul 25": "Generosity comes naturally when you feel secure. Today, your security allows great giving.",
  "Jul 26": "Entertainment and pleasure deserve a place in your structured world. Play is productive for you.",
  "Jul 27": "Your heart opens wider when you feel safe. Build that safety and watch love expand.",
  "Jul 28": "A child, pet, or creative project needs your patient guidance. You're the ideal nurturer today.",
  "Jul 29": "Your sensuality glows with Leo confidence. Own your physical presence radiantly.",
  "Jul 30": "An investment in quality over quantity proves correct — again. Your taste continues to serve you.",
  "Jul 31": "July closes with warmth and fullness. Your earth has been well-watered and well-tended. Grow on.",

  // ── August ──
  "Aug 1": "Leo's fire warms your steady earth. Creative confidence surges — make something bold today.",
  "Aug 2": "Your determination combined with creative fire makes you nearly unstoppable. Choose your one thing and go.",
  "Aug 3": "Recognition or appreciation comes your way today. Accept it as the natural harvest of your labor.",
  "Aug 4": "Your steadfast nature grounds Leo's dramatic energy around you. Be the calm center.",
  "Aug 5": "A pleasure or luxury you've been eyeing is worth it if it brings lasting joy, not just a momentary thrill.",
  "Aug 6": "Children, creativity, or romance highlight the day. Whatever brings you alive — give it your full attention.",
  "Aug 7": "Your financial instincts are exceptionally sharp today. Make the move you've been researching.",
  "Aug 8": "Physical vitality is high. Use it for something that also brings you joy — don't just endure, enjoy.",
  "Aug 9": "Your loyalty in love or friendship is being reciprocated beautifully today. Feel it and soak it in.",
  "Aug 10": "A creative expression — visual, culinary, musical — feels like it flows from a deeper place. Trust it.",
  "Aug 11": "Your perseverance is being tested. You'll pass — you always do. But today, pace yourself deliberately.",
  "Aug 12": "Someone tries to shake your foundation. Stand your ground with calm ferocity. Your roots go deep.",
  "Aug 13": "Your appetite for beauty and quality inspires someone today. Never apologize for high standards.",
  "Aug 14": "Sunlight on your skin literally recharges your earthen battery. Get outside and absorb it.",
  "Aug 15": "The midpoint of August finds you grounded and generous. Give from overflow rather than obligation.",
  "Aug 16": "A possession reveals its sentimental value beyond its material worth. Some things are priceless.",
  "Aug 17": "Your quiet power is louder than anyone's noise today. Lead by example, not volume.",
  "Aug 18": "Romance favored. Your sensual, devoted love language speaks directly to someone's heart.",
  "Aug 19": "An end-of-summer project needs finishing. Your stamina and focus get it across the line.",
  "Aug 20": "Your body holds seasonal transitions in its bones. Ease into the coming shift with extra self-care.",
  "Aug 21": "Late summer bounty mirrors your own abundance. Take stock of what you've grown this year.",
  "Aug 22": "The transition from fire to earth energy feels like coming home. Settle into the shift.",
  "Aug 23": "Virgo season begins. Fellow earth sign energy sharpens your already practical nature. Refine and perfect.",
  "Aug 24": "Attention to detail comes easier today. The small things that make big differences get your focus.",
  "Aug 25": "Your health routines deserve the same devotion you give your financial plans. Body is wealth too.",
  "Aug 26": "Organizing or decluttering your space creates surprising emotional relief. Clear the physical, clear the mental.",
  "Aug 27": "A skill you use daily deserves upgrading. Invest in getting even better at what you already know.",
  "Aug 28": "Your practical wisdom helps a friend or colleague with a real-world problem. Be the counselor.",
  "Aug 29": "Quality sleep is non-negotiable for earth signs. Protect tonight's rest like the investment it is.",
  "Aug 30": "Nature's late-summer harvest reminds you: patience and steady effort always yield abundance.",
  "Aug 31": "August ends with quiet pride and earthy satisfaction. What you've cultivated is starting to fruit.",

  // ── September ──
  "Sep 1": "September's productive energy harmonizes with your nature. Steady progress on meaningful work today.",
  "Sep 2": "Your meticulousness shines. Whatever you touch today gets better because of your attention.",
  "Sep 3": "A health goal takes root today. Earth signs have natural body wisdom — trust yours and begin.",
  "Sep 4": "Your practical approach to problems saves time and resources today. No drama, just results.",
  "Sep 5": "Service to your community — local or personal — feeds your sense of purpose. Help today.",
  "Sep 6": "Beauty in the details: notice the way light falls, how a meal looks on the plate. You are the artist of everyday.",
  "Sep 7": "A financial review reveals you're in better shape than you thought. Your steady habits are paying off.",
  "Sep 8": "Your body and mind align through a wellness practice today. Yoga, walking, or cooking — choose what grounds you.",
  "Sep 9": "Perfectionism isn't your usual struggle, but today, done is better than perfect. Ship it.",
  "Sep 10": "Your earthy realism grounds someone's anxiety today. Your steady voice calms spiraling minds.",
  "Sep 11": "Craftsmanship matters to you. Whatever you're creating, give it the quality that makes you proud.",
  "Sep 12": "Your routine is your religion. Today, honor the small rituals that hold your life together.",
  "Sep 13": "A harvest begins — of something you planted months ago with quiet hope. It's arriving.",
  "Sep 14": "Communication about practical matters goes smoothly today. Be clear, be kind, be concise.",
  "Sep 15": "Your patience outlasts the problem. Whatever's been stressful is about to resolve through simple endurance.",
  "Sep 16": "Physical comfort adjustments — a better chair, softer lighting, warmer blanket — have outsized effects on your wellbeing.",
  "Sep 17": "Your reliability is currency in this scattered world. People invest trust in you because you always deliver.",
  "Sep 18": "Earth sign solidarity: you, Virgo, and Capricorn energy create a stable foundation for big dreams.",
  "Sep 19": "A creative skill you've been honing quietly impresses someone today. Mastery takes time — you gave it time.",
  "Sep 20": "Your garden, real or metaphorical, is approaching peak harvest. Don't forget to enjoy what you've grown.",
  "Sep 21": "Autumn arrives and your body knows it. Adjust your rhythms to match the season's slower cadence.",
  "Sep 22": "Libra season begins. Beauty, balance, and partnership energy aligns with your Venusian nature.",
  "Sep 23": "Your ruler Venus is highlighted. Love, luxury, and aesthetics all flow more freely. Receive them.",
  "Sep 24": "Partnership energy asks: are you giving and receiving equally? Adjust the balance today.",
  "Sep 25": "Your eye for beauty guides a decision today — trust it more than spreadsheets or logic.",
  "Sep 26": "A diplomatic approach serves you better than stubbornness today. Bend slightly — it's not breaking.",
  "Sep 27": "Art and aesthetics speak to your deepest self. Visit a gallery, listen to music, notice architecture.",
  "Sep 28": "Romance warms under Venus energy. Express devotion through your signature acts of love and service.",
  "Sep 29": "Your financial instincts meet Libra's awareness of fairness. Negotiate with heart and numbers equally.",
  "Sep 30": "September ends with autumnal grace. You've harvested beautifully. Now, prepare for the quiet season ahead.",

  // ── October ──
  "Oct 1": "October cools the world and deepens your earthy introspection. What matters most becomes clearer.",
  "Oct 2": "Beauty in decay — autumn leaves, late-blooming flowers — teaches you that endings have their own elegance.",
  "Oct 3": "Your partnerships — romantic, creative, professional — benefit from your steady, honest attention today.",
  "Oct 4": "A major aesthetic decision — redecorating, wardrobe, personal style — aligns with your refined taste.",
  "Oct 5": "Balance between giving and holding isn't selfish — it's sustainable. Protect your resources wisely.",
  "Oct 6": "Venus guides your interactions today. Charm, grace, and genuine warmth open every door.",
  "Oct 7": "Your fixed nature meets Libra's call for flexibility. Compromise today serves a greater harmony.",
  "Oct 8": "A financial negotiation or partnership agreement benefits from your grounded, fair approach.",
  "Oct 9": "Your calm demeanor masks deep feeling today. Let someone trusted see beneath the surface.",
  "Oct 10": "Quality time with a partner or close friend is medicine. No screens, no agendas — just presence.",
  "Oct 11": "An artistic impulse surges. Paint, cook, arrange, design — let beauty flow through your hands.",
  "Oct 12": "Fairness in all dealings is your standard today. Hold others and yourself to it equally.",
  "Oct 13": "Your sensuality deepens as the season cools. Warm drinks, soft blankets, candlelight — indulge fully.",
  "Oct 14": "A long-term partnership shows its enduring value today. What you've invested in together is solid.",
  "Oct 15": "Your resolve about something important strengthens. When Taurus is certain, mountains move.",
  "Oct 16": "Comfort food is not just comfort — it's connection to memory, season, and love. Cook with all of that.",
  "Oct 17": "Your stubborn grace is exactly what a tense situation needs. Stay steady when others wobble.",
  "Oct 18": "An investment decision clicks into place. Your patience in gathering information pays off now.",
  "Oct 19": "Your home reflects your inner peace. Today, create more of both — simultaneously.",
  "Oct 20": "Loyalty is love's endurance run, and you're built for it. Honor the commitments that honor you.",
  "Oct 21": "Deep transformation energy arrives. Even fixed earth can shift when the time is right.",
  "Oct 22": "Scorpio season intensifies everything. Feel it fully — your earth can hold any emotional weight.",
  "Oct 23": "Emotional depth that you usually control surfaces unexpectedly. Let it. Vulnerability enriches.",
  "Oct 24": "Your resources — material, emotional, spiritual — are being alchemized. Something precious is forming.",
  "Oct 25": "A power dynamic in a relationship becomes visible. Address it with your signature honest calm.",
  "Oct 26": "Your opposite sign's energy (Scorpio) teaches through intensity. What you resist most right now is your teacher.",
  "Oct 27": "Shared finances or deep emotional investments ask for your attention and your courage.",
  "Oct 28": "Your body processes change through physical sensation. Move, stretch, or sweat through what you're feeling.",
  "Oct 29": "Letting go of something you've held onto fiercely is not loss — it's making room for what's next.",
  "Oct 30": "Your earthen strength meets the supernatural thinning of the veil. Trust your instincts about what's real.",
  "Oct 31": "The mysteries of life don't frighten you — they intrigue. Stay curious about the unseen today.",

  // ── November ──
  "Nov 1": "Deep channels of feeling run through you today. Don't dam them — let them carve something beautiful.",
  "Nov 2": "Remembrance is tangible for you. Honor those you've lost through something physical — a meal, flowers, or ritual.",
  "Nov 3": "Transformation is not your preferred mode, but today, lean into it. Your roots survive every storm.",
  "Nov 4": "A joint financial or emotional investment shows its return. Trust in partnership is validated.",
  "Nov 5": "Your stubbornness meets Scorpio's intensity. Either an immovable force or an unstoppable team — your choice.",
  "Nov 6": "Emotional honesty feels vulnerable but powerful today. Say what's true, even if your voice trembles.",
  "Nov 7": "Physical sensations tell emotional truths today. Tension in your neck, ease in your hands — listen.",
  "Nov 8": "Your material possessions reflect your values. Today, align them more closely. Keep what matters, release what doesn't.",
  "Nov 9": "A secret or hidden truth surfaces. Your grounded nature processes it slowly and wisely.",
  "Nov 10": "Intimacy deepens when you let someone see your unpolished self. Today, be real over refined.",
  "Nov 11": "Your perseverance through difficulty is not just admirable — it's heroic. Acknowledge how much you've endured.",
  "Nov 12": "A creative rebirth happens through destruction of the old. Let a defunct idea go so a new one can grow.",
  "Nov 13": "Your relationship with money is being refined today. Less accumulation, more alignment with purpose.",
  "Nov 14": "Physical healing accelerates when you apply your determination. Your body responds to your will.",
  "Nov 15": "Halfway through November, your earthy self finds footing in the intensity. Grounding is your gift.",
  "Nov 16": "Someone's gratitude for your consistency catches you off guard. You underestimate how much your steadiness means.",
  "Nov 17": "Your capacity to hold space for difficult emotions — yours or others' — is tremendous. Use it today.",
  "Nov 18": "A financial or material windfall arrives as natural consequence of your patient work. Not luck — harvest.",
  "Nov 19": "Your sensual nature finds beauty even in November's bareness. There is elegance in emptiness.",
  "Nov 20": "A transformation you've been resisting becomes irresistible. Let the change happen. You'll land on solid ground.",
  "Nov 21": "Sagittarius season begins. Fire on earth creates warmth and light. Let adventure warm your steady soul.",
  "Nov 22": "Expansion doesn't mean losing your foundation. You can explore while staying rooted.",
  "Nov 23": "Travel or learning broadens your perspective today. Your earthy wisdom gets philosophical.",
  "Nov 24": "Gratitude is natural for you when you pause to notice. Name your abundance out loud.",
  "Nov 25": "Your kitchen might be the happiest place in the world today. Feed people and feel purpose.",
  "Nov 26": "An optimistic view of the future arrives not from fantasy but from evidence. Your effort is building results.",
  "Nov 27": "Physical adventure — a brisk hike, exploring somewhere new — energizes your usually home-loving self.",
  "Nov 28": "Your beliefs solidify around what experience, not theory, has taught you. Trust your empirical wisdom.",
  "Nov 29": "A bold vision for next year forms. Your practical nature gives it legs and a timeline.",
  "Nov 30": "November ends with deep richness — emotional, material, spiritual. You've earned every bit.",

  // ── December ──
  "Dec 1": "December expands your vision. What do you want to build next year? The planning starts now.",
  "Dec 2": "Your earthy nature meets holiday magic. Create traditions that combine beauty with meaning.",
  "Dec 3": "A philosophical conversation deepens your understanding of something you took for granted.",
  "Dec 4": "Your generosity shines during the giving season. Give what you know best — comfort, quality, and presence.",
  "Dec 5": "Winter asks for hibernation wisdom. Slow down, store energy, and luxuriate in the darker months.",
  "Dec 6": "Your fixed nature makes you the rock in family holiday dynamics. Steady as ever, you hold the center.",
  "Dec 7": "A financial year-end review shows the power of consistent saving and smart spending. Celebrate your discipline.",
  "Dec 8": "Cooking is magic, and your kitchen is the laboratory. Create something extraordinary to share.",
  "Dec 9": "Your year-end reflections are practical and honest. What worked? What didn't? Adjust without drama.",
  "Dec 10": "Holiday decorating is an art form for you. Your aesthetic choices create wonder in every room.",
  "Dec 11": "Your loyalty to traditions gives continuity and meaning to the season. You are the keeper of memory.",
  "Dec 12": "Rest is productive in December. Your body is preparing for the next growing season. Let it.",
  "Dec 13": "A handmade or carefully chosen gift from you means more than anything expensive. Your thoughtfulness shows.",
  "Dec 14": "Comfort is your gift to the world this month. A warm space, a generous plate, a calm presence.",
  "Dec 15": "Your year has been one of steady progress. Not flashy, but real. The best kind.",
  "Dec 16": "Music carries special power for you today. Let holiday melodies move emotions words can't reach.",
  "Dec 17": "Your home becomes a gathering place. Open the door to those who need warmth — it's what Taurus does best.",
  "Dec 18": "Financial generosity and financial wisdom coexist in you beautifully. Give wisely and freely.",
  "Dec 19": "The year's slowdown matches your natural pace. For once, the world moves at Taurus speed. Enjoy it.",
  "Dec 20": "Gratitude for what you have — not longing for what you don't — defines this day beautifully.",
  "Dec 21": "Winter solstice. The earth rests, and so should you. Stillness is sacred, especially for an earth sign.",
  "Dec 22": "Capricorn season begins. Fellow earth sign energy amplifies your ambition and discipline.",
  "Dec 23": "Your year-end preparations are thorough and beautiful. Others wish they had your eye for detail.",
  "Dec 24": "Tonight, your home glows with exactly the warmth the world needs. You created this sanctuary. Be proud.",
  "Dec 25": "Today, you are the steady center of every gathering. Your love is a feast in itself.",
  "Dec 26": "The quiet after celebration is your favorite part. Leftover luxury and no agenda — pure Taurus bliss.",
  "Dec 27": "Your plans for the new year are forming — practical, beautiful, and rich with intention.",
  "Dec 28": "Review what you've cultivated this year. Every harvest began with your patient planting.",
  "Dec 29": "Your body and spirit need restoration before the new year. Give yourself permission for deep rest.",
  "Dec 30": "Tomorrow the year ends. Today, hold gratitude for every meal shared, every touch exchanged, every bloom you grew.",
  "Dec 31": "The year ends and you stand on solid ground — as always. You've been steady, strong, and real. That's everything.",
};
